# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dashboardwindowFRAMETEST.ui',
# licensing of 'dashboardwindowFRAMETEST.ui' applies.
#
# Created: Sun Jul 28 17:38:05 2019
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_DashboardWindow(object):
    def setupUi(self, DashboardWindow):
        DashboardWindow.setObjectName("DashboardWindow")
        DashboardWindow.resize(1182, 686)
        self.centralwidget = QtWidgets.QWidget(DashboardWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.Header = QtWidgets.QHBoxLayout()
        self.Header.setObjectName("Header")
        self.DashboardTitle = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DashboardTitle.sizePolicy().hasHeightForWidth())
        self.DashboardTitle.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.DashboardTitle.setFont(font)
        self.DashboardTitle.setObjectName("DashboardTitle")
        self.Header.addWidget(self.DashboardTitle)
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(100, 100))
        self.label.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("img/re3d.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.Header.addWidget(self.label)
        self.gridLayout.addLayout(self.Header, 0, 0, 1, 1)
        self.Dashboard = QtWidgets.QVBoxLayout()
        self.Dashboard.setObjectName("Dashboard")
        self.gridLayout.addLayout(self.Dashboard, 1, 0, 1, 1)
        self.buttons = QtWidgets.QHBoxLayout()
        self.buttons.setObjectName("buttons")
        self.StartServer = QtWidgets.QPushButton(self.centralwidget)
        self.StartServer.setObjectName("StartServer")
        self.buttons.addWidget(self.StartServer)
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser.sizePolicy().hasHeightForWidth())
        self.textBrowser.setSizePolicy(sizePolicy)
        self.textBrowser.setMinimumSize(QtCore.QSize(0, 25))
        self.textBrowser.setMaximumSize(QtCore.QSize(16777215, 25))
        self.textBrowser.setObjectName("textBrowser")
        self.buttons.addWidget(self.textBrowser)
        self.Quit = QtWidgets.QPushButton(self.centralwidget)
        self.Quit.setObjectName("Quit")
        self.buttons.addWidget(self.Quit)
        self.gridLayout.addLayout(self.buttons, 2, 0, 1, 1)
        DashboardWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(DashboardWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1182, 22))
        self.menubar.setNativeMenuBar(False)
        self.menubar.setObjectName("menubar")
        self.Manage = QtWidgets.QMenu(self.menubar)
        self.Manage.setObjectName("Manage")
        DashboardWindow.setMenuBar(self.menubar)
        self.toolBar = QtWidgets.QToolBar(DashboardWindow)
        self.toolBar.setObjectName("toolBar")
        DashboardWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.AddMachine = QtWidgets.QAction(DashboardWindow)
        self.AddMachine.setObjectName("AddMachine")
        self.DoSomethingElse = QtWidgets.QAction(DashboardWindow)
        self.DoSomethingElse.setObjectName("DoSomethingElse")
        self.actionSettings = QtWidgets.QAction(DashboardWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.Manage.addAction(self.AddMachine)
        self.Manage.addAction(self.DoSomethingElse)
        self.Manage.addAction(self.actionSettings)
        self.menubar.addAction(self.Manage.menuAction())

        self.retranslateUi(DashboardWindow)
        QtCore.QMetaObject.connectSlotsByName(DashboardWindow)

    def retranslateUi(self, DashboardWindow):
        DashboardWindow.setWindowTitle(QtWidgets.QApplication.translate("DashboardWindow", "Gigabot Dashboard", None, -1))
        self.DashboardTitle.setText(QtWidgets.QApplication.translate("DashboardWindow", "<html><head/><body><p><span style=\" font-size:26pt;\">Gigabot DashBoard</span></p></body></html>", None, -1))
        self.StartServer.setText(QtWidgets.QApplication.translate("DashboardWindow", "Start Server", None, -1))
        self.Quit.setText(QtWidgets.QApplication.translate("DashboardWindow", "Quit", None, -1))
        self.Manage.setTitle(QtWidgets.QApplication.translate("DashboardWindow", "Manage", None, -1))
        self.toolBar.setWindowTitle(QtWidgets.QApplication.translate("DashboardWindow", "toolBar", None, -1))
        self.AddMachine.setText(QtWidgets.QApplication.translate("DashboardWindow", "Add Machine", None, -1))
        self.DoSomethingElse.setText(QtWidgets.QApplication.translate("DashboardWindow", "View Connected Devices", None, -1))
        self.actionSettings.setText(QtWidgets.QApplication.translate("DashboardWindow", "Settings", None, -1))

