# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'module_gigabot.ui',
# licensing of 'module_gigabot.ui' applies.
#
# Created: Sun Jul 28 17:08:14 2019
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_GigabotModule(object):
    def setupUi(self, GigabotModule):
        GigabotModule.setObjectName("GigabotModule")
        GigabotModule.resize(320, 187)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(GigabotModule.sizePolicy().hasHeightForWidth())
        GigabotModule.setSizePolicy(sizePolicy)
        GigabotModule.setMinimumSize(QtCore.QSize(320, 187))
        GigabotModule.setMaximumSize(QtCore.QSize(450, 280))
        self.verticalLayout = QtWidgets.QVBoxLayout(GigabotModule)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.GigabotText = QtWidgets.QTextBrowser(GigabotModule)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GigabotText.sizePolicy().hasHeightForWidth())
        self.GigabotText.setSizePolicy(sizePolicy)
        self.GigabotText.setMinimumSize(QtCore.QSize(0, 30))
        self.GigabotText.setMaximumSize(QtCore.QSize(16777215, 55))
        self.GigabotText.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.GigabotText.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.GigabotText.setDocumentTitle("")
        self.GigabotText.setObjectName("GigabotText")
        self.horizontalLayout_4.addWidget(self.GigabotText)
        self.GigabotNum = QtWidgets.QTextBrowser(GigabotModule)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GigabotNum.sizePolicy().hasHeightForWidth())
        self.GigabotNum.setSizePolicy(sizePolicy)
        self.GigabotNum.setMinimumSize(QtCore.QSize(0, 30))
        self.GigabotNum.setMaximumSize(QtCore.QSize(16777215, 55))
        self.GigabotNum.setObjectName("GigabotNum")
        self.horizontalLayout_4.addWidget(self.GigabotNum)
        self.ViewMachine = QtWidgets.QPushButton(GigabotModule)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ViewMachine.sizePolicy().hasHeightForWidth())
        self.ViewMachine.setSizePolicy(sizePolicy)
        self.ViewMachine.setMinimumSize(QtCore.QSize(0, 30))
        self.ViewMachine.setMaximumSize(QtCore.QSize(40, 55))
        self.ViewMachine.setObjectName("ViewMachine")
        self.horizontalLayout_4.addWidget(self.ViewMachine)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.textBrowser = QtWidgets.QTextBrowser(GigabotModule)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser.sizePolicy().hasHeightForWidth())
        self.textBrowser.setSizePolicy(sizePolicy)
        self.textBrowser.setMaximumSize(QtCore.QSize(16777215, 25))
        self.textBrowser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.StatusLabel = QtWidgets.QLabel(GigabotModule)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StatusLabel.sizePolicy().hasHeightForWidth())
        self.StatusLabel.setSizePolicy(sizePolicy)
        self.StatusLabel.setMaximumSize(QtCore.QSize(16777215, 30))
        self.StatusLabel.setObjectName("StatusLabel")
        self.horizontalLayout.addWidget(self.StatusLabel)
        self.StatusText = QtWidgets.QTextBrowser(GigabotModule)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StatusText.sizePolicy().hasHeightForWidth())
        self.StatusText.setSizePolicy(sizePolicy)
        self.StatusText.setMaximumSize(QtCore.QSize(16777215, 30))
        self.StatusText.setObjectName("StatusText")
        self.horizontalLayout.addWidget(self.StatusText)
        self.StatusImg = QtWidgets.QLabel(GigabotModule)
        self.StatusImg.setMaximumSize(QtCore.QSize(30, 30))
        self.StatusImg.setText("")
        self.StatusImg.setPixmap(QtGui.QPixmap("img/Active.png"))
        self.StatusImg.setScaledContents(True)
        self.StatusImg.setObjectName("StatusImg")
        self.horizontalLayout.addWidget(self.StatusImg)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Nozzle1Img = QtWidgets.QLabel(GigabotModule)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Nozzle1Img.sizePolicy().hasHeightForWidth())
        self.Nozzle1Img.setSizePolicy(sizePolicy)
        self.Nozzle1Img.setMinimumSize(QtCore.QSize(40, 40))
        self.Nozzle1Img.setMaximumSize(QtCore.QSize(120, 120))
        self.Nozzle1Img.setText("")
        self.Nozzle1Img.setPixmap(QtGui.QPixmap("img/nozzle.png"))
        self.Nozzle1Img.setScaledContents(True)
        self.Nozzle1Img.setObjectName("Nozzle1Img")
        self.horizontalLayout_2.addWidget(self.Nozzle1Img)
        self.Nozzle2Img = QtWidgets.QLabel(GigabotModule)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Nozzle2Img.sizePolicy().hasHeightForWidth())
        self.Nozzle2Img.setSizePolicy(sizePolicy)
        self.Nozzle2Img.setMinimumSize(QtCore.QSize(40, 40))
        self.Nozzle2Img.setMaximumSize(QtCore.QSize(120, 120))
        self.Nozzle2Img.setText("")
        self.Nozzle2Img.setPixmap(QtGui.QPixmap("img/nozzle.png"))
        self.Nozzle2Img.setScaledContents(True)
        self.Nozzle2Img.setObjectName("Nozzle2Img")
        self.horizontalLayout_2.addWidget(self.Nozzle2Img)
        self.BedImg = QtWidgets.QLabel(GigabotModule)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BedImg.sizePolicy().hasHeightForWidth())
        self.BedImg.setSizePolicy(sizePolicy)
        self.BedImg.setMinimumSize(QtCore.QSize(40, 40))
        self.BedImg.setMaximumSize(QtCore.QSize(120, 120))
        self.BedImg.setText("")
        self.BedImg.setPixmap(QtGui.QPixmap("img/bed_unheated.png"))
        self.BedImg.setScaledContents(True)
        self.BedImg.setObjectName("BedImg")
        self.horizontalLayout_2.addWidget(self.BedImg)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Nozzle1Text = QtWidgets.QTextBrowser(GigabotModule)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Nozzle1Text.sizePolicy().hasHeightForWidth())
        self.Nozzle1Text.setSizePolicy(sizePolicy)
        self.Nozzle1Text.setMinimumSize(QtCore.QSize(0, 20))
        self.Nozzle1Text.setMaximumSize(QtCore.QSize(16777215, 40))
        self.Nozzle1Text.setObjectName("Nozzle1Text")
        self.horizontalLayout_3.addWidget(self.Nozzle1Text)
        self.Nozzle2Text = QtWidgets.QTextBrowser(GigabotModule)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Nozzle2Text.sizePolicy().hasHeightForWidth())
        self.Nozzle2Text.setSizePolicy(sizePolicy)
        self.Nozzle2Text.setMinimumSize(QtCore.QSize(0, 20))
        self.Nozzle2Text.setMaximumSize(QtCore.QSize(16777215, 40))
        self.Nozzle2Text.setObjectName("Nozzle2Text")
        self.horizontalLayout_3.addWidget(self.Nozzle2Text)
        self.BedText = QtWidgets.QTextBrowser(GigabotModule)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BedText.sizePolicy().hasHeightForWidth())
        self.BedText.setSizePolicy(sizePolicy)
        self.BedText.setMinimumSize(QtCore.QSize(0, 20))
        self.BedText.setMaximumSize(QtCore.QSize(16777215, 40))
        self.BedText.setObjectName("BedText")
        self.horizontalLayout_3.addWidget(self.BedText)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(GigabotModule)
        QtCore.QMetaObject.connectSlotsByName(GigabotModule)

    def retranslateUi(self, GigabotModule):
        GigabotModule.setWindowTitle(QtWidgets.QApplication.translate("GigabotModule", "Form", None, -1))
        self.GigabotText.setHtml(QtWidgets.QApplication.translate("GigabotModule", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt;\">Gigabot 3+ XLT</span></p></body></html>", None, -1))
        self.GigabotNum.setHtml(QtWidgets.QApplication.translate("GigabotModule", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt;\">512</span></p></body></html>", None, -1))
        self.ViewMachine.setText(QtWidgets.QApplication.translate("GigabotModule", "...", None, -1))
        self.textBrowser.setHtml(QtWidgets.QApplication.translate("GigabotModule", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">IP Address</p></body></html>", None, -1))
        self.StatusLabel.setText(QtWidgets.QApplication.translate("GigabotModule", "<html><head/><body><p><span style=\" font-size:14pt;\">Status:</span></p></body></html>", None, -1))
        self.StatusText.setHtml(QtWidgets.QApplication.translate("GigabotModule", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">On/Idle</p></body></html>", None, -1))

