# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'duexsetuppage_qt.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DuExSetupPage(object):
    def setupUi(self, DuExSetupPage):
        DuExSetupPage.setObjectName("DuExSetupPage")
        DuExSetupPage.resize(800, 448)
        DuExSetupPage.setMaximumSize(QtCore.QSize(800, 448))
        DuExSetupPage.setFocusPolicy(QtCore.Qt.NoFocus)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(DuExSetupPage)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.LeftBar = QtWidgets.QWidget(DuExSetupPage)
        self.LeftBar.setObjectName("LeftBar")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.LeftBar)
        self.verticalLayout_7.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_7.setSpacing(6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.w_pushbutton_permanent = QtWidgets.QPushButton(self.LeftBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_pushbutton_permanent.sizePolicy().hasHeightForWidth())
        self.w_pushbutton_permanent.setSizePolicy(sizePolicy)
        self.w_pushbutton_permanent.setMinimumSize(QtCore.QSize(160, 85))
        self.w_pushbutton_permanent.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.w_pushbutton_permanent.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/img/Save_Permanently.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.w_pushbutton_permanent.setIcon(icon)
        self.w_pushbutton_permanent.setIconSize(QtCore.QSize(140, 65))
        self.w_pushbutton_permanent.setObjectName("w_pushbutton_permanent")
        self.verticalLayout_7.addWidget(self.w_pushbutton_permanent)
        self.w_pushbutton_temporary = QtWidgets.QPushButton(self.LeftBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_pushbutton_temporary.sizePolicy().hasHeightForWidth())
        self.w_pushbutton_temporary.setSizePolicy(sizePolicy)
        self.w_pushbutton_temporary.setMinimumSize(QtCore.QSize(160, 85))
        self.w_pushbutton_temporary.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.w_pushbutton_temporary.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/img/img/Save_Temporarily.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.w_pushbutton_temporary.setIcon(icon1)
        self.w_pushbutton_temporary.setIconSize(QtCore.QSize(140, 65))
        self.w_pushbutton_temporary.setObjectName("w_pushbutton_temporary")
        self.verticalLayout_7.addWidget(self.w_pushbutton_temporary)
        self.line = QtWidgets.QFrame(self.LeftBar)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_7.addWidget(self.line)
        self.w_pushbutton_revert = QtWidgets.QPushButton(self.LeftBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_pushbutton_revert.sizePolicy().hasHeightForWidth())
        self.w_pushbutton_revert.setSizePolicy(sizePolicy)
        self.w_pushbutton_revert.setMinimumSize(QtCore.QSize(160, 50))
        self.w_pushbutton_revert.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.w_pushbutton_revert.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/img/img/Revert_to_last_saved.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.w_pushbutton_revert.setIcon(icon2)
        self.w_pushbutton_revert.setIconSize(QtCore.QSize(140, 30))
        self.w_pushbutton_revert.setObjectName("w_pushbutton_revert")
        self.verticalLayout_7.addWidget(self.w_pushbutton_revert)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_7.addItem(spacerItem1)
        self.horizontalLayout_3.addWidget(self.LeftBar)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.t1xIcon = QtWidgets.QPushButton(DuExSetupPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t1xIcon.sizePolicy().hasHeightForWidth())
        self.t1xIcon.setSizePolicy(sizePolicy)
        self.t1xIcon.setMinimumSize(QtCore.QSize(75, 75))
        self.t1xIcon.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.t1xIcon.setFocusPolicy(QtCore.Qt.NoFocus)
        self.t1xIcon.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/img/img/T1_X.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.t1xIcon.setIcon(icon3)
        self.t1xIcon.setIconSize(QtCore.QSize(100, 100))
        self.t1xIcon.setObjectName("t1xIcon")
        self.verticalLayout.addWidget(self.t1xIcon)
        self.w_lineedit_x1 = DuexLineEdit(DuExSetupPage)
        self.w_lineedit_x1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.w_lineedit_x1.setFont(font)
        self.w_lineedit_x1.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.w_lineedit_x1.setObjectName("w_lineedit_x1")
        self.verticalLayout.addWidget(self.w_lineedit_x1)
        self.t1yIcon = QtWidgets.QPushButton(DuExSetupPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t1yIcon.sizePolicy().hasHeightForWidth())
        self.t1yIcon.setSizePolicy(sizePolicy)
        self.t1yIcon.setMinimumSize(QtCore.QSize(75, 75))
        self.t1yIcon.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.t1yIcon.setFocusPolicy(QtCore.Qt.NoFocus)
        self.t1yIcon.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/img/img/T1_Y.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.t1yIcon.setIcon(icon4)
        self.t1yIcon.setIconSize(QtCore.QSize(100, 100))
        self.t1yIcon.setObjectName("t1yIcon")
        self.verticalLayout.addWidget(self.t1yIcon)
        self.w_lineedit_y1 = DuexLineEdit(DuExSetupPage)
        self.w_lineedit_y1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.w_lineedit_y1.setFont(font)
        self.w_lineedit_y1.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.w_lineedit_y1.setObjectName("w_lineedit_y1")
        self.verticalLayout.addWidget(self.w_lineedit_y1)
        self.gridLayout.addLayout(self.verticalLayout, 0, 1, 1, 1)
        self.NumberPad = QtWidgets.QHBoxLayout()
        self.NumberPad.setSpacing(10)
        self.NumberPad.setObjectName("NumberPad")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.w_pushbutton_7 = QtWidgets.QPushButton(DuExSetupPage)
        self.w_pushbutton_7.setMinimumSize(QtCore.QSize(70, 70))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.w_pushbutton_7.setFont(font)
        self.w_pushbutton_7.setFocusPolicy(QtCore.Qt.NoFocus)
        self.w_pushbutton_7.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/img/img/7.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.w_pushbutton_7.setIcon(icon5)
        self.w_pushbutton_7.setIconSize(QtCore.QSize(70, 70))
        self.w_pushbutton_7.setObjectName("w_pushbutton_7")
        self.verticalLayout_3.addWidget(self.w_pushbutton_7)
        self.w_pushbutton_4 = QtWidgets.QPushButton(DuExSetupPage)
        self.w_pushbutton_4.setMinimumSize(QtCore.QSize(70, 70))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.w_pushbutton_4.setFont(font)
        self.w_pushbutton_4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.w_pushbutton_4.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/img/img/4.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.w_pushbutton_4.setIcon(icon6)
        self.w_pushbutton_4.setIconSize(QtCore.QSize(70, 70))
        self.w_pushbutton_4.setObjectName("w_pushbutton_4")
        self.verticalLayout_3.addWidget(self.w_pushbutton_4)
        self.w_pushbutton_1 = QtWidgets.QPushButton(DuExSetupPage)
        self.w_pushbutton_1.setMinimumSize(QtCore.QSize(70, 70))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.w_pushbutton_1.setFont(font)
        self.w_pushbutton_1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.w_pushbutton_1.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/img/img/1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.w_pushbutton_1.setIcon(icon7)
        self.w_pushbutton_1.setIconSize(QtCore.QSize(70, 70))
        self.w_pushbutton_1.setObjectName("w_pushbutton_1")
        self.verticalLayout_3.addWidget(self.w_pushbutton_1)
        self.w_pushbutton_negative = QtWidgets.QPushButton(DuExSetupPage)
        self.w_pushbutton_negative.setMinimumSize(QtCore.QSize(70, 70))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.w_pushbutton_negative.setFont(font)
        self.w_pushbutton_negative.setFocusPolicy(QtCore.Qt.NoFocus)
        self.w_pushbutton_negative.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/img/img/+--.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.w_pushbutton_negative.setIcon(icon8)
        self.w_pushbutton_negative.setIconSize(QtCore.QSize(70, 70))
        self.w_pushbutton_negative.setObjectName("w_pushbutton_negative")
        self.verticalLayout_3.addWidget(self.w_pushbutton_negative)
        self.NumberPad.addLayout(self.verticalLayout_3)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(10)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.w_pushbutton_8 = QtWidgets.QPushButton(DuExSetupPage)
        self.w_pushbutton_8.setMinimumSize(QtCore.QSize(70, 70))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.w_pushbutton_8.setFont(font)
        self.w_pushbutton_8.setFocusPolicy(QtCore.Qt.NoFocus)
        self.w_pushbutton_8.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/img/img/8.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.w_pushbutton_8.setIcon(icon9)
        self.w_pushbutton_8.setIconSize(QtCore.QSize(70, 70))
        self.w_pushbutton_8.setObjectName("w_pushbutton_8")
        self.verticalLayout_5.addWidget(self.w_pushbutton_8)
        self.w_pushbutton_5 = QtWidgets.QPushButton(DuExSetupPage)
        self.w_pushbutton_5.setMinimumSize(QtCore.QSize(70, 70))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.w_pushbutton_5.setFont(font)
        self.w_pushbutton_5.setFocusPolicy(QtCore.Qt.NoFocus)
        self.w_pushbutton_5.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/img/img/5.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.w_pushbutton_5.setIcon(icon10)
        self.w_pushbutton_5.setIconSize(QtCore.QSize(70, 70))
        self.w_pushbutton_5.setObjectName("w_pushbutton_5")
        self.verticalLayout_5.addWidget(self.w_pushbutton_5)
        self.w_pushbutton_2 = QtWidgets.QPushButton(DuExSetupPage)
        self.w_pushbutton_2.setMinimumSize(QtCore.QSize(70, 70))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.w_pushbutton_2.setFont(font)
        self.w_pushbutton_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.w_pushbutton_2.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/img/img/2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.w_pushbutton_2.setIcon(icon11)
        self.w_pushbutton_2.setIconSize(QtCore.QSize(70, 70))
        self.w_pushbutton_2.setObjectName("w_pushbutton_2")
        self.verticalLayout_5.addWidget(self.w_pushbutton_2)
        self.w_pushbutton_0 = QtWidgets.QPushButton(DuExSetupPage)
        self.w_pushbutton_0.setMinimumSize(QtCore.QSize(70, 70))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.w_pushbutton_0.setFont(font)
        self.w_pushbutton_0.setFocusPolicy(QtCore.Qt.NoFocus)
        self.w_pushbutton_0.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/img/img/0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.w_pushbutton_0.setIcon(icon12)
        self.w_pushbutton_0.setIconSize(QtCore.QSize(70, 70))
        self.w_pushbutton_0.setObjectName("w_pushbutton_0")
        self.verticalLayout_5.addWidget(self.w_pushbutton_0)
        self.NumberPad.addLayout(self.verticalLayout_5)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(10)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.w_pushbutton_9 = QtWidgets.QPushButton(DuExSetupPage)
        self.w_pushbutton_9.setMinimumSize(QtCore.QSize(70, 70))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.w_pushbutton_9.setFont(font)
        self.w_pushbutton_9.setFocusPolicy(QtCore.Qt.NoFocus)
        self.w_pushbutton_9.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/img/img/9.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.w_pushbutton_9.setIcon(icon13)
        self.w_pushbutton_9.setIconSize(QtCore.QSize(70, 70))
        self.w_pushbutton_9.setObjectName("w_pushbutton_9")
        self.verticalLayout_4.addWidget(self.w_pushbutton_9)
        self.w_pushbutton_6 = QtWidgets.QPushButton(DuExSetupPage)
        self.w_pushbutton_6.setMinimumSize(QtCore.QSize(70, 70))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.w_pushbutton_6.setFont(font)
        self.w_pushbutton_6.setFocusPolicy(QtCore.Qt.NoFocus)
        self.w_pushbutton_6.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/img/img/6.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.w_pushbutton_6.setIcon(icon14)
        self.w_pushbutton_6.setIconSize(QtCore.QSize(70, 70))
        self.w_pushbutton_6.setObjectName("w_pushbutton_6")
        self.verticalLayout_4.addWidget(self.w_pushbutton_6)
        self.w_pushbutton_3 = QtWidgets.QPushButton(DuExSetupPage)
        self.w_pushbutton_3.setMinimumSize(QtCore.QSize(70, 70))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.w_pushbutton_3.setFont(font)
        self.w_pushbutton_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.w_pushbutton_3.setText("")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/img/img/3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.w_pushbutton_3.setIcon(icon15)
        self.w_pushbutton_3.setIconSize(QtCore.QSize(70, 70))
        self.w_pushbutton_3.setObjectName("w_pushbutton_3")
        self.verticalLayout_4.addWidget(self.w_pushbutton_3)
        self.w_pushbutton_decimal = QtWidgets.QPushButton(DuExSetupPage)
        self.w_pushbutton_decimal.setMinimumSize(QtCore.QSize(70, 70))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.w_pushbutton_decimal.setFont(font)
        self.w_pushbutton_decimal.setFocusPolicy(QtCore.Qt.NoFocus)
        self.w_pushbutton_decimal.setText("")
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/img/img/dot.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.w_pushbutton_decimal.setIcon(icon16)
        self.w_pushbutton_decimal.setIconSize(QtCore.QSize(70, 70))
        self.w_pushbutton_decimal.setObjectName("w_pushbutton_decimal")
        self.verticalLayout_4.addWidget(self.w_pushbutton_decimal)
        self.NumberPad.addLayout(self.verticalLayout_4)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.w_pushbutton_delete = QtWidgets.QPushButton(DuExSetupPage)
        self.w_pushbutton_delete.setMinimumSize(QtCore.QSize(70, 150))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.w_pushbutton_delete.setFont(font)
        self.w_pushbutton_delete.setFocusPolicy(QtCore.Qt.NoFocus)
        self.w_pushbutton_delete.setText("")
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/img/img/_-.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.w_pushbutton_delete.setIcon(icon17)
        self.w_pushbutton_delete.setIconSize(QtCore.QSize(70, 150))
        self.w_pushbutton_delete.setObjectName("w_pushbutton_delete")
        self.verticalLayout_2.addWidget(self.w_pushbutton_delete)
        self.w_pushbutton_clear = QtWidgets.QPushButton(DuExSetupPage)
        self.w_pushbutton_clear.setMinimumSize(QtCore.QSize(70, 150))
        self.w_pushbutton_clear.setFocusPolicy(QtCore.Qt.NoFocus)
        self.w_pushbutton_clear.setText("")
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/img/img/X.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.w_pushbutton_clear.setIcon(icon18)
        self.w_pushbutton_clear.setIconSize(QtCore.QSize(70, 150))
        self.w_pushbutton_clear.setObjectName("w_pushbutton_clear")
        self.verticalLayout_2.addWidget(self.w_pushbutton_clear)
        self.NumberPad.addLayout(self.verticalLayout_2)
        self.gridLayout.addLayout(self.NumberPad, 0, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 0, 3, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.BottomBar = QtWidgets.QWidget(DuExSetupPage)
        self.BottomBar.setObjectName("BottomBar")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.BottomBar)
        self.horizontalLayout_4.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.Back = QtWidgets.QPushButton(self.BottomBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Back.sizePolicy().hasHeightForWidth())
        self.Back.setSizePolicy(sizePolicy)
        self.Back.setMinimumSize(QtCore.QSize(65, 65))
        self.Back.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Back.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Back.setText("")
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/img/img/Small_arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Back.setIcon(icon19)
        self.Back.setIconSize(QtCore.QSize(55, 55))
        self.Back.setObjectName("Back")
        self.horizontalLayout_4.addWidget(self.Back)
        spacerItem4 = QtWidgets.QSpacerItem(282, 40, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.verticalLayout_6.addWidget(self.BottomBar)

        self.retranslateUi(DuExSetupPage)
        QtCore.QMetaObject.connectSlotsByName(DuExSetupPage)

    def retranslateUi(self, DuExSetupPage):
        _translate = QtCore.QCoreApplication.translate
        DuExSetupPage.setWindowTitle(_translate("DuExSetupPage", "ControlWindow"))
from duexsetuppage import DuexLineEdit
import img_rc
