# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settingspage_qt.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SettingsPage(object):
    def setupUi(self, SettingsPage):
        SettingsPage.setObjectName("SettingsPage")
        SettingsPage.setEnabled(True)
        SettingsPage.resize(800, 448)
        SettingsPage.setMinimumSize(QtCore.QSize(0, 0))
        SettingsPage.setMaximumSize(QtCore.QSize(800, 448))
        self.verticalLayout = QtWidgets.QVBoxLayout(SettingsPage)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.SettingsScrollArea = QtWidgets.QScrollArea(SettingsPage)
        self.SettingsScrollArea.setWidgetResizable(True)
        self.SettingsScrollArea.setObjectName("SettingsScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1925, 347))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout.setContentsMargins(25, 0, 0, 0)
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Serial = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Serial.sizePolicy().hasHeightForWidth())
        self.Serial.setSizePolicy(sizePolicy)
        self.Serial.setMinimumSize(QtCore.QSize(220, 220))
        self.Serial.setMaximumSize(QtCore.QSize(220, 220))
        self.Serial.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/img/Connection.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Serial.setIcon(icon)
        self.Serial.setIconSize(QtCore.QSize(220, 220))
        self.Serial.setObjectName("Serial")
        self.horizontalLayout.addWidget(self.Serial)
        self.UserUpdate = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.UserUpdate.sizePolicy().hasHeightForWidth())
        self.UserUpdate.setSizePolicy(sizePolicy)
        self.UserUpdate.setMinimumSize(QtCore.QSize(220, 220))
        self.UserUpdate.setMaximumSize(QtCore.QSize(220, 220))
        self.UserUpdate.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/img/img/Update.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.UserUpdate.setIcon(icon1)
        self.UserUpdate.setIconSize(QtCore.QSize(220, 220))
        self.UserUpdate.setObjectName("UserUpdate")
        self.horizontalLayout.addWidget(self.UserUpdate)
        self.w_pushbutton_duex = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_pushbutton_duex.sizePolicy().hasHeightForWidth())
        self.w_pushbutton_duex.setSizePolicy(sizePolicy)
        self.w_pushbutton_duex.setMinimumSize(QtCore.QSize(220, 220))
        self.w_pushbutton_duex.setMaximumSize(QtCore.QSize(220, 220))
        self.w_pushbutton_duex.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/img/img/Dual_Extruder_Calibration.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.w_pushbutton_duex.setIcon(icon2)
        self.w_pushbutton_duex.setIconSize(QtCore.QSize(220, 220))
        self.w_pushbutton_duex.setObjectName("w_pushbutton_duex")
        self.horizontalLayout.addWidget(self.w_pushbutton_duex)
        self.w_pushbutton_info = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_pushbutton_info.sizePolicy().hasHeightForWidth())
        self.w_pushbutton_info.setSizePolicy(sizePolicy)
        self.w_pushbutton_info.setMinimumSize(QtCore.QSize(220, 220))
        self.w_pushbutton_info.setMaximumSize(QtCore.QSize(220, 220))
        self.w_pushbutton_info.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/img/img/Info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.w_pushbutton_info.setIcon(icon3)
        self.w_pushbutton_info.setIconSize(QtCore.QSize(220, 220))
        self.w_pushbutton_info.setObjectName("w_pushbutton_info")
        self.horizontalLayout.addWidget(self.w_pushbutton_info)
        self.w_pushbutton_debug = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.w_pushbutton_debug.setMinimumSize(QtCore.QSize(220, 220))
        self.w_pushbutton_debug.setMaximumSize(QtCore.QSize(220, 220))
        self.w_pushbutton_debug.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/img/img/Debug.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.w_pushbutton_debug.setIcon(icon4)
        self.w_pushbutton_debug.setIconSize(QtCore.QSize(220, 220))
        self.w_pushbutton_debug.setObjectName("w_pushbutton_debug")
        self.horizontalLayout.addWidget(self.w_pushbutton_debug)
        self.Wifi = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.Wifi.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Wifi.sizePolicy().hasHeightForWidth())
        self.Wifi.setSizePolicy(sizePolicy)
        self.Wifi.setMinimumSize(QtCore.QSize(220, 220))
        self.Wifi.setMaximumSize(QtCore.QSize(220, 220))
        self.Wifi.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/img/img/Wifi.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Wifi.setIcon(icon5)
        self.Wifi.setIconSize(QtCore.QSize(220, 220))
        self.Wifi.setObjectName("Wifi")
        self.horizontalLayout.addWidget(self.Wifi)
        self.w_pushbutton_term = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.w_pushbutton_term.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_pushbutton_term.sizePolicy().hasHeightForWidth())
        self.w_pushbutton_term.setSizePolicy(sizePolicy)
        self.w_pushbutton_term.setMinimumSize(QtCore.QSize(220, 220))
        self.w_pushbutton_term.setMaximumSize(QtCore.QSize(220, 220))
        self.w_pushbutton_term.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/img/img/Terminal.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.w_pushbutton_term.setIcon(icon6)
        self.w_pushbutton_term.setIconSize(QtCore.QSize(220, 220))
        self.w_pushbutton_term.setObjectName("w_pushbutton_term")
        self.horizontalLayout.addWidget(self.w_pushbutton_term)
        self.Server = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.Server.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Server.sizePolicy().hasHeightForWidth())
        self.Server.setSizePolicy(sizePolicy)
        self.Server.setMinimumSize(QtCore.QSize(220, 220))
        self.Server.setMaximumSize(QtCore.QSize(220, 220))
        self.Server.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/img/img/Server_Setup.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Server.setIcon(icon7)
        self.Server.setIconSize(QtCore.QSize(220, 220))
        self.Server.setObjectName("Server")
        self.horizontalLayout.addWidget(self.Server)
        self.SettingsScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.SettingsScrollArea)
        self.BottomBar = QtWidgets.QWidget(SettingsPage)
        self.BottomBar.setObjectName("BottomBar")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.BottomBar)
        self.horizontalLayout_2.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Back = QtWidgets.QPushButton(self.BottomBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Back.sizePolicy().hasHeightForWidth())
        self.Back.setSizePolicy(sizePolicy)
        self.Back.setMinimumSize(QtCore.QSize(65, 65))
        self.Back.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Back.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Back.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/img/img/Small_arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Back.setIcon(icon8)
        self.Back.setIconSize(QtCore.QSize(55, 55))
        self.Back.setObjectName("Back")
        self.horizontalLayout_2.addWidget(self.Back)
        spacerItem = QtWidgets.QSpacerItem(282, 40, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addWidget(self.BottomBar)

        self.retranslateUi(SettingsPage)
        QtCore.QMetaObject.connectSlotsByName(SettingsPage)

    def retranslateUi(self, SettingsPage):
        _translate = QtCore.QCoreApplication.translate
        SettingsPage.setWindowTitle(_translate("SettingsPage", "TouchDisplay"))
import img_rc
