# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/dashboardwindow.ui',
# licensing of 'qt/dashboardwindow.ui' applies.
#
# Created: Fri Aug  2 11:40:39 2019
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_DashboardWindow(object):
    def setupUi(self, DashboardWindow):
        DashboardWindow.setObjectName("DashboardWindow")
        DashboardWindow.resize(1182, 686)
        self.centralwidget = QtWidgets.QWidget(DashboardWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.Header = QtWidgets.QHBoxLayout()
        self.Header.setObjectName("Header")
        self.DashboardTitle = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DashboardTitle.sizePolicy().hasHeightForWidth())
        self.DashboardTitle.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.DashboardTitle.setFont(font)
        self.DashboardTitle.setObjectName("DashboardTitle")
        self.Header.addWidget(self.DashboardTitle)
        self.Re3dIcon = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Re3dIcon.sizePolicy().hasHeightForWidth())
        self.Re3dIcon.setSizePolicy(sizePolicy)
        self.Re3dIcon.setMaximumSize(QtCore.QSize(100, 100))
        self.Re3dIcon.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Re3dIcon.setText("")
        self.Re3dIcon.setPixmap(QtGui.QPixmap("img/re3d.png"))
        self.Re3dIcon.setScaledContents(True)
        self.Re3dIcon.setObjectName("Re3dIcon")
        self.Header.addWidget(self.Re3dIcon)
        self.gridLayout.addLayout(self.Header, 0, 0, 1, 1)
        self.Dashboard = QtWidgets.QVBoxLayout()
        self.Dashboard.setObjectName("Dashboard")
        self.gridLayout.addLayout(self.Dashboard, 3, 0, 1, 1)
        self.buttons = QtWidgets.QHBoxLayout()
        self.buttons.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.buttons.setObjectName("buttons")
        self.ServerStatus = QtWidgets.QTextBrowser(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ServerStatus.sizePolicy().hasHeightForWidth())
        self.ServerStatus.setSizePolicy(sizePolicy)
        self.ServerStatus.setMinimumSize(QtCore.QSize(0, 25))
        self.ServerStatus.setMaximumSize(QtCore.QSize(200, 25))
        self.ServerStatus.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.ServerStatus.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.ServerStatus.setObjectName("ServerStatus")
        self.buttons.addWidget(self.ServerStatus)
        self.StartServer = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StartServer.sizePolicy().hasHeightForWidth())
        self.StartServer.setSizePolicy(sizePolicy)
        self.StartServer.setMinimumSize(QtCore.QSize(80, 0))
        self.StartServer.setMaximumSize(QtCore.QSize(100, 25))
        self.StartServer.setObjectName("StartServer")
        self.buttons.addWidget(self.StartServer)
        self.StopServer = QtWidgets.QPushButton(self.centralwidget)
        self.StopServer.setMaximumSize(QtCore.QSize(100, 25))
        self.StopServer.setObjectName("StopServer")
        self.buttons.addWidget(self.StopServer)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.buttons.addItem(spacerItem)
        self.gridLayout.addLayout(self.buttons, 1, 0, 1, 1)
        DashboardWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(DashboardWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1182, 22))
        self.menubar.setNativeMenuBar(False)
        self.menubar.setObjectName("menubar")
        self.Manage = QtWidgets.QMenu(self.menubar)
        self.Manage.setObjectName("Manage")
        DashboardWindow.setMenuBar(self.menubar)
        self.toolBar = QtWidgets.QToolBar(DashboardWindow)
        self.toolBar.setObjectName("toolBar")
        DashboardWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.AddMachine = QtWidgets.QAction(DashboardWindow)
        self.AddMachine.setObjectName("AddMachine")
        self.AddLabel = QtWidgets.QAction(DashboardWindow)
        self.AddLabel.setObjectName("AddLabel")
        self.Settings = QtWidgets.QAction(DashboardWindow)
        self.Settings.setObjectName("Settings")
        self.Quit = QtWidgets.QAction(DashboardWindow)
        self.Quit.setObjectName("Quit")
        self.Manage.addAction(self.AddMachine)
        self.Manage.addAction(self.AddLabel)
        self.Manage.addAction(self.Settings)
        self.Manage.addAction(self.Quit)
        self.menubar.addAction(self.Manage.menuAction())

        self.retranslateUi(DashboardWindow)
        QtCore.QMetaObject.connectSlotsByName(DashboardWindow)

    def retranslateUi(self, DashboardWindow):
        DashboardWindow.setWindowTitle(QtWidgets.QApplication.translate("DashboardWindow", "Gigabot Dashboard", None, -1))
        self.DashboardTitle.setText(QtWidgets.QApplication.translate("DashboardWindow", "<html><head/><body><p><span style=\" font-size:26pt;\">Gigabot DashBoard</span></p></body></html>", None, -1))
        self.StartServer.setText(QtWidgets.QApplication.translate("DashboardWindow", "Start Server", None, -1))
        self.StopServer.setText(QtWidgets.QApplication.translate("DashboardWindow", "Stop Server", None, -1))
        self.Manage.setTitle(QtWidgets.QApplication.translate("DashboardWindow", "Manage", None, -1))
        self.toolBar.setWindowTitle(QtWidgets.QApplication.translate("DashboardWindow", "toolBar", None, -1))
        self.AddMachine.setText(QtWidgets.QApplication.translate("DashboardWindow", "Add Machine", None, -1))
        self.AddLabel.setText(QtWidgets.QApplication.translate("DashboardWindow", "Add Label", None, -1))
        self.Settings.setText(QtWidgets.QApplication.translate("DashboardWindow", "Settings", None, -1))
        self.Quit.setText(QtWidgets.QApplication.translate("DashboardWindow", "Quit", None, -1))

