# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/module_gigabot.ui',
# licensing of 'qt/module_gigabot.ui' applies.
#
# Created: Wed Jul 31 12:03:36 2019
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_GigabotModule(object):
    def setupUi(self, GigabotModule):
        GigabotModule.setObjectName("GigabotModule")
        GigabotModule.resize(320, 187)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(GigabotModule.sizePolicy().hasHeightForWidth())
        GigabotModule.setSizePolicy(sizePolicy)
        GigabotModule.setMinimumSize(QtCore.QSize(320, 187))
        GigabotModule.setMaximumSize(QtCore.QSize(450, 280))
        self.verticalLayout = QtWidgets.QVBoxLayout(GigabotModule)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.GigabotVersion = ScaledLabelText(GigabotModule)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GigabotVersion.sizePolicy().hasHeightForWidth())
        self.GigabotVersion.setSizePolicy(sizePolicy)
        self.GigabotVersion.setMinimumSize(QtCore.QSize(0, 22))
        self.GigabotVersion.setMaximumSize(QtCore.QSize(200, 50))
        self.GigabotVersion.setObjectName("GigabotVersion")
        self.horizontalLayout_4.addWidget(self.GigabotVersion)
        self.ModelType = ScaledLabelText(GigabotModule)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ModelType.sizePolicy().hasHeightForWidth())
        self.ModelType.setSizePolicy(sizePolicy)
        self.ModelType.setMinimumSize(QtCore.QSize(0, 22))
        self.ModelType.setMaximumSize(QtCore.QSize(100, 50))
        self.ModelType.setObjectName("ModelType")
        self.horizontalLayout_4.addWidget(self.ModelType)
        self.GigabotNum = ScaledLabelText(GigabotModule)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GigabotNum.sizePolicy().hasHeightForWidth())
        self.GigabotNum.setSizePolicy(sizePolicy)
        self.GigabotNum.setMinimumSize(QtCore.QSize(0, 22))
        self.GigabotNum.setMaximumSize(QtCore.QSize(100, 50))
        self.GigabotNum.setObjectName("GigabotNum")
        self.horizontalLayout_4.addWidget(self.GigabotNum)
        self.ViewMachineInfo = QtWidgets.QPushButton(GigabotModule)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ViewMachineInfo.sizePolicy().hasHeightForWidth())
        self.ViewMachineInfo.setSizePolicy(sizePolicy)
        self.ViewMachineInfo.setMinimumSize(QtCore.QSize(0, 22))
        self.ViewMachineInfo.setMaximumSize(QtCore.QSize(40, 50))
        self.ViewMachineInfo.setObjectName("ViewMachineInfo")
        self.horizontalLayout_4.addWidget(self.ViewMachineInfo)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.StatusLabel = ScaledLabelText(GigabotModule)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StatusLabel.sizePolicy().hasHeightForWidth())
        self.StatusLabel.setSizePolicy(sizePolicy)
        self.StatusLabel.setMinimumSize(QtCore.QSize(0, 20))
        self.StatusLabel.setMaximumSize(QtCore.QSize(16777215, 30))
        self.StatusLabel.setObjectName("StatusLabel")
        self.horizontalLayout.addWidget(self.StatusLabel)
        self.StatusText = ScaledLabelText(GigabotModule)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StatusText.sizePolicy().hasHeightForWidth())
        self.StatusText.setSizePolicy(sizePolicy)
        self.StatusText.setMinimumSize(QtCore.QSize(90, 20))
        self.StatusText.setMaximumSize(QtCore.QSize(100, 30))
        self.StatusText.setObjectName("StatusText")
        self.horizontalLayout.addWidget(self.StatusText)
        self.StatusImg = ScaledLabelImg(GigabotModule)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StatusImg.sizePolicy().hasHeightForWidth())
        self.StatusImg.setSizePolicy(sizePolicy)
        self.StatusImg.setMinimumSize(QtCore.QSize(35, 20))
        self.StatusImg.setMaximumSize(QtCore.QSize(25, 30))
        self.StatusImg.setText("")
        self.StatusImg.setPixmap(QtGui.QPixmap("../img/idle.png"))
        self.StatusImg.setScaledContents(False)
        self.StatusImg.setObjectName("StatusImg")
        self.horizontalLayout.addWidget(self.StatusImg)
        self.FileLabel = ScaledLabelText(GigabotModule)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FileLabel.sizePolicy().hasHeightForWidth())
        self.FileLabel.setSizePolicy(sizePolicy)
        self.FileLabel.setMinimumSize(QtCore.QSize(0, 20))
        self.FileLabel.setMaximumSize(QtCore.QSize(16777215, 30))
        self.FileLabel.setObjectName("FileLabel")
        self.horizontalLayout.addWidget(self.FileLabel)
        self.FileText = ScaledLabelText(GigabotModule)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FileText.sizePolicy().hasHeightForWidth())
        self.FileText.setSizePolicy(sizePolicy)
        self.FileText.setMinimumSize(QtCore.QSize(0, 20))
        self.FileText.setMaximumSize(QtCore.QSize(16777215, 30))
        self.FileText.setObjectName("FileText")
        self.horizontalLayout.addWidget(self.FileText)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Nozzle1Img = ScaledLabelImg(GigabotModule)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Nozzle1Img.sizePolicy().hasHeightForWidth())
        self.Nozzle1Img.setSizePolicy(sizePolicy)
        self.Nozzle1Img.setMinimumSize(QtCore.QSize(50, 50))
        self.Nozzle1Img.setMaximumSize(QtCore.QSize(100, 100))
        self.Nozzle1Img.setText("")
        self.Nozzle1Img.setPixmap(QtGui.QPixmap("../img/nozzle1.png"))
        self.Nozzle1Img.setScaledContents(False)
        self.Nozzle1Img.setObjectName("Nozzle1Img")
        self.horizontalLayout_2.addWidget(self.Nozzle1Img)
        self.Nozzle2Img = ScaledLabelImg(GigabotModule)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Nozzle2Img.sizePolicy().hasHeightForWidth())
        self.Nozzle2Img.setSizePolicy(sizePolicy)
        self.Nozzle2Img.setMinimumSize(QtCore.QSize(50, 50))
        self.Nozzle2Img.setMaximumSize(QtCore.QSize(100, 100))
        self.Nozzle2Img.setText("")
        self.Nozzle2Img.setPixmap(QtGui.QPixmap("../img/nozzle2.png"))
        self.Nozzle2Img.setScaledContents(False)
        self.Nozzle2Img.setObjectName("Nozzle2Img")
        self.horizontalLayout_2.addWidget(self.Nozzle2Img)
        self.BedImg = ScaledLabelImg(GigabotModule)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BedImg.sizePolicy().hasHeightForWidth())
        self.BedImg.setSizePolicy(sizePolicy)
        self.BedImg.setMinimumSize(QtCore.QSize(50, 50))
        self.BedImg.setMaximumSize(QtCore.QSize(100, 100))
        self.BedImg.setText("")
        self.BedImg.setPixmap(QtGui.QPixmap("../img/bed_unheated.png"))
        self.BedImg.setScaledContents(False)
        self.BedImg.setObjectName("BedImg")
        self.horizontalLayout_2.addWidget(self.BedImg)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Nozzle1Text = ScaledLabelText(GigabotModule)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Nozzle1Text.sizePolicy().hasHeightForWidth())
        self.Nozzle1Text.setSizePolicy(sizePolicy)
        self.Nozzle1Text.setMinimumSize(QtCore.QSize(0, 22))
        self.Nozzle1Text.setMaximumSize(QtCore.QSize(16777215, 75))
        self.Nozzle1Text.setObjectName("Nozzle1Text")
        self.horizontalLayout_3.addWidget(self.Nozzle1Text)
        self.Nozzle2Text = ScaledLabelText(GigabotModule)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Nozzle2Text.sizePolicy().hasHeightForWidth())
        self.Nozzle2Text.setSizePolicy(sizePolicy)
        self.Nozzle2Text.setMinimumSize(QtCore.QSize(0, 22))
        self.Nozzle2Text.setMaximumSize(QtCore.QSize(16777215, 75))
        self.Nozzle2Text.setObjectName("Nozzle2Text")
        self.horizontalLayout_3.addWidget(self.Nozzle2Text)
        self.BedText = ScaledLabelText(GigabotModule)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BedText.sizePolicy().hasHeightForWidth())
        self.BedText.setSizePolicy(sizePolicy)
        self.BedText.setMinimumSize(QtCore.QSize(0, 22))
        self.BedText.setMaximumSize(QtCore.QSize(16777215, 75))
        self.BedText.setObjectName("BedText")
        self.horizontalLayout_3.addWidget(self.BedText)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(GigabotModule)
        QtCore.QMetaObject.connectSlotsByName(GigabotModule)

    def retranslateUi(self, GigabotModule):
        GigabotModule.setWindowTitle(QtWidgets.QApplication.translate("GigabotModule", "Form", None, -1))
        self.GigabotVersion.setText(QtWidgets.QApplication.translate("GigabotModule", "<html><head/><body><p><span style=\" font-size:22pt;\">-----</span></p></body></html>", None, -1))
        self.ModelType.setText(QtWidgets.QApplication.translate("GigabotModule", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt;\">-----</span></p></body></html>", None, -1))
        self.GigabotNum.setText(QtWidgets.QApplication.translate("GigabotModule", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt;\">-----</span></p></body></html>", None, -1))
        self.ViewMachineInfo.setText(QtWidgets.QApplication.translate("GigabotModule", "...", None, -1))
        self.StatusLabel.setText(QtWidgets.QApplication.translate("GigabotModule", "<html><head/><body><p><span style=\" font-size:16pt;\">-----</span></p></body></html>", None, -1))
        self.StatusText.setText(QtWidgets.QApplication.translate("GigabotModule", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">-----</span></p></body></html>", None, -1))
        self.FileLabel.setText(QtWidgets.QApplication.translate("GigabotModule", "<html><head/><body><p><span style=\" font-size:16pt;\">-----</span></p></body></html>", None, -1))
        self.FileText.setText(QtWidgets.QApplication.translate("GigabotModule", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">-----</span></p></body></html>", None, -1))
        self.Nozzle1Text.setText(QtWidgets.QApplication.translate("GigabotModule", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt;\">-----</span></p></body></html>", None, -1))
        self.Nozzle2Text.setText(QtWidgets.QApplication.translate("GigabotModule", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt;\">-----</span></p></body></html>", None, -1))
        self.BedText.setText(QtWidgets.QApplication.translate("GigabotModule", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt;\">-----</span></p></body></html>", None, -1))

from scaledlabeltext import ScaledLabelText
from scaledlabelimg import ScaledLabelImg
