# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/module_gigabot.ui',
# licensing of 'qt/module_gigabot.ui' applies.
#
# Created: Tue Jul 30 17:46:48 2019
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_GigabotModule(object):
    def setupUi(self, GigabotModule):
        GigabotModule.setObjectName("GigabotModule")
        GigabotModule.resize(320, 187)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(GigabotModule.sizePolicy().hasHeightForWidth())
        GigabotModule.setSizePolicy(sizePolicy)
        GigabotModule.setMinimumSize(QtCore.QSize(320, 187))
        GigabotModule.setMaximumSize(QtCore.QSize(450, 280))
        self.verticalLayout = QtWidgets.QVBoxLayout(GigabotModule)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.GigabotVersion = QtWidgets.QTextBrowser(GigabotModule)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GigabotVersion.sizePolicy().hasHeightForWidth())
        self.GigabotVersion.setSizePolicy(sizePolicy)
        self.GigabotVersion.setMinimumSize(QtCore.QSize(50, 35))
        self.GigabotVersion.setMaximumSize(QtCore.QSize(200, 50))
        self.GigabotVersion.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.GigabotVersion.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.GigabotVersion.setDocumentTitle("")
        self.GigabotVersion.setObjectName("GigabotVersion")
        self.horizontalLayout_4.addWidget(self.GigabotVersion)
        self.ModelType = QtWidgets.QTextBrowser(GigabotModule)
        self.ModelType.setMinimumSize(QtCore.QSize(50, 35))
        self.ModelType.setMaximumSize(QtCore.QSize(100, 50))
        self.ModelType.setObjectName("ModelType")
        self.horizontalLayout_4.addWidget(self.ModelType)
        self.GigabotNum = QtWidgets.QTextBrowser(GigabotModule)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GigabotNum.sizePolicy().hasHeightForWidth())
        self.GigabotNum.setSizePolicy(sizePolicy)
        self.GigabotNum.setMinimumSize(QtCore.QSize(50, 35))
        self.GigabotNum.setMaximumSize(QtCore.QSize(100, 50))
        self.GigabotNum.setObjectName("GigabotNum")
        self.horizontalLayout_4.addWidget(self.GigabotNum)
        self.ViewMachineInfo = QtWidgets.QPushButton(GigabotModule)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ViewMachineInfo.sizePolicy().hasHeightForWidth())
        self.ViewMachineInfo.setSizePolicy(sizePolicy)
        self.ViewMachineInfo.setMinimumSize(QtCore.QSize(15, 30))
        self.ViewMachineInfo.setMaximumSize(QtCore.QSize(40, 50))
        self.ViewMachineInfo.setObjectName("ViewMachineInfo")
        self.horizontalLayout_4.addWidget(self.ViewMachineInfo)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.StatusLabel = QtWidgets.QLabel(GigabotModule)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StatusLabel.sizePolicy().hasHeightForWidth())
        self.StatusLabel.setSizePolicy(sizePolicy)
        self.StatusLabel.setMinimumSize(QtCore.QSize(0, 25))
        self.StatusLabel.setMaximumSize(QtCore.QSize(16777215, 35))
        self.StatusLabel.setObjectName("StatusLabel")
        self.horizontalLayout.addWidget(self.StatusLabel)
        self.StatusText = QtWidgets.QTextBrowser(GigabotModule)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StatusText.sizePolicy().hasHeightForWidth())
        self.StatusText.setSizePolicy(sizePolicy)
        self.StatusText.setMinimumSize(QtCore.QSize(0, 25))
        self.StatusText.setMaximumSize(QtCore.QSize(16777215, 35))
        self.StatusText.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.StatusText.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.StatusText.setObjectName("StatusText")
        self.horizontalLayout.addWidget(self.StatusText)
        self.StatusImg = ScaledLabel(GigabotModule)
        self.StatusImg.setMinimumSize(QtCore.QSize(35, 35))
        self.StatusImg.setMaximumSize(QtCore.QSize(40, 40))
        self.StatusImg.setText("")
        self.StatusImg.setPixmap(QtGui.QPixmap("../img/idle.png"))
        self.StatusImg.setScaledContents(False)
        self.StatusImg.setObjectName("StatusImg")
        self.horizontalLayout.addWidget(self.StatusImg)
        self.StatusLabel_2 = QtWidgets.QLabel(GigabotModule)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StatusLabel_2.sizePolicy().hasHeightForWidth())
        self.StatusLabel_2.setSizePolicy(sizePolicy)
        self.StatusLabel_2.setMinimumSize(QtCore.QSize(0, 25))
        self.StatusLabel_2.setMaximumSize(QtCore.QSize(16777215, 35))
        self.StatusLabel_2.setObjectName("StatusLabel_2")
        self.horizontalLayout.addWidget(self.StatusLabel_2)
        self.CurrentFile = QtWidgets.QTextBrowser(GigabotModule)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CurrentFile.sizePolicy().hasHeightForWidth())
        self.CurrentFile.setSizePolicy(sizePolicy)
        self.CurrentFile.setMinimumSize(QtCore.QSize(0, 25))
        self.CurrentFile.setMaximumSize(QtCore.QSize(16777215, 35))
        self.CurrentFile.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.CurrentFile.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.CurrentFile.setObjectName("CurrentFile")
        self.horizontalLayout.addWidget(self.CurrentFile)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Nozzle1Img = ScaledLabel(GigabotModule)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Nozzle1Img.sizePolicy().hasHeightForWidth())
        self.Nozzle1Img.setSizePolicy(sizePolicy)
        self.Nozzle1Img.setMinimumSize(QtCore.QSize(50, 50))
        self.Nozzle1Img.setMaximumSize(QtCore.QSize(120, 120))
        self.Nozzle1Img.setText("")
        self.Nozzle1Img.setPixmap(QtGui.QPixmap("../img/nozzle1.png"))
        self.Nozzle1Img.setScaledContents(False)
        self.Nozzle1Img.setObjectName("Nozzle1Img")
        self.horizontalLayout_2.addWidget(self.Nozzle1Img)
        self.Nozzle2Img = ScaledLabel(GigabotModule)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Nozzle2Img.sizePolicy().hasHeightForWidth())
        self.Nozzle2Img.setSizePolicy(sizePolicy)
        self.Nozzle2Img.setMinimumSize(QtCore.QSize(50, 50))
        self.Nozzle2Img.setMaximumSize(QtCore.QSize(120, 120))
        self.Nozzle2Img.setText("")
        self.Nozzle2Img.setPixmap(QtGui.QPixmap("../img/nozzle2.png"))
        self.Nozzle2Img.setScaledContents(False)
        self.Nozzle2Img.setObjectName("Nozzle2Img")
        self.horizontalLayout_2.addWidget(self.Nozzle2Img)
        self.BedImg = ScaledLabel(GigabotModule)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BedImg.sizePolicy().hasHeightForWidth())
        self.BedImg.setSizePolicy(sizePolicy)
        self.BedImg.setMinimumSize(QtCore.QSize(50, 50))
        self.BedImg.setMaximumSize(QtCore.QSize(120, 120))
        self.BedImg.setText("")
        self.BedImg.setPixmap(QtGui.QPixmap("../img/bed_unheated.png"))
        self.BedImg.setScaledContents(False)
        self.BedImg.setObjectName("BedImg")
        self.horizontalLayout_2.addWidget(self.BedImg)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Nozzle1Text = QtWidgets.QTextBrowser(GigabotModule)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Nozzle1Text.sizePolicy().hasHeightForWidth())
        self.Nozzle1Text.setSizePolicy(sizePolicy)
        self.Nozzle1Text.setMinimumSize(QtCore.QSize(0, 25))
        self.Nozzle1Text.setMaximumSize(QtCore.QSize(16777215, 40))
        self.Nozzle1Text.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Nozzle1Text.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Nozzle1Text.setObjectName("Nozzle1Text")
        self.horizontalLayout_3.addWidget(self.Nozzle1Text)
        self.Nozzle2Text = QtWidgets.QTextBrowser(GigabotModule)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Nozzle2Text.sizePolicy().hasHeightForWidth())
        self.Nozzle2Text.setSizePolicy(sizePolicy)
        self.Nozzle2Text.setMinimumSize(QtCore.QSize(0, 25))
        self.Nozzle2Text.setMaximumSize(QtCore.QSize(16777215, 40))
        self.Nozzle2Text.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Nozzle2Text.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Nozzle2Text.setObjectName("Nozzle2Text")
        self.horizontalLayout_3.addWidget(self.Nozzle2Text)
        self.BedText = QtWidgets.QTextBrowser(GigabotModule)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BedText.sizePolicy().hasHeightForWidth())
        self.BedText.setSizePolicy(sizePolicy)
        self.BedText.setMinimumSize(QtCore.QSize(0, 25))
        self.BedText.setMaximumSize(QtCore.QSize(16777215, 40))
        self.BedText.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.BedText.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.BedText.setObjectName("BedText")
        self.horizontalLayout_3.addWidget(self.BedText)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(GigabotModule)
        QtCore.QMetaObject.connectSlotsByName(GigabotModule)

    def retranslateUi(self, GigabotModule):
        GigabotModule.setWindowTitle(QtWidgets.QApplication.translate("GigabotModule", "Form", None, -1))
        self.GigabotVersion.setHtml(QtWidgets.QApplication.translate("GigabotModule", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">Gigabot 3+ </span></p></body></html>", None, -1))
        self.GigabotNum.setHtml(QtWidgets.QApplication.translate("GigabotModule", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">512</span></p></body></html>", None, -1))
        self.ViewMachineInfo.setText(QtWidgets.QApplication.translate("GigabotModule", "...", None, -1))
        self.StatusLabel.setText(QtWidgets.QApplication.translate("GigabotModule", "<html><head/><body><p>Status:</p></body></html>", None, -1))
        self.StatusText.setHtml(QtWidgets.QApplication.translate("GigabotModule", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">On/Idle</p></body></html>", None, -1))
        self.StatusLabel_2.setText(QtWidgets.QApplication.translate("GigabotModule", "<html><head/><body><p>File:</p></body></html>", None, -1))
        self.CurrentFile.setHtml(QtWidgets.QApplication.translate("GigabotModule", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None, -1))

from scaledlabel import ScaledLabel
