# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/activeprintwidget.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ActivePrintWidget(object):
    def setupUi(self, ActivePrintWidget):
        ActivePrintWidget.setObjectName("ActivePrintWidget")
        ActivePrintWidget.resize(800, 263)
        ActivePrintWidget.setMaximumSize(QtCore.QSize(800, 480))
        self.layoutWidget = QtWidgets.QWidget(ActivePrintWidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 778, 181))
        self.layoutWidget.setObjectName("layoutWidget")
        self.ActivePrint = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.ActivePrint.setSpacing(0)
        self.ActivePrint.setObjectName("ActivePrint")
        self.Back = QtWidgets.QPushButton(self.layoutWidget)
        self.Back.setMaximumSize(QtCore.QSize(100, 100))
        self.Back.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Back.setIcon(icon)
        self.Back.setIconSize(QtCore.QSize(100, 100))
        self.Back.setObjectName("Back")
        self.ActivePrint.addWidget(self.Back)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.FileLabel = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FileLabel.sizePolicy().hasHeightForWidth())
        self.FileLabel.setSizePolicy(sizePolicy)
        self.FileLabel.setMinimumSize(QtCore.QSize(120, 0))
        self.FileLabel.setObjectName("FileLabel")
        self.horizontalLayout.addWidget(self.FileLabel)
        self.FileName = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FileName.sizePolicy().hasHeightForWidth())
        self.FileName.setSizePolicy(sizePolicy)
        self.FileName.setMinimumSize(QtCore.QSize(0, 30))
        self.FileName.setObjectName("FileName")
        self.horizontalLayout.addWidget(self.FileName)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.FileProgress = QtWidgets.QProgressBar(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FileProgress.sizePolicy().hasHeightForWidth())
        self.FileProgress.setSizePolicy(sizePolicy)
        self.FileProgress.setMinimumSize(QtCore.QSize(280, 0))
        self.FileProgress.setProperty("value", 0)
        self.FileProgress.setObjectName("FileProgress")
        self.verticalLayout_5.addWidget(self.FileProgress)
        self.verticalLayout.addLayout(self.verticalLayout_5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.StopPrint = QtWidgets.QPushButton(self.layoutWidget)
        self.StopPrint.setMaximumSize(QtCore.QSize(65, 65))
        self.StopPrint.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("img/stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.StopPrint.setIcon(icon1)
        self.StopPrint.setIconSize(QtCore.QSize(55, 55))
        self.StopPrint.setObjectName("StopPrint")
        self.horizontalLayout_2.addWidget(self.StopPrint)
        self.PausePrint = QtWidgets.QPushButton(self.layoutWidget)
        self.PausePrint.setMaximumSize(QtCore.QSize(65, 65))
        self.PausePrint.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("img/pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PausePrint.setIcon(icon2)
        self.PausePrint.setIconSize(QtCore.QSize(55, 55))
        self.PausePrint.setObjectName("PausePrint")
        self.horizontalLayout_2.addWidget(self.PausePrint)
        self.ResumePrint = QtWidgets.QPushButton(self.layoutWidget)
        self.ResumePrint.setMaximumSize(QtCore.QSize(65, 65))
        self.ResumePrint.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("img/resume.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ResumePrint.setIcon(icon3)
        self.ResumePrint.setIconSize(QtCore.QSize(55, 55))
        self.ResumePrint.setObjectName("ResumePrint")
        self.horizontalLayout_2.addWidget(self.ResumePrint)
        self.Fan = QtWidgets.QPushButton(self.layoutWidget)
        self.Fan.setMaximumSize(QtCore.QSize(65, 65))
        self.Fan.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("img/fanoff.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Fan.setIcon(icon4)
        self.Fan.setIconSize(QtCore.QSize(55, 55))
        self.Fan.setObjectName("Fan")
        self.horizontalLayout_2.addWidget(self.Fan)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.ActivePrint.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.FeedrateLabel = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FeedrateLabel.sizePolicy().hasHeightForWidth())
        self.FeedrateLabel.setSizePolicy(sizePolicy)
        self.FeedrateLabel.setObjectName("FeedrateLabel")
        self.horizontalLayout_5.addWidget(self.FeedrateLabel)
        self.FeedrateVal = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FeedrateVal.sizePolicy().hasHeightForWidth())
        self.FeedrateVal.setSizePolicy(sizePolicy)
        self.FeedrateVal.setObjectName("FeedrateVal")
        self.horizontalLayout_5.addWidget(self.FeedrateVal)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.FeedrateSlider = QtWidgets.QSlider(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FeedrateSlider.sizePolicy().hasHeightForWidth())
        self.FeedrateSlider.setSizePolicy(sizePolicy)
        self.FeedrateSlider.setMinimumSize(QtCore.QSize(0, 40))
        self.FeedrateSlider.setMaximum(100)
        self.FeedrateSlider.setSliderPosition(50)
        self.FeedrateSlider.setOrientation(QtCore.Qt.Horizontal)
        self.FeedrateSlider.setObjectName("FeedrateSlider")
        self.verticalLayout_3.addWidget(self.FeedrateSlider)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 6, -1, -1)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.FlowrateLabel = QtWidgets.QPushButton(self.layoutWidget)
        self.FlowrateLabel.setMaximumSize(QtCore.QSize(16777215, 25))
        self.FlowrateLabel.setObjectName("FlowrateLabel")
        self.horizontalLayout_4.addWidget(self.FlowrateLabel)
        self.BabysteppingLabel = QtWidgets.QPushButton(self.layoutWidget)
        self.BabysteppingLabel.setMaximumSize(QtCore.QSize(16777215, 25))
        self.BabysteppingLabel.setObjectName("BabysteppingLabel")
        self.horizontalLayout_4.addWidget(self.BabysteppingLabel)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.FlowrateNeg = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FlowrateNeg.sizePolicy().hasHeightForWidth())
        self.FlowrateNeg.setSizePolicy(sizePolicy)
        self.FlowrateNeg.setMaximumSize(QtCore.QSize(150, 150))
        self.FlowrateNeg.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("img/downarrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.FlowrateNeg.setIcon(icon5)
        self.FlowrateNeg.setIconSize(QtCore.QSize(50, 50))
        self.FlowrateNeg.setObjectName("FlowrateNeg")
        self.horizontalLayout_3.addWidget(self.FlowrateNeg)
        self.FlowrateVal = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FlowrateVal.sizePolicy().hasHeightForWidth())
        self.FlowrateVal.setSizePolicy(sizePolicy)
        self.FlowrateVal.setObjectName("FlowrateVal")
        self.horizontalLayout_3.addWidget(self.FlowrateVal)
        self.FlowratePos = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FlowratePos.sizePolicy().hasHeightForWidth())
        self.FlowratePos.setSizePolicy(sizePolicy)
        self.FlowratePos.setMaximumSize(QtCore.QSize(150, 150))
        self.FlowratePos.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("img/uparrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.FlowratePos.setIcon(icon6)
        self.FlowratePos.setIconSize(QtCore.QSize(50, 50))
        self.FlowratePos.setObjectName("FlowratePos")
        self.horizontalLayout_3.addWidget(self.FlowratePos)
        self.BabystepNeg = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BabystepNeg.sizePolicy().hasHeightForWidth())
        self.BabystepNeg.setSizePolicy(sizePolicy)
        self.BabystepNeg.setMaximumSize(QtCore.QSize(150, 150))
        self.BabystepNeg.setText("")
        self.BabystepNeg.setIcon(icon5)
        self.BabystepNeg.setIconSize(QtCore.QSize(50, 50))
        self.BabystepNeg.setObjectName("BabystepNeg")
        self.horizontalLayout_3.addWidget(self.BabystepNeg)
        self.BabysteppingVal = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BabysteppingVal.sizePolicy().hasHeightForWidth())
        self.BabysteppingVal.setSizePolicy(sizePolicy)
        self.BabysteppingVal.setObjectName("BabysteppingVal")
        self.horizontalLayout_3.addWidget(self.BabysteppingVal)
        self.BabysteppingPos = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BabysteppingPos.sizePolicy().hasHeightForWidth())
        self.BabysteppingPos.setSizePolicy(sizePolicy)
        self.BabysteppingPos.setMaximumSize(QtCore.QSize(150, 150))
        self.BabysteppingPos.setText("")
        self.BabysteppingPos.setIcon(icon6)
        self.BabysteppingPos.setIconSize(QtCore.QSize(50, 50))
        self.BabysteppingPos.setObjectName("BabysteppingPos")
        self.horizontalLayout_3.addWidget(self.BabysteppingPos)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.ActivePrint.addLayout(self.verticalLayout_3)

        self.retranslateUi(ActivePrintWidget)
        QtCore.QMetaObject.connectSlotsByName(ActivePrintWidget)

    def retranslateUi(self, ActivePrintWidget):
        _translate = QtCore.QCoreApplication.translate
        ActivePrintWidget.setWindowTitle(_translate("ActivePrintWidget", "TemperatureWindow"))
        self.FileLabel.setText(_translate("ActivePrintWidget", "Current File:"))
        self.FileName.setText(_translate("ActivePrintWidget", "<html><head/><body><p><span style=\" font-size:14pt;\">-----</span></p></body></html>"))
        self.FeedrateLabel.setText(_translate("ActivePrintWidget", "Feedrate:"))
        self.FeedrateVal.setText(_translate("ActivePrintWidget", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">-----</span></p></body></html>"))
        self.FlowrateLabel.setText(_translate("ActivePrintWidget", "Flowrate: All"))
        self.BabysteppingLabel.setText(_translate("ActivePrintWidget", "Babystepping"))
        self.FlowrateVal.setText(_translate("ActivePrintWidget", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">-----</span></p></body></html>"))
        self.BabysteppingVal.setText(_translate("ActivePrintWidget", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">-----</span></p></body></html>"))

