# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'controlpage_qt.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ControlPage(object):
    def setupUi(self, ControlPage):
        ControlPage.setObjectName("ControlPage")
        ControlPage.resize(800, 448)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ControlPage.sizePolicy().hasHeightForWidth())
        ControlPage.setSizePolicy(sizePolicy)
        ControlPage.setMaximumSize(QtCore.QSize(800, 448))
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(ControlPage)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(10, 10, 10, -1)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.HomeAll = QtWidgets.QPushButton(ControlPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.HomeAll.sizePolicy().hasHeightForWidth())
        self.HomeAll.setSizePolicy(sizePolicy)
        self.HomeAll.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.HomeAll.setFocusPolicy(QtCore.Qt.NoFocus)
        self.HomeAll.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/img/Home_XYZ.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.HomeAll.setIcon(icon)
        self.HomeAll.setIconSize(QtCore.QSize(45, 45))
        self.HomeAll.setObjectName("HomeAll")
        self.verticalLayout_4.addWidget(self.HomeAll)
        self.HomeXY = QtWidgets.QPushButton(ControlPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.HomeXY.sizePolicy().hasHeightForWidth())
        self.HomeXY.setSizePolicy(sizePolicy)
        self.HomeXY.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.HomeXY.setFocusPolicy(QtCore.Qt.NoFocus)
        self.HomeXY.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/img/img/Home_XY.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.HomeXY.setIcon(icon1)
        self.HomeXY.setIconSize(QtCore.QSize(45, 45))
        self.HomeXY.setObjectName("HomeXY")
        self.verticalLayout_4.addWidget(self.HomeXY)
        self.HomeZ = QtWidgets.QPushButton(ControlPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.HomeZ.sizePolicy().hasHeightForWidth())
        self.HomeZ.setSizePolicy(sizePolicy)
        self.HomeZ.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.HomeZ.setFocusPolicy(QtCore.Qt.NoFocus)
        self.HomeZ.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/img/img/Home_Z.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.HomeZ.setIcon(icon2)
        self.HomeZ.setIconSize(QtCore.QSize(45, 45))
        self.HomeZ.setObjectName("HomeZ")
        self.verticalLayout_4.addWidget(self.HomeZ)
        self.DisableMotors = QtWidgets.QPushButton(ControlPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DisableMotors.sizePolicy().hasHeightForWidth())
        self.DisableMotors.setSizePolicy(sizePolicy)
        self.DisableMotors.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.DisableMotors.setFocusPolicy(QtCore.Qt.NoFocus)
        self.DisableMotors.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/img/img/Stepper_Motor_Off.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.DisableMotors.setIcon(icon3)
        self.DisableMotors.setIconSize(QtCore.QSize(45, 45))
        self.DisableMotors.setObjectName("DisableMotors")
        self.verticalLayout_4.addWidget(self.DisableMotors)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSpacing(15)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.XNeg = QtWidgets.QPushButton(ControlPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.XNeg.sizePolicy().hasHeightForWidth())
        self.XNeg.setSizePolicy(sizePolicy)
        self.XNeg.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.XNeg.setFocusPolicy(QtCore.Qt.NoFocus)
        self.XNeg.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/img/img/Left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.XNeg.setIcon(icon4)
        self.XNeg.setIconSize(QtCore.QSize(75, 75))
        self.XNeg.setObjectName("XNeg")
        self.gridLayout_3.addWidget(self.XNeg, 1, 0, 1, 1)
        self.YPos = QtWidgets.QPushButton(ControlPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.YPos.sizePolicy().hasHeightForWidth())
        self.YPos.setSizePolicy(sizePolicy)
        self.YPos.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.YPos.setFocusPolicy(QtCore.Qt.NoFocus)
        self.YPos.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/img/img/UP.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.YPos.setIcon(icon5)
        self.YPos.setIconSize(QtCore.QSize(75, 75))
        self.YPos.setObjectName("YPos")
        self.gridLayout_3.addWidget(self.YPos, 0, 1, 1, 1)
        self.XPos = QtWidgets.QPushButton(ControlPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.XPos.sizePolicy().hasHeightForWidth())
        self.XPos.setSizePolicy(sizePolicy)
        self.XPos.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.XPos.setFocusPolicy(QtCore.Qt.NoFocus)
        self.XPos.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/img/img/Right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.XPos.setIcon(icon6)
        self.XPos.setIconSize(QtCore.QSize(75, 75))
        self.XPos.setObjectName("XPos")
        self.gridLayout_3.addWidget(self.XPos, 1, 2, 1, 1)
        self.XYIcon = QtWidgets.QPushButton(ControlPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.XYIcon.sizePolicy().hasHeightForWidth())
        self.XYIcon.setSizePolicy(sizePolicy)
        self.XYIcon.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.XYIcon.setFocusPolicy(QtCore.Qt.NoFocus)
        self.XYIcon.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/img/img/Bed_Front_XY.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.XYIcon.setIcon(icon7)
        self.XYIcon.setIconSize(QtCore.QSize(75, 75))
        self.XYIcon.setObjectName("XYIcon")
        self.gridLayout_3.addWidget(self.XYIcon, 1, 1, 1, 1)
        self.YNeg = QtWidgets.QPushButton(ControlPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.YNeg.sizePolicy().hasHeightForWidth())
        self.YNeg.setSizePolicy(sizePolicy)
        self.YNeg.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.YNeg.setFocusPolicy(QtCore.Qt.NoFocus)
        self.YNeg.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/img/img/Down.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.YNeg.setIcon(icon8)
        self.YNeg.setIconSize(QtCore.QSize(75, 75))
        self.YNeg.setObjectName("YNeg")
        self.gridLayout_3.addWidget(self.YNeg, 2, 1, 1, 1)
        self.horizontalLayout_5.addLayout(self.gridLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ZNeg = QtWidgets.QPushButton(ControlPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ZNeg.sizePolicy().hasHeightForWidth())
        self.ZNeg.setSizePolicy(sizePolicy)
        self.ZNeg.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.ZNeg.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ZNeg.setText("")
        self.ZNeg.setIcon(icon5)
        self.ZNeg.setIconSize(QtCore.QSize(75, 75))
        self.ZNeg.setObjectName("ZNeg")
        self.verticalLayout.addWidget(self.ZNeg)
        self.ZIcon = QtWidgets.QPushButton(ControlPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ZIcon.sizePolicy().hasHeightForWidth())
        self.ZIcon.setSizePolicy(sizePolicy)
        self.ZIcon.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.ZIcon.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ZIcon.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/img/img/Bed_Z.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ZIcon.setIcon(icon9)
        self.ZIcon.setIconSize(QtCore.QSize(75, 70))
        self.ZIcon.setObjectName("ZIcon")
        self.verticalLayout.addWidget(self.ZIcon)
        self.ZPos = QtWidgets.QPushButton(ControlPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ZPos.sizePolicy().hasHeightForWidth())
        self.ZPos.setSizePolicy(sizePolicy)
        self.ZPos.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.ZPos.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ZPos.setText("")
        self.ZPos.setIcon(icon8)
        self.ZPos.setIconSize(QtCore.QSize(75, 75))
        self.ZPos.setObjectName("ZPos")
        self.verticalLayout.addWidget(self.ZPos)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(15)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.E0Neg = QtWidgets.QPushButton(ControlPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.E0Neg.sizePolicy().hasHeightForWidth())
        self.E0Neg.setSizePolicy(sizePolicy)
        self.E0Neg.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.E0Neg.setFocusPolicy(QtCore.Qt.NoFocus)
        self.E0Neg.setText("")
        self.E0Neg.setIcon(icon5)
        self.E0Neg.setIconSize(QtCore.QSize(75, 75))
        self.E0Neg.setObjectName("E0Neg")
        self.verticalLayout_2.addWidget(self.E0Neg)
        self.E0Icon = QtWidgets.QPushButton(ControlPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.E0Icon.sizePolicy().hasHeightForWidth())
        self.E0Icon.setSizePolicy(sizePolicy)
        self.E0Icon.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.E0Icon.setFocusPolicy(QtCore.Qt.NoFocus)
        self.E0Icon.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/img/img/Extruder_1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.E0Icon.setIcon(icon10)
        self.E0Icon.setIconSize(QtCore.QSize(75, 70))
        self.E0Icon.setObjectName("E0Icon")
        self.verticalLayout_2.addWidget(self.E0Icon)
        self.E0Pos = QtWidgets.QPushButton(ControlPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.E0Pos.sizePolicy().hasHeightForWidth())
        self.E0Pos.setSizePolicy(sizePolicy)
        self.E0Pos.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.E0Pos.setFocusPolicy(QtCore.Qt.NoFocus)
        self.E0Pos.setText("")
        self.E0Pos.setIcon(icon8)
        self.E0Pos.setIconSize(QtCore.QSize(75, 75))
        self.E0Pos.setObjectName("E0Pos")
        self.verticalLayout_2.addWidget(self.E0Pos)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(15)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.E1Neg = QtWidgets.QPushButton(ControlPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.E1Neg.sizePolicy().hasHeightForWidth())
        self.E1Neg.setSizePolicy(sizePolicy)
        self.E1Neg.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.E1Neg.setFocusPolicy(QtCore.Qt.NoFocus)
        self.E1Neg.setText("")
        self.E1Neg.setIcon(icon5)
        self.E1Neg.setIconSize(QtCore.QSize(75, 75))
        self.E1Neg.setObjectName("E1Neg")
        self.verticalLayout_3.addWidget(self.E1Neg)
        self.E1Icon = QtWidgets.QPushButton(ControlPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.E1Icon.sizePolicy().hasHeightForWidth())
        self.E1Icon.setSizePolicy(sizePolicy)
        self.E1Icon.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.E1Icon.setFocusPolicy(QtCore.Qt.NoFocus)
        self.E1Icon.setText("")
        self.E1Icon.setIcon(icon10)
        self.E1Icon.setIconSize(QtCore.QSize(75, 70))
        self.E1Icon.setObjectName("E1Icon")
        self.verticalLayout_3.addWidget(self.E1Icon)
        self.E1Pos = QtWidgets.QPushButton(ControlPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.E1Pos.sizePolicy().hasHeightForWidth())
        self.E1Pos.setSizePolicy(sizePolicy)
        self.E1Pos.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.E1Pos.setFocusPolicy(QtCore.Qt.NoFocus)
        self.E1Pos.setText("")
        self.E1Pos.setIcon(icon8)
        self.E1Pos.setIconSize(QtCore.QSize(75, 75))
        self.E1Pos.setObjectName("E1Pos")
        self.verticalLayout_3.addWidget(self.E1Pos)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(12)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.movey = QtWidgets.QPushButton(ControlPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.movey.sizePolicy().hasHeightForWidth())
        self.movey.setSizePolicy(sizePolicy)
        self.movey.setMinimumSize(QtCore.QSize(65, 0))
        self.movey.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.movey.setFocusPolicy(QtCore.Qt.NoFocus)
        self.movey.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/img/img/Bed_Y.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.movey.setIcon(icon11)
        self.movey.setIconSize(QtCore.QSize(50, 40))
        self.movey.setObjectName("movey")
        self.horizontalLayout_2.addWidget(self.movey)
        self.ym01 = QtWidgets.QPushButton(ControlPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ym01.sizePolicy().hasHeightForWidth())
        self.ym01.setSizePolicy(sizePolicy)
        self.ym01.setMinimumSize(QtCore.QSize(60, 30))
        self.ym01.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.ym01.setFont(font)
        self.ym01.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ym01.setIconSize(QtCore.QSize(0, 0))
        self.ym01.setObjectName("ym01")
        self.horizontalLayout_2.addWidget(self.ym01)
        self.ym1 = QtWidgets.QPushButton(ControlPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ym1.sizePolicy().hasHeightForWidth())
        self.ym1.setSizePolicy(sizePolicy)
        self.ym1.setMinimumSize(QtCore.QSize(60, 30))
        self.ym1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.ym1.setFont(font)
        self.ym1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ym1.setIconSize(QtCore.QSize(0, 0))
        self.ym1.setObjectName("ym1")
        self.horizontalLayout_2.addWidget(self.ym1)
        self.ym10 = QtWidgets.QPushButton(ControlPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ym10.sizePolicy().hasHeightForWidth())
        self.ym10.setSizePolicy(sizePolicy)
        self.ym10.setMinimumSize(QtCore.QSize(60, 30))
        self.ym10.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.ym10.setFont(font)
        self.ym10.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ym10.setIconSize(QtCore.QSize(0, 0))
        self.ym10.setObjectName("ym10")
        self.horizontalLayout_2.addWidget(self.ym10)
        self.ym100 = QtWidgets.QPushButton(ControlPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ym100.sizePolicy().hasHeightForWidth())
        self.ym100.setSizePolicy(sizePolicy)
        self.ym100.setMinimumSize(QtCore.QSize(60, 30))
        self.ym100.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.ym100.setFont(font)
        self.ym100.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ym100.setIconSize(QtCore.QSize(0, 0))
        self.ym100.setObjectName("ym100")
        self.horizontalLayout_2.addWidget(self.ym100)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(12)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.movee = QtWidgets.QPushButton(ControlPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.movee.sizePolicy().hasHeightForWidth())
        self.movee.setSizePolicy(sizePolicy)
        self.movee.setMinimumSize(QtCore.QSize(65, 0))
        self.movee.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.movee.setFocusPolicy(QtCore.Qt.NoFocus)
        self.movee.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/img/img/Extruder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.movee.setIcon(icon12)
        self.movee.setIconSize(QtCore.QSize(50, 40))
        self.movee.setObjectName("movee")
        self.horizontalLayout_4.addWidget(self.movee)
        self.em01 = QtWidgets.QPushButton(ControlPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.em01.sizePolicy().hasHeightForWidth())
        self.em01.setSizePolicy(sizePolicy)
        self.em01.setMinimumSize(QtCore.QSize(60, 30))
        self.em01.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.em01.setFont(font)
        self.em01.setFocusPolicy(QtCore.Qt.NoFocus)
        self.em01.setIconSize(QtCore.QSize(0, 0))
        self.em01.setObjectName("em01")
        self.horizontalLayout_4.addWidget(self.em01)
        self.em1 = QtWidgets.QPushButton(ControlPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.em1.sizePolicy().hasHeightForWidth())
        self.em1.setSizePolicy(sizePolicy)
        self.em1.setMinimumSize(QtCore.QSize(60, 30))
        self.em1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.em1.setFont(font)
        self.em1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.em1.setIconSize(QtCore.QSize(0, 0))
        self.em1.setObjectName("em1")
        self.horizontalLayout_4.addWidget(self.em1)
        self.em10 = QtWidgets.QPushButton(ControlPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.em10.sizePolicy().hasHeightForWidth())
        self.em10.setSizePolicy(sizePolicy)
        self.em10.setMinimumSize(QtCore.QSize(60, 30))
        self.em10.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.em10.setFont(font)
        self.em10.setFocusPolicy(QtCore.Qt.NoFocus)
        self.em10.setIconSize(QtCore.QSize(0, 0))
        self.em10.setObjectName("em10")
        self.horizontalLayout_4.addWidget(self.em10)
        self.em100 = QtWidgets.QPushButton(ControlPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.em100.sizePolicy().hasHeightForWidth())
        self.em100.setSizePolicy(sizePolicy)
        self.em100.setMinimumSize(QtCore.QSize(60, 30))
        self.em100.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.em100.setFont(font)
        self.em100.setFocusPolicy(QtCore.Qt.NoFocus)
        self.em100.setIconSize(QtCore.QSize(0, 0))
        self.em100.setObjectName("em100")
        self.horizontalLayout_4.addWidget(self.em100)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 1, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(12)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.movez = QtWidgets.QPushButton(ControlPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.movez.sizePolicy().hasHeightForWidth())
        self.movez.setSizePolicy(sizePolicy)
        self.movez.setMinimumSize(QtCore.QSize(65, 0))
        self.movez.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.movez.setFocusPolicy(QtCore.Qt.NoFocus)
        self.movez.setText("")
        self.movez.setIcon(icon9)
        self.movez.setIconSize(QtCore.QSize(50, 40))
        self.movez.setObjectName("movez")
        self.horizontalLayout_3.addWidget(self.movez)
        self.zm01 = QtWidgets.QPushButton(ControlPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zm01.sizePolicy().hasHeightForWidth())
        self.zm01.setSizePolicy(sizePolicy)
        self.zm01.setMinimumSize(QtCore.QSize(60, 30))
        self.zm01.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.zm01.setFont(font)
        self.zm01.setFocusPolicy(QtCore.Qt.NoFocus)
        self.zm01.setIconSize(QtCore.QSize(0, 0))
        self.zm01.setObjectName("zm01")
        self.horizontalLayout_3.addWidget(self.zm01)
        self.zm1 = QtWidgets.QPushButton(ControlPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zm1.sizePolicy().hasHeightForWidth())
        self.zm1.setSizePolicy(sizePolicy)
        self.zm1.setMinimumSize(QtCore.QSize(60, 30))
        self.zm1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.zm1.setFont(font)
        self.zm1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.zm1.setIconSize(QtCore.QSize(0, 0))
        self.zm1.setObjectName("zm1")
        self.horizontalLayout_3.addWidget(self.zm1)
        self.zm10 = QtWidgets.QPushButton(ControlPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zm10.sizePolicy().hasHeightForWidth())
        self.zm10.setSizePolicy(sizePolicy)
        self.zm10.setMinimumSize(QtCore.QSize(60, 30))
        self.zm10.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.zm10.setFont(font)
        self.zm10.setFocusPolicy(QtCore.Qt.NoFocus)
        self.zm10.setIconSize(QtCore.QSize(0, 0))
        self.zm10.setObjectName("zm10")
        self.horizontalLayout_3.addWidget(self.zm10)
        self.zm100 = QtWidgets.QPushButton(ControlPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zm100.sizePolicy().hasHeightForWidth())
        self.zm100.setSizePolicy(sizePolicy)
        self.zm100.setMinimumSize(QtCore.QSize(60, 30))
        self.zm100.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.zm100.setFont(font)
        self.zm100.setFocusPolicy(QtCore.Qt.NoFocus)
        self.zm100.setIconSize(QtCore.QSize(0, 0))
        self.zm100.setObjectName("zm100")
        self.horizontalLayout_3.addWidget(self.zm100)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 0, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(12)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.movex = QtWidgets.QPushButton(ControlPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.movex.sizePolicy().hasHeightForWidth())
        self.movex.setSizePolicy(sizePolicy)
        self.movex.setMinimumSize(QtCore.QSize(65, 0))
        self.movex.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.movex.setFocusPolicy(QtCore.Qt.NoFocus)
        self.movex.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/img/img/Bed_X.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.movex.setIcon(icon13)
        self.movex.setIconSize(QtCore.QSize(50, 40))
        self.movex.setObjectName("movex")
        self.horizontalLayout.addWidget(self.movex)
        self.xm01 = QtWidgets.QPushButton(ControlPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xm01.sizePolicy().hasHeightForWidth())
        self.xm01.setSizePolicy(sizePolicy)
        self.xm01.setMinimumSize(QtCore.QSize(60, 30))
        self.xm01.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.xm01.setFont(font)
        self.xm01.setFocusPolicy(QtCore.Qt.NoFocus)
        self.xm01.setIconSize(QtCore.QSize(0, 0))
        self.xm01.setObjectName("xm01")
        self.horizontalLayout.addWidget(self.xm01)
        self.xm1 = QtWidgets.QPushButton(ControlPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xm1.sizePolicy().hasHeightForWidth())
        self.xm1.setSizePolicy(sizePolicy)
        self.xm1.setMinimumSize(QtCore.QSize(60, 30))
        self.xm1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.xm1.setFont(font)
        self.xm1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.xm1.setIconSize(QtCore.QSize(0, 0))
        self.xm1.setObjectName("xm1")
        self.horizontalLayout.addWidget(self.xm1)
        self.xm10 = QtWidgets.QPushButton(ControlPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xm10.sizePolicy().hasHeightForWidth())
        self.xm10.setSizePolicy(sizePolicy)
        self.xm10.setMinimumSize(QtCore.QSize(60, 30))
        self.xm10.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.xm10.setFont(font)
        self.xm10.setFocusPolicy(QtCore.Qt.NoFocus)
        self.xm10.setIconSize(QtCore.QSize(0, 0))
        self.xm10.setObjectName("xm10")
        self.horizontalLayout.addWidget(self.xm10)
        self.xm100 = QtWidgets.QPushButton(ControlPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xm100.sizePolicy().hasHeightForWidth())
        self.xm100.setSizePolicy(sizePolicy)
        self.xm100.setMinimumSize(QtCore.QSize(60, 30))
        self.xm100.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.xm100.setFont(font)
        self.xm100.setFocusPolicy(QtCore.Qt.NoFocus)
        self.xm100.setIconSize(QtCore.QSize(0, 0))
        self.xm100.setObjectName("xm100")
        self.horizontalLayout.addWidget(self.xm100)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_2)
        self.BottomBar = QtWidgets.QWidget(ControlPage)
        self.BottomBar.setObjectName("BottomBar")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.BottomBar)
        self.horizontalLayout_7.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.Back = QtWidgets.QPushButton(self.BottomBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Back.sizePolicy().hasHeightForWidth())
        self.Back.setSizePolicy(sizePolicy)
        self.Back.setMinimumSize(QtCore.QSize(65, 65))
        self.Back.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Back.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Back.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/img/img/Small_arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Back.setIcon(icon14)
        self.Back.setIconSize(QtCore.QSize(55, 55))
        self.Back.setObjectName("Back")
        self.horizontalLayout_7.addWidget(self.Back)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.xposlabel = QtWidgets.QLabel(self.BottomBar)
        self.xposlabel.setObjectName("xposlabel")
        self.horizontalLayout_7.addWidget(self.xposlabel)
        self.w_lineedit_x_position = QtWidgets.QLabel(self.BottomBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_lineedit_x_position.sizePolicy().hasHeightForWidth())
        self.w_lineedit_x_position.setSizePolicy(sizePolicy)
        self.w_lineedit_x_position.setMinimumSize(QtCore.QSize(90, 0))
        self.w_lineedit_x_position.setObjectName("w_lineedit_x_position")
        self.horizontalLayout_7.addWidget(self.w_lineedit_x_position)
        self.yposlabel = QtWidgets.QLabel(self.BottomBar)
        self.yposlabel.setObjectName("yposlabel")
        self.horizontalLayout_7.addWidget(self.yposlabel)
        self.w_lineedit_y_position = QtWidgets.QLabel(self.BottomBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_lineedit_y_position.sizePolicy().hasHeightForWidth())
        self.w_lineedit_y_position.setSizePolicy(sizePolicy)
        self.w_lineedit_y_position.setMinimumSize(QtCore.QSize(90, 0))
        self.w_lineedit_y_position.setObjectName("w_lineedit_y_position")
        self.horizontalLayout_7.addWidget(self.w_lineedit_y_position)
        self.zposlabel = QtWidgets.QLabel(self.BottomBar)
        self.zposlabel.setObjectName("zposlabel")
        self.horizontalLayout_7.addWidget(self.zposlabel)
        self.w_lineedit_z_position = QtWidgets.QLabel(self.BottomBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_lineedit_z_position.sizePolicy().hasHeightForWidth())
        self.w_lineedit_z_position.setSizePolicy(sizePolicy)
        self.w_lineedit_z_position.setMinimumSize(QtCore.QSize(90, 0))
        self.w_lineedit_z_position.setObjectName("w_lineedit_z_position")
        self.horizontalLayout_7.addWidget(self.w_lineedit_z_position)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.verticalLayout_5.addWidget(self.BottomBar)

        self.retranslateUi(ControlPage)
        QtCore.QMetaObject.connectSlotsByName(ControlPage)

    def retranslateUi(self, ControlPage):
        _translate = QtCore.QCoreApplication.translate
        ControlPage.setWindowTitle(_translate("ControlPage", "ControlPage"))
        self.ym01.setToolTip(_translate("ControlPage", "<html><head/><body><p><span style=\" font-size:24pt;\">0.1</span></p></body></html>"))
        self.ym01.setText(_translate("ControlPage", "0.1"))
        self.ym1.setToolTip(_translate("ControlPage", "<html><head/><body><p><span style=\" font-size:24pt;\">0.1</span></p></body></html>"))
        self.ym1.setText(_translate("ControlPage", "1"))
        self.ym10.setToolTip(_translate("ControlPage", "<html><head/><body><p><span style=\" font-size:24pt;\">0.1</span></p></body></html>"))
        self.ym10.setText(_translate("ControlPage", "10"))
        self.ym100.setToolTip(_translate("ControlPage", "<html><head/><body><p><span style=\" font-size:24pt;\">0.1</span></p></body></html>"))
        self.ym100.setText(_translate("ControlPage", "100"))
        self.em01.setToolTip(_translate("ControlPage", "<html><head/><body><p><span style=\" font-size:24pt;\">0.1</span></p></body></html>"))
        self.em01.setText(_translate("ControlPage", "0.1"))
        self.em1.setToolTip(_translate("ControlPage", "<html><head/><body><p><span style=\" font-size:24pt;\">0.1</span></p></body></html>"))
        self.em1.setText(_translate("ControlPage", "1"))
        self.em10.setToolTip(_translate("ControlPage", "<html><head/><body><p><span style=\" font-size:24pt;\">0.1</span></p></body></html>"))
        self.em10.setText(_translate("ControlPage", "10"))
        self.em100.setToolTip(_translate("ControlPage", "<html><head/><body><p><span style=\" font-size:24pt;\">0.1</span></p></body></html>"))
        self.em100.setText(_translate("ControlPage", "100"))
        self.zm01.setToolTip(_translate("ControlPage", "<html><head/><body><p><span style=\" font-size:24pt;\">0.1</span></p></body></html>"))
        self.zm01.setText(_translate("ControlPage", "0.1"))
        self.zm1.setToolTip(_translate("ControlPage", "<html><head/><body><p><span style=\" font-size:24pt;\">0.1</span></p></body></html>"))
        self.zm1.setText(_translate("ControlPage", "1"))
        self.zm10.setToolTip(_translate("ControlPage", "<html><head/><body><p><span style=\" font-size:24pt;\">0.1</span></p></body></html>"))
        self.zm10.setText(_translate("ControlPage", "10"))
        self.zm100.setToolTip(_translate("ControlPage", "<html><head/><body><p><span style=\" font-size:24pt;\">0.1</span></p></body></html>"))
        self.zm100.setText(_translate("ControlPage", "100"))
        self.xm01.setToolTip(_translate("ControlPage", "<html><head/><body><p><span style=\" font-size:24pt;\">0.1</span></p></body></html>"))
        self.xm01.setText(_translate("ControlPage", "0.1"))
        self.xm1.setToolTip(_translate("ControlPage", "<html><head/><body><p><span style=\" font-size:24pt;\">0.1</span></p></body></html>"))
        self.xm1.setText(_translate("ControlPage", "1"))
        self.xm10.setToolTip(_translate("ControlPage", "<html><head/><body><p><span style=\" font-size:24pt;\">0.1</span></p></body></html>"))
        self.xm10.setText(_translate("ControlPage", "10"))
        self.xm100.setToolTip(_translate("ControlPage", "<html><head/><body><p><span style=\" font-size:24pt;\">0.1</span></p></body></html>"))
        self.xm100.setText(_translate("ControlPage", "100"))
        self.xposlabel.setText(_translate("ControlPage", "X:"))
        self.w_lineedit_x_position.setText(_translate("ControlPage", "-----"))
        self.yposlabel.setText(_translate("ControlPage", "Y:"))
        self.w_lineedit_y_position.setText(_translate("ControlPage", "-----"))
        self.zposlabel.setText(_translate("ControlPage", "Z:"))
        self.w_lineedit_z_position.setText(_translate("ControlPage", "-----"))
import img_rc
