# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'controlpage_qt.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ControlPage(object):
    def setupUi(self, ControlPage):
        ControlPage.setObjectName("ControlPage")
        ControlPage.resize(800, 448)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ControlPage.sizePolicy().hasHeightForWidth())
        ControlPage.setSizePolicy(sizePolicy)
        ControlPage.setMaximumSize(QtCore.QSize(800, 448))
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(ControlPage)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(10, 10, 10, -1)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSpacing(15)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.YPos = QtWidgets.QPushButton(ControlPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.YPos.sizePolicy().hasHeightForWidth())
        self.YPos.setSizePolicy(sizePolicy)
        self.YPos.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.YPos.setFocusPolicy(QtCore.Qt.NoFocus)
        self.YPos.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/img/UP.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.YPos.setIcon(icon)
        self.YPos.setIconSize(QtCore.QSize(75, 75))
        self.YPos.setObjectName("YPos")
        self.gridLayout_3.addWidget(self.YPos, 0, 1, 1, 1)
        self.XNeg = QtWidgets.QPushButton(ControlPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.XNeg.sizePolicy().hasHeightForWidth())
        self.XNeg.setSizePolicy(sizePolicy)
        self.XNeg.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.XNeg.setFocusPolicy(QtCore.Qt.NoFocus)
        self.XNeg.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/img/img/Left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.XNeg.setIcon(icon1)
        self.XNeg.setIconSize(QtCore.QSize(75, 75))
        self.XNeg.setObjectName("XNeg")
        self.gridLayout_3.addWidget(self.XNeg, 1, 0, 1, 1)
        self.YNeg = QtWidgets.QPushButton(ControlPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.YNeg.sizePolicy().hasHeightForWidth())
        self.YNeg.setSizePolicy(sizePolicy)
        self.YNeg.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.YNeg.setFocusPolicy(QtCore.Qt.NoFocus)
        self.YNeg.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/img/img/Down.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.YNeg.setIcon(icon2)
        self.YNeg.setIconSize(QtCore.QSize(75, 75))
        self.YNeg.setObjectName("YNeg")
        self.gridLayout_3.addWidget(self.YNeg, 2, 1, 1, 1)
        self.XYIcon = QtWidgets.QPushButton(ControlPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.XYIcon.sizePolicy().hasHeightForWidth())
        self.XYIcon.setSizePolicy(sizePolicy)
        self.XYIcon.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.XYIcon.setFocusPolicy(QtCore.Qt.NoFocus)
        self.XYIcon.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/img/img/Bed_Front_XY.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.XYIcon.setIcon(icon3)
        self.XYIcon.setIconSize(QtCore.QSize(75, 75))
        self.XYIcon.setObjectName("XYIcon")
        self.gridLayout_3.addWidget(self.XYIcon, 1, 1, 1, 1)
        self.XPos = QtWidgets.QPushButton(ControlPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.XPos.sizePolicy().hasHeightForWidth())
        self.XPos.setSizePolicy(sizePolicy)
        self.XPos.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.XPos.setFocusPolicy(QtCore.Qt.NoFocus)
        self.XPos.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/img/img/Right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.XPos.setIcon(icon4)
        self.XPos.setIconSize(QtCore.QSize(75, 75))
        self.XPos.setObjectName("XPos")
        self.gridLayout_3.addWidget(self.XPos, 1, 2, 1, 1)
        self.horizontalLayout_5.addLayout(self.gridLayout_3)
        spacerItem2 = QtWidgets.QSpacerItem(55, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ZNeg = QtWidgets.QPushButton(ControlPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ZNeg.sizePolicy().hasHeightForWidth())
        self.ZNeg.setSizePolicy(sizePolicy)
        self.ZNeg.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.ZNeg.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ZNeg.setText("")
        self.ZNeg.setIcon(icon)
        self.ZNeg.setIconSize(QtCore.QSize(75, 75))
        self.ZNeg.setObjectName("ZNeg")
        self.verticalLayout.addWidget(self.ZNeg)
        self.ZIcon = QtWidgets.QPushButton(ControlPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ZIcon.sizePolicy().hasHeightForWidth())
        self.ZIcon.setSizePolicy(sizePolicy)
        self.ZIcon.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.ZIcon.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ZIcon.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/img/img/Bed_Z.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ZIcon.setIcon(icon5)
        self.ZIcon.setIconSize(QtCore.QSize(75, 75))
        self.ZIcon.setObjectName("ZIcon")
        self.verticalLayout.addWidget(self.ZIcon)
        self.ZPos = QtWidgets.QPushButton(ControlPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ZPos.sizePolicy().hasHeightForWidth())
        self.ZPos.setSizePolicy(sizePolicy)
        self.ZPos.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.ZPos.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ZPos.setText("")
        self.ZPos.setIcon(icon2)
        self.ZPos.setIconSize(QtCore.QSize(75, 75))
        self.ZPos.setObjectName("ZPos")
        self.verticalLayout.addWidget(self.ZPos)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(15)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.E0Neg = QtWidgets.QPushButton(ControlPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.E0Neg.sizePolicy().hasHeightForWidth())
        self.E0Neg.setSizePolicy(sizePolicy)
        self.E0Neg.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.E0Neg.setFocusPolicy(QtCore.Qt.NoFocus)
        self.E0Neg.setText("")
        self.E0Neg.setIcon(icon)
        self.E0Neg.setIconSize(QtCore.QSize(75, 75))
        self.E0Neg.setObjectName("E0Neg")
        self.verticalLayout_2.addWidget(self.E0Neg)
        self.E0Icon = QtWidgets.QPushButton(ControlPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.E0Icon.sizePolicy().hasHeightForWidth())
        self.E0Icon.setSizePolicy(sizePolicy)
        self.E0Icon.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.E0Icon.setFocusPolicy(QtCore.Qt.NoFocus)
        self.E0Icon.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/img/img/Extruder_0.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.E0Icon.setIcon(icon6)
        self.E0Icon.setIconSize(QtCore.QSize(75, 75))
        self.E0Icon.setObjectName("E0Icon")
        self.verticalLayout_2.addWidget(self.E0Icon)
        self.E0Pos = QtWidgets.QPushButton(ControlPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.E0Pos.sizePolicy().hasHeightForWidth())
        self.E0Pos.setSizePolicy(sizePolicy)
        self.E0Pos.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.E0Pos.setFocusPolicy(QtCore.Qt.NoFocus)
        self.E0Pos.setText("")
        self.E0Pos.setIcon(icon2)
        self.E0Pos.setIconSize(QtCore.QSize(75, 75))
        self.E0Pos.setObjectName("E0Pos")
        self.verticalLayout_2.addWidget(self.E0Pos)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(15)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.E1Neg = QtWidgets.QPushButton(ControlPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.E1Neg.sizePolicy().hasHeightForWidth())
        self.E1Neg.setSizePolicy(sizePolicy)
        self.E1Neg.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.E1Neg.setFocusPolicy(QtCore.Qt.NoFocus)
        self.E1Neg.setText("")
        self.E1Neg.setIcon(icon)
        self.E1Neg.setIconSize(QtCore.QSize(75, 75))
        self.E1Neg.setObjectName("E1Neg")
        self.verticalLayout_3.addWidget(self.E1Neg)
        self.E1Icon = QtWidgets.QPushButton(ControlPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.E1Icon.sizePolicy().hasHeightForWidth())
        self.E1Icon.setSizePolicy(sizePolicy)
        self.E1Icon.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.E1Icon.setFocusPolicy(QtCore.Qt.NoFocus)
        self.E1Icon.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/img/img/Extruder_1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.E1Icon.setIcon(icon7)
        self.E1Icon.setIconSize(QtCore.QSize(75, 75))
        self.E1Icon.setObjectName("E1Icon")
        self.verticalLayout_3.addWidget(self.E1Icon)
        self.E1Pos = QtWidgets.QPushButton(ControlPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.E1Pos.sizePolicy().hasHeightForWidth())
        self.E1Pos.setSizePolicy(sizePolicy)
        self.E1Pos.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.E1Pos.setFocusPolicy(QtCore.Qt.NoFocus)
        self.E1Pos.setText("")
        self.E1Pos.setIcon(icon2)
        self.E1Pos.setIconSize(QtCore.QSize(75, 75))
        self.E1Pos.setObjectName("E1Pos")
        self.verticalLayout_3.addWidget(self.E1Pos)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_5.addItem(spacerItem5)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(15, 5, 15, 5)
        self.horizontalLayout_6.setSpacing(12)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.HomeAll = QtWidgets.QPushButton(ControlPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.HomeAll.sizePolicy().hasHeightForWidth())
        self.HomeAll.setSizePolicy(sizePolicy)
        self.HomeAll.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.HomeAll.setFocusPolicy(QtCore.Qt.NoFocus)
        self.HomeAll.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/img/img/Home_XYZ.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.HomeAll.setIcon(icon8)
        self.HomeAll.setIconSize(QtCore.QSize(55, 55))
        self.HomeAll.setObjectName("HomeAll")
        self.horizontalLayout_6.addWidget(self.HomeAll)
        self.HomeXY = QtWidgets.QPushButton(ControlPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.HomeXY.sizePolicy().hasHeightForWidth())
        self.HomeXY.setSizePolicy(sizePolicy)
        self.HomeXY.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.HomeXY.setFocusPolicy(QtCore.Qt.NoFocus)
        self.HomeXY.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/img/img/Home_XY.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.HomeXY.setIcon(icon9)
        self.HomeXY.setIconSize(QtCore.QSize(55, 55))
        self.HomeXY.setObjectName("HomeXY")
        self.horizontalLayout_6.addWidget(self.HomeXY)
        self.HomeZ = QtWidgets.QPushButton(ControlPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.HomeZ.sizePolicy().hasHeightForWidth())
        self.HomeZ.setSizePolicy(sizePolicy)
        self.HomeZ.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.HomeZ.setFocusPolicy(QtCore.Qt.NoFocus)
        self.HomeZ.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/img/img/Home_Z.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.HomeZ.setIcon(icon10)
        self.HomeZ.setIconSize(QtCore.QSize(55, 55))
        self.HomeZ.setObjectName("HomeZ")
        self.horizontalLayout_6.addWidget(self.HomeZ)
        spacerItem7 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem7)
        self.DisableMotors = QtWidgets.QPushButton(ControlPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DisableMotors.sizePolicy().hasHeightForWidth())
        self.DisableMotors.setSizePolicy(sizePolicy)
        self.DisableMotors.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.DisableMotors.setFocusPolicy(QtCore.Qt.NoFocus)
        self.DisableMotors.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/img/img/Stepper_Motor_Off.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.DisableMotors.setIcon(icon11)
        self.DisableMotors.setIconSize(QtCore.QSize(55, 55))
        self.DisableMotors.setObjectName("DisableMotors")
        self.horizontalLayout_6.addWidget(self.DisableMotors)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem8)
        self.globalm01 = QtWidgets.QPushButton(ControlPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.globalm01.sizePolicy().hasHeightForWidth())
        self.globalm01.setSizePolicy(sizePolicy)
        self.globalm01.setMinimumSize(QtCore.QSize(85, 35))
        self.globalm01.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.globalm01.setFont(font)
        self.globalm01.setFocusPolicy(QtCore.Qt.NoFocus)
        self.globalm01.setToolTip("")
        self.globalm01.setIconSize(QtCore.QSize(0, 0))
        self.globalm01.setObjectName("globalm01")
        self.horizontalLayout_6.addWidget(self.globalm01)
        self.globalm1 = QtWidgets.QPushButton(ControlPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.globalm1.sizePolicy().hasHeightForWidth())
        self.globalm1.setSizePolicy(sizePolicy)
        self.globalm1.setMinimumSize(QtCore.QSize(85, 35))
        self.globalm1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.globalm1.setFont(font)
        self.globalm1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.globalm1.setToolTip("")
        self.globalm1.setIconSize(QtCore.QSize(0, 0))
        self.globalm1.setObjectName("globalm1")
        self.horizontalLayout_6.addWidget(self.globalm1)
        self.globalm10 = QtWidgets.QPushButton(ControlPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.globalm10.sizePolicy().hasHeightForWidth())
        self.globalm10.setSizePolicy(sizePolicy)
        self.globalm10.setMinimumSize(QtCore.QSize(85, 35))
        self.globalm10.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.globalm10.setFont(font)
        self.globalm10.setFocusPolicy(QtCore.Qt.NoFocus)
        self.globalm10.setToolTip("")
        self.globalm10.setIconSize(QtCore.QSize(0, 0))
        self.globalm10.setObjectName("globalm10")
        self.horizontalLayout_6.addWidget(self.globalm10)
        self.globalm100 = QtWidgets.QPushButton(ControlPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.globalm100.sizePolicy().hasHeightForWidth())
        self.globalm100.setSizePolicy(sizePolicy)
        self.globalm100.setMinimumSize(QtCore.QSize(85, 35))
        self.globalm100.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.globalm100.setFont(font)
        self.globalm100.setFocusPolicy(QtCore.Qt.NoFocus)
        self.globalm100.setToolTip("")
        self.globalm100.setIconSize(QtCore.QSize(0, 0))
        self.globalm100.setObjectName("globalm100")
        self.horizontalLayout_6.addWidget(self.globalm100)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.BottomBar = QtWidgets.QWidget(ControlPage)
        self.BottomBar.setObjectName("BottomBar")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.BottomBar)
        self.horizontalLayout_7.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.Back = QtWidgets.QPushButton(self.BottomBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Back.sizePolicy().hasHeightForWidth())
        self.Back.setSizePolicy(sizePolicy)
        self.Back.setMinimumSize(QtCore.QSize(65, 65))
        self.Back.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Back.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Back.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/img/img/Small_arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Back.setIcon(icon12)
        self.Back.setIconSize(QtCore.QSize(55, 55))
        self.Back.setObjectName("Back")
        self.horizontalLayout_7.addWidget(self.Back)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem9)
        self.xposlabel = QtWidgets.QLabel(self.BottomBar)
        self.xposlabel.setObjectName("xposlabel")
        self.horizontalLayout_7.addWidget(self.xposlabel)
        self.w_lineedit_x_position = QtWidgets.QLabel(self.BottomBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_lineedit_x_position.sizePolicy().hasHeightForWidth())
        self.w_lineedit_x_position.setSizePolicy(sizePolicy)
        self.w_lineedit_x_position.setMinimumSize(QtCore.QSize(90, 0))
        self.w_lineedit_x_position.setObjectName("w_lineedit_x_position")
        self.horizontalLayout_7.addWidget(self.w_lineedit_x_position)
        self.yposlabel = QtWidgets.QLabel(self.BottomBar)
        self.yposlabel.setObjectName("yposlabel")
        self.horizontalLayout_7.addWidget(self.yposlabel)
        self.w_lineedit_y_position = QtWidgets.QLabel(self.BottomBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_lineedit_y_position.sizePolicy().hasHeightForWidth())
        self.w_lineedit_y_position.setSizePolicy(sizePolicy)
        self.w_lineedit_y_position.setMinimumSize(QtCore.QSize(90, 0))
        self.w_lineedit_y_position.setObjectName("w_lineedit_y_position")
        self.horizontalLayout_7.addWidget(self.w_lineedit_y_position)
        self.zposlabel = QtWidgets.QLabel(self.BottomBar)
        self.zposlabel.setObjectName("zposlabel")
        self.horizontalLayout_7.addWidget(self.zposlabel)
        self.w_lineedit_z_position = QtWidgets.QLabel(self.BottomBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_lineedit_z_position.sizePolicy().hasHeightForWidth())
        self.w_lineedit_z_position.setSizePolicy(sizePolicy)
        self.w_lineedit_z_position.setMinimumSize(QtCore.QSize(90, 0))
        self.w_lineedit_z_position.setObjectName("w_lineedit_z_position")
        self.horizontalLayout_7.addWidget(self.w_lineedit_z_position)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem10)
        self.verticalLayout_4.addWidget(self.BottomBar)

        self.retranslateUi(ControlPage)
        QtCore.QMetaObject.connectSlotsByName(ControlPage)

    def retranslateUi(self, ControlPage):
        _translate = QtCore.QCoreApplication.translate
        ControlPage.setWindowTitle(_translate("ControlPage", "ControlPage"))
        self.globalm01.setText(_translate("ControlPage", "0.1"))
        self.globalm1.setText(_translate("ControlPage", "1"))
        self.globalm10.setText(_translate("ControlPage", "10"))
        self.globalm100.setText(_translate("ControlPage", "100"))
        self.xposlabel.setText(_translate("ControlPage", "X:"))
        self.w_lineedit_x_position.setText(_translate("ControlPage", "-----"))
        self.yposlabel.setText(_translate("ControlPage", "Y:"))
        self.w_lineedit_y_position.setText(_translate("ControlPage", "-----"))
        self.zposlabel.setText(_translate("ControlPage", "Z:"))
        self.w_lineedit_z_position.setText(_translate("ControlPage", "-----"))
import img_rc
