# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'debugpage_qt.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DebugPage(object):
    def setupUi(self, DebugPage):
        DebugPage.setObjectName("DebugPage")
        DebugPage.resize(800, 448)
        DebugPage.setMaximumSize(QtCore.QSize(800, 448))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(DebugPage)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.LeftBar = QtWidgets.QWidget(DebugPage)
        self.LeftBar.setObjectName("LeftBar")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.LeftBar)
        self.verticalLayout_6.setContentsMargins(-1, -1, -1, 9)
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.w_pushbutton_add_marker = QtWidgets.QPushButton(self.LeftBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_pushbutton_add_marker.sizePolicy().hasHeightForWidth())
        self.w_pushbutton_add_marker.setSizePolicy(sizePolicy)
        self.w_pushbutton_add_marker.setMinimumSize(QtCore.QSize(160, 60))
        self.w_pushbutton_add_marker.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.w_pushbutton_add_marker.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/img/Add_Log_Marker.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.w_pushbutton_add_marker.setIcon(icon)
        self.w_pushbutton_add_marker.setIconSize(QtCore.QSize(120, 60))
        self.w_pushbutton_add_marker.setObjectName("w_pushbutton_add_marker")
        self.verticalLayout_6.addWidget(self.w_pushbutton_add_marker)
        self.w_pushbutton_copy_log = QtWidgets.QPushButton(self.LeftBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_pushbutton_copy_log.sizePolicy().hasHeightForWidth())
        self.w_pushbutton_copy_log.setSizePolicy(sizePolicy)
        self.w_pushbutton_copy_log.setMinimumSize(QtCore.QSize(160, 60))
        self.w_pushbutton_copy_log.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.w_pushbutton_copy_log.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/img/img/Copy_Log_files.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.w_pushbutton_copy_log.setIcon(icon1)
        self.w_pushbutton_copy_log.setIconSize(QtCore.QSize(120, 60))
        self.w_pushbutton_copy_log.setObjectName("w_pushbutton_copy_log")
        self.verticalLayout_6.addWidget(self.w_pushbutton_copy_log)
        self.w_pushbutton_send_fake_ack = QtWidgets.QPushButton(self.LeftBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_pushbutton_send_fake_ack.sizePolicy().hasHeightForWidth())
        self.w_pushbutton_send_fake_ack.setSizePolicy(sizePolicy)
        self.w_pushbutton_send_fake_ack.setMinimumSize(QtCore.QSize(160, 60))
        self.w_pushbutton_send_fake_ack.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.w_pushbutton_send_fake_ack.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/img/img/Send_Fake_ACK.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.w_pushbutton_send_fake_ack.setIcon(icon2)
        self.w_pushbutton_send_fake_ack.setIconSize(QtCore.QSize(120, 60))
        self.w_pushbutton_send_fake_ack.setObjectName("w_pushbutton_send_fake_ack")
        self.verticalLayout_6.addWidget(self.w_pushbutton_send_fake_ack)
        self.logging_label = QtWidgets.QLabel(self.LeftBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logging_label.sizePolicy().hasHeightForWidth())
        self.logging_label.setSizePolicy(sizePolicy)
        self.logging_label.setMinimumSize(QtCore.QSize(0, 25))
        self.logging_label.setObjectName("logging_label")
        self.verticalLayout_6.addWidget(self.logging_label)
        self.w_combobox_debuglevel = QtWidgets.QComboBox(self.LeftBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_combobox_debuglevel.sizePolicy().hasHeightForWidth())
        self.w_combobox_debuglevel.setSizePolicy(sizePolicy)
        self.w_combobox_debuglevel.setMinimumSize(QtCore.QSize(0, 55))
        self.w_combobox_debuglevel.setFrame(False)
        self.w_combobox_debuglevel.setObjectName("w_combobox_debuglevel")
        self.w_combobox_debuglevel.addItem("")
        self.w_combobox_debuglevel.addItem("")
        self.verticalLayout_6.addWidget(self.w_combobox_debuglevel)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_6.addItem(spacerItem1)
        self.horizontalLayout_2.addWidget(self.LeftBar)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.w_lineedit_message = QtWidgets.QLineEdit(DebugPage)
        self.w_lineedit_message.setObjectName("w_lineedit_message")
        self.verticalLayout.addWidget(self.w_lineedit_message)
        self.w_message_text = QtWidgets.QTextBrowser(DebugPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_message_text.sizePolicy().hasHeightForWidth())
        self.w_message_text.setSizePolicy(sizePolicy)
        self.w_message_text.setMaximumSize(QtCore.QSize(115200, 1000))
        self.w_message_text.setObjectName("w_message_text")
        self.verticalLayout.addWidget(self.w_message_text)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.BottomBar = QtWidgets.QWidget(DebugPage)
        self.BottomBar.setObjectName("BottomBar")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.BottomBar)
        self.horizontalLayout_3.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Back = QtWidgets.QPushButton(self.BottomBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Back.sizePolicy().hasHeightForWidth())
        self.Back.setSizePolicy(sizePolicy)
        self.Back.setMinimumSize(QtCore.QSize(65, 65))
        self.Back.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Back.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Back.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/img/img/Small_arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Back.setIcon(icon3)
        self.Back.setIconSize(QtCore.QSize(55, 55))
        self.Back.setObjectName("Back")
        self.horizontalLayout_3.addWidget(self.Back)
        spacerItem2 = QtWidgets.QSpacerItem(282, 40, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_2.addWidget(self.BottomBar)

        self.retranslateUi(DebugPage)
        QtCore.QMetaObject.connectSlotsByName(DebugPage)

    def retranslateUi(self, DebugPage):
        _translate = QtCore.QCoreApplication.translate
        DebugPage.setWindowTitle(_translate("DebugPage", "ControlWindow"))
        self.logging_label.setText(_translate("DebugPage", "Logging level:"))
        self.w_combobox_debuglevel.setItemText(0, _translate("DebugPage", "DEBUG"))
        self.w_combobox_debuglevel.setItemText(1, _translate("DebugPage", "INFO"))
import img_rc
