# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'duexsetupwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_duexSetupWindow(object):
    def setupUi(self, duexSetupWindow):
        duexSetupWindow.setObjectName("duexSetupWindow")
        duexSetupWindow.resize(800, 480)
        duexSetupWindow.setMaximumSize(QtCore.QSize(800, 480))
        self.Back = QtWidgets.QPushButton(duexSetupWindow)
        self.Back.setGeometry(QtCore.QRect(10, 380, 91, 91))
        self.Back.setMaximumSize(QtCore.QSize(100, 100))
        self.Back.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Back.setIcon(icon)
        self.Back.setIconSize(QtCore.QSize(100, 100))
        self.Back.setObjectName("Back")
        self.verticalLayoutWidget = QtWidgets.QWidget(duexSetupWindow)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(264, 60, 301, 241))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.w_lineedit_x1 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.w_lineedit_x1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.w_lineedit_x1.setFont(font)
        self.w_lineedit_x1.setObjectName("w_lineedit_x1")
        self.horizontalLayout.addWidget(self.w_lineedit_x1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.w_lineedit_y1 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.w_lineedit_y1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.w_lineedit_y1.setFont(font)
        self.w_lineedit_y1.setObjectName("w_lineedit_y1")
        self.horizontalLayout_2.addWidget(self.w_lineedit_y1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.w_pushbutton_temporary = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.w_pushbutton_temporary.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.w_pushbutton_temporary.setFont(font)
        self.w_pushbutton_temporary.setObjectName("w_pushbutton_temporary")
        self.verticalLayout.addWidget(self.w_pushbutton_temporary)
        self.w_pushbutton_permanent = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.w_pushbutton_permanent.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.w_pushbutton_permanent.setFont(font)
        self.w_pushbutton_permanent.setObjectName("w_pushbutton_permanent")
        self.verticalLayout.addWidget(self.w_pushbutton_permanent)
        self.w_pushbutton_revert = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.w_pushbutton_revert.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.w_pushbutton_revert.setFont(font)
        self.w_pushbutton_revert.setObjectName("w_pushbutton_revert")
        self.verticalLayout.addWidget(self.w_pushbutton_revert)

        self.retranslateUi(duexSetupWindow)
        QtCore.QMetaObject.connectSlotsByName(duexSetupWindow)

    def retranslateUi(self, duexSetupWindow):
        _translate = QtCore.QCoreApplication.translate
        duexSetupWindow.setWindowTitle(_translate("duexSetupWindow", "ControlWindow"))
        self.label_3.setText(_translate("duexSetupWindow", "Dual Extruder Offsets"))
        self.label.setText(_translate("duexSetupWindow", "T1 X Offset"))
        self.label_2.setText(_translate("duexSetupWindow", "T1 Y Offset"))
        self.w_pushbutton_temporary.setText(_translate("duexSetupWindow", "Use these settings temporarily"))
        self.w_pushbutton_permanent.setText(_translate("duexSetupWindow", "Save these settings permanently"))
        self.w_pushbutton_revert.setText(_translate("duexSetupWindow", "Revert to last saved settings"))
