%.py: %.ui
	pyuic5-3.7 $< -o $@

all: activeprintwidget.py \
     controlwindow.py \
     notactiveprintwidget.py \
     notificationwindow.py \
     printwindow.py \
     runout.py \
     serialwindow.py \
     serverwindow.py \
     settingswindow.py \
     temperaturewindow.py \
     touchdisplaywindow.py \
     userupdatewindow.py
