# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'infopage_qt.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InfoPage(object):
    def setupUi(self, InfoPage):
        InfoPage.setObjectName("InfoPage")
        InfoPage.resize(800, 448)
        InfoPage.setMaximumSize(QtCore.QSize(800, 448))
        self.verticalLayout = QtWidgets.QVBoxLayout(InfoPage)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.LeftBar = QtWidgets.QWidget(InfoPage)
        self.LeftBar.setObjectName("LeftBar")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.LeftBar)
        self.verticalLayout_7.setContentsMargins(-1, -1, -1, 9)
        self.verticalLayout_7.setSpacing(6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.w_pushbutton_info = QtWidgets.QPushButton(self.LeftBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_pushbutton_info.sizePolicy().hasHeightForWidth())
        self.w_pushbutton_info.setSizePolicy(sizePolicy)
        self.w_pushbutton_info.setMinimumSize(QtCore.QSize(160, 60))
        self.w_pushbutton_info.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.w_pushbutton_info.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/img/Gigabot.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.w_pushbutton_info.setIcon(icon)
        self.w_pushbutton_info.setIconSize(QtCore.QSize(160, 40))
        self.w_pushbutton_info.setObjectName("w_pushbutton_info")
        self.verticalLayout_7.addWidget(self.w_pushbutton_info)
        self.w_pushbutton_capabilities = QtWidgets.QPushButton(self.LeftBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_pushbutton_capabilities.sizePolicy().hasHeightForWidth())
        self.w_pushbutton_capabilities.setSizePolicy(sizePolicy)
        self.w_pushbutton_capabilities.setMinimumSize(QtCore.QSize(160, 60))
        self.w_pushbutton_capabilities.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.w_pushbutton_capabilities.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/img/img/Capabilities.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.w_pushbutton_capabilities.setIcon(icon1)
        self.w_pushbutton_capabilities.setIconSize(QtCore.QSize(160, 40))
        self.w_pushbutton_capabilities.setObjectName("w_pushbutton_capabilities")
        self.verticalLayout_7.addWidget(self.w_pushbutton_capabilities)
        self.w_pushbutton_stats = QtWidgets.QPushButton(self.LeftBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_pushbutton_stats.sizePolicy().hasHeightForWidth())
        self.w_pushbutton_stats.setSizePolicy(sizePolicy)
        self.w_pushbutton_stats.setMinimumSize(QtCore.QSize(160, 60))
        self.w_pushbutton_stats.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.w_pushbutton_stats.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/img/img/Stats.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.w_pushbutton_stats.setIcon(icon2)
        self.w_pushbutton_stats.setIconSize(QtCore.QSize(160, 40))
        self.w_pushbutton_stats.setObjectName("w_pushbutton_stats")
        self.verticalLayout_7.addWidget(self.w_pushbutton_stats)
        self.w_pushbutton_settings = QtWidgets.QPushButton(self.LeftBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_pushbutton_settings.sizePolicy().hasHeightForWidth())
        self.w_pushbutton_settings.setSizePolicy(sizePolicy)
        self.w_pushbutton_settings.setMinimumSize(QtCore.QSize(160, 60))
        self.w_pushbutton_settings.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.w_pushbutton_settings.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/img/img/Settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.w_pushbutton_settings.setIcon(icon3)
        self.w_pushbutton_settings.setIconSize(QtCore.QSize(160, 40))
        self.w_pushbutton_settings.setObjectName("w_pushbutton_settings")
        self.verticalLayout_7.addWidget(self.w_pushbutton_settings)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_7.addItem(spacerItem1)
        self.horizontalLayout.addWidget(self.LeftBar)
        self.w_message_text = QtWidgets.QTextEdit(InfoPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_message_text.sizePolicy().hasHeightForWidth())
        self.w_message_text.setSizePolicy(sizePolicy)
        self.w_message_text.setMaximumSize(QtCore.QSize(115200, 1000))
        self.w_message_text.setObjectName("w_message_text")
        self.horizontalLayout.addWidget(self.w_message_text)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.BottomBar = QtWidgets.QWidget(InfoPage)
        self.BottomBar.setObjectName("BottomBar")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.BottomBar)
        self.horizontalLayout_2.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Back = QtWidgets.QPushButton(self.BottomBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Back.sizePolicy().hasHeightForWidth())
        self.Back.setSizePolicy(sizePolicy)
        self.Back.setMinimumSize(QtCore.QSize(65, 65))
        self.Back.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Back.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Back.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/img/img/Small_arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Back.setIcon(icon4)
        self.Back.setIconSize(QtCore.QSize(55, 55))
        self.Back.setObjectName("Back")
        self.horizontalLayout_2.addWidget(self.Back)
        spacerItem2 = QtWidgets.QSpacerItem(282, 40, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout.addWidget(self.BottomBar)

        self.retranslateUi(InfoPage)
        QtCore.QMetaObject.connectSlotsByName(InfoPage)

    def retranslateUi(self, InfoPage):
        _translate = QtCore.QCoreApplication.translate
        InfoPage.setWindowTitle(_translate("InfoPage", "ControlWindow"))
import img_rc
