%.py: %.ui
	pyuic5-3.7 $< -o $@

all: activeprintwidget.py \
     controlwindow.py \
     debugwindow.py \
     duexsetupwindow.py \
     infowindow.py \
     notactiveprintwidget.py \
     notificationwindow.py \
     runout.py \
     serialwindow.py \
     serverwindow.py \
     settingswindow.py \
     temperaturewindow.py \
     userupdatewindow.py \
     home_qt.py \
     printpage_qt.py \
     mainwindow_qt.py
