# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/notactiveprintwidget.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_NotActivePrintWidget(object):
    def setupUi(self, NotActivePrintWidget):
        NotActivePrintWidget.setObjectName("NotActivePrintWidget")
        NotActivePrintWidget.resize(800, 196)
        NotActivePrintWidget.setMaximumSize(QtCore.QSize(800, 480))
        self.widget = QtWidgets.QWidget(NotActivePrintWidget)
        self.widget.setGeometry(QtCore.QRect(9, 30, 791, 151))
        self.widget.setObjectName("widget")
        self.NotActivePrint = QtWidgets.QHBoxLayout(self.widget)
        self.NotActivePrint.setObjectName("NotActivePrint")
        self.Back = QtWidgets.QPushButton(self.widget)
        self.Back.setMaximumSize(QtCore.QSize(100, 100))
        self.Back.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Back.setIcon(icon)
        self.Back.setIconSize(QtCore.QSize(100, 100))
        self.Back.setObjectName("Back")
        self.NotActivePrint.addWidget(self.Back)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.PreheatPLA = QtWidgets.QLabel(self.widget)
        self.PreheatPLA.setObjectName("PreheatPLA")
        self.horizontalLayout.addWidget(self.PreheatPLA)
        self.m1e1 = QtWidgets.QPushButton(self.widget)
        self.m1e1.setMinimumSize(QtCore.QSize(70, 30))
        self.m1e1.setMaximumSize(QtCore.QSize(75, 35))
        self.m1e1.setStyleSheet("font: 14pt \"Ubuntu\";")
        self.m1e1.setObjectName("m1e1")
        self.horizontalLayout.addWidget(self.m1e1)
        self.m1e2 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m1e2.sizePolicy().hasHeightForWidth())
        self.m1e2.setSizePolicy(sizePolicy)
        self.m1e2.setMinimumSize(QtCore.QSize(70, 30))
        self.m1e2.setMaximumSize(QtCore.QSize(75, 35))
        self.m1e2.setStyleSheet("font: 14pt \"Ubuntu\";")
        self.m1e2.setObjectName("m1e2")
        self.horizontalLayout.addWidget(self.m1e2)
        self.m1bed = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m1bed.sizePolicy().hasHeightForWidth())
        self.m1bed.setSizePolicy(sizePolicy)
        self.m1bed.setMinimumSize(QtCore.QSize(70, 30))
        self.m1bed.setMaximumSize(QtCore.QSize(75, 35))
        self.m1bed.setStyleSheet("font: 14pt \"Ubuntu\";")
        self.m1bed.setObjectName("m1bed")
        self.horizontalLayout.addWidget(self.m1bed)
        self.m1all = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m1all.sizePolicy().hasHeightForWidth())
        self.m1all.setSizePolicy(sizePolicy)
        self.m1all.setMinimumSize(QtCore.QSize(70, 30))
        self.m1all.setMaximumSize(QtCore.QSize(75, 35))
        self.m1all.setStyleSheet("font: 14pt \"Ubuntu\";")
        self.m1all.setObjectName("m1all")
        self.horizontalLayout.addWidget(self.m1all)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.PreheatPC = QtWidgets.QLabel(self.widget)
        self.PreheatPC.setObjectName("PreheatPC")
        self.horizontalLayout_2.addWidget(self.PreheatPC)
        self.m2e1 = QtWidgets.QPushButton(self.widget)
        self.m2e1.setMinimumSize(QtCore.QSize(70, 30))
        self.m2e1.setMaximumSize(QtCore.QSize(75, 35))
        self.m2e1.setStyleSheet("font: 14pt \"Ubuntu\";")
        self.m2e1.setObjectName("m2e1")
        self.horizontalLayout_2.addWidget(self.m2e1)
        self.m2e2 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m2e2.sizePolicy().hasHeightForWidth())
        self.m2e2.setSizePolicy(sizePolicy)
        self.m2e2.setMinimumSize(QtCore.QSize(70, 30))
        self.m2e2.setMaximumSize(QtCore.QSize(75, 35))
        self.m2e2.setStyleSheet("font: 14pt \"Ubuntu\";")
        self.m2e2.setObjectName("m2e2")
        self.horizontalLayout_2.addWidget(self.m2e2)
        self.m2bed = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m2bed.sizePolicy().hasHeightForWidth())
        self.m2bed.setSizePolicy(sizePolicy)
        self.m2bed.setMinimumSize(QtCore.QSize(70, 30))
        self.m2bed.setMaximumSize(QtCore.QSize(75, 35))
        self.m2bed.setStyleSheet("font: 14pt \"Ubuntu\";")
        self.m2bed.setObjectName("m2bed")
        self.horizontalLayout_2.addWidget(self.m2bed)
        self.m2all = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m2all.sizePolicy().hasHeightForWidth())
        self.m2all.setSizePolicy(sizePolicy)
        self.m2all.setMinimumSize(QtCore.QSize(70, 30))
        self.m2all.setMaximumSize(QtCore.QSize(75, 35))
        self.m2all.setStyleSheet("font: 14pt \"Ubuntu\";")
        self.m2all.setObjectName("m2all")
        self.horizontalLayout_2.addWidget(self.m2all)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.PreheatPETG = QtWidgets.QLabel(self.widget)
        self.PreheatPETG.setObjectName("PreheatPETG")
        self.horizontalLayout_3.addWidget(self.PreheatPETG)
        self.m3e1 = QtWidgets.QPushButton(self.widget)
        self.m3e1.setMinimumSize(QtCore.QSize(70, 30))
        self.m3e1.setMaximumSize(QtCore.QSize(75, 35))
        self.m3e1.setStyleSheet("font: 14pt \"Ubuntu\";")
        self.m3e1.setObjectName("m3e1")
        self.horizontalLayout_3.addWidget(self.m3e1)
        self.m3e2 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m3e2.sizePolicy().hasHeightForWidth())
        self.m3e2.setSizePolicy(sizePolicy)
        self.m3e2.setMinimumSize(QtCore.QSize(70, 30))
        self.m3e2.setMaximumSize(QtCore.QSize(75, 35))
        self.m3e2.setStyleSheet("font: 14pt \"Ubuntu\";")
        self.m3e2.setObjectName("m3e2")
        self.horizontalLayout_3.addWidget(self.m3e2)
        self.m3bed = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m3bed.sizePolicy().hasHeightForWidth())
        self.m3bed.setSizePolicy(sizePolicy)
        self.m3bed.setMinimumSize(QtCore.QSize(70, 30))
        self.m3bed.setMaximumSize(QtCore.QSize(75, 35))
        self.m3bed.setStyleSheet("font: 14pt \"Ubuntu\";")
        self.m3bed.setObjectName("m3bed")
        self.horizontalLayout_3.addWidget(self.m3bed)
        self.m3all = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m3all.sizePolicy().hasHeightForWidth())
        self.m3all.setSizePolicy(sizePolicy)
        self.m3all.setMinimumSize(QtCore.QSize(70, 30))
        self.m3all.setMaximumSize(QtCore.QSize(75, 35))
        self.m3all.setStyleSheet("font: 14pt \"Ubuntu\";")
        self.m3all.setObjectName("m3all")
        self.horizontalLayout_3.addWidget(self.m3all)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.NotActivePrint.addLayout(self.verticalLayout)
        self.Fan = QtWidgets.QPushButton(self.widget)
        self.Fan.setMaximumSize(QtCore.QSize(75, 75))
        self.Fan.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("img/fanoff.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Fan.setIcon(icon1)
        self.Fan.setIconSize(QtCore.QSize(65, 65))
        self.Fan.setObjectName("Fan")
        self.NotActivePrint.addWidget(self.Fan)
        self.CoolDown = QtWidgets.QPushButton(self.widget)
        self.CoolDown.setMaximumSize(QtCore.QSize(75, 75))
        self.CoolDown.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("img/cooldown.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.CoolDown.setIcon(icon2)
        self.CoolDown.setIconSize(QtCore.QSize(65, 65))
        self.CoolDown.setObjectName("CoolDown")
        self.NotActivePrint.addWidget(self.CoolDown)

        self.retranslateUi(NotActivePrintWidget)
        QtCore.QMetaObject.connectSlotsByName(NotActivePrintWidget)

    def retranslateUi(self, NotActivePrintWidget):
        _translate = QtCore.QCoreApplication.translate
        NotActivePrintWidget.setWindowTitle(_translate("NotActivePrintWidget", "TemperatureWindow"))
        self.PreheatPLA.setText(_translate("NotActivePrintWidget", "Preheat PLA"))
        self.m1e1.setToolTip(_translate("NotActivePrintWidget", "<html><head/><body><p><span style=\" font-size:24pt;\">0.1</span></p></body></html>"))
        self.m1e1.setText(_translate("NotActivePrintWidget", "E1"))
        self.m1e2.setToolTip(_translate("NotActivePrintWidget", "<html><head/><body><p><span style=\" font-size:24pt;\">0.1</span></p></body></html>"))
        self.m1e2.setText(_translate("NotActivePrintWidget", "E2"))
        self.m1bed.setToolTip(_translate("NotActivePrintWidget", "<html><head/><body><p><span style=\" font-size:24pt;\">0.1</span></p></body></html>"))
        self.m1bed.setText(_translate("NotActivePrintWidget", "Bed"))
        self.m1all.setToolTip(_translate("NotActivePrintWidget", "<html><head/><body><p><span style=\" font-size:24pt;\">0.1</span></p></body></html>"))
        self.m1all.setText(_translate("NotActivePrintWidget", "All"))
        self.PreheatPC.setText(_translate("NotActivePrintWidget", "Preheat PC"))
        self.m2e1.setToolTip(_translate("NotActivePrintWidget", "<html><head/><body><p><span style=\" font-size:24pt;\">0.1</span></p></body></html>"))
        self.m2e1.setText(_translate("NotActivePrintWidget", "E1"))
        self.m2e2.setToolTip(_translate("NotActivePrintWidget", "<html><head/><body><p><span style=\" font-size:24pt;\">0.1</span></p></body></html>"))
        self.m2e2.setText(_translate("NotActivePrintWidget", "E2"))
        self.m2bed.setToolTip(_translate("NotActivePrintWidget", "<html><head/><body><p><span style=\" font-size:24pt;\">0.1</span></p></body></html>"))
        self.m2bed.setText(_translate("NotActivePrintWidget", "Bed"))
        self.m2all.setToolTip(_translate("NotActivePrintWidget", "<html><head/><body><p><span style=\" font-size:24pt;\">0.1</span></p></body></html>"))
        self.m2all.setText(_translate("NotActivePrintWidget", "All"))
        self.PreheatPETG.setText(_translate("NotActivePrintWidget", "Preheat PETG"))
        self.m3e1.setToolTip(_translate("NotActivePrintWidget", "<html><head/><body><p><span style=\" font-size:24pt;\">0.1</span></p></body></html>"))
        self.m3e1.setText(_translate("NotActivePrintWidget", "E1"))
        self.m3e2.setToolTip(_translate("NotActivePrintWidget", "<html><head/><body><p><span style=\" font-size:24pt;\">0.1</span></p></body></html>"))
        self.m3e2.setText(_translate("NotActivePrintWidget", "E2"))
        self.m3bed.setToolTip(_translate("NotActivePrintWidget", "<html><head/><body><p><span style=\" font-size:24pt;\">0.1</span></p></body></html>"))
        self.m3bed.setText(_translate("NotActivePrintWidget", "Bed"))
        self.m3all.setToolTip(_translate("NotActivePrintWidget", "<html><head/><body><p><span style=\" font-size:24pt;\">0.1</span></p></body></html>"))
        self.m3all.setText(_translate("NotActivePrintWidget", "All"))

