# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'notactiveprintwidget.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NotActivePrintWidget(object):
    def setupUi(self, NotActivePrintWidget):
        NotActivePrintWidget.setObjectName("NotActivePrintWidget")
        NotActivePrintWidget.resize(800, 190)
        NotActivePrintWidget.setMaximumSize(QtCore.QSize(800, 480))
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(NotActivePrintWidget)
        self.horizontalLayout_5.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_2 = QtWidgets.QFrame(NotActivePrintWidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setLineWidth(0)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.PreheatPLA = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PreheatPLA.sizePolicy().hasHeightForWidth())
        self.PreheatPLA.setSizePolicy(sizePolicy)
        self.PreheatPLA.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.PreheatPLA.setObjectName("PreheatPLA")
        self.verticalLayout_2.addWidget(self.PreheatPLA)
        self.PreheatPC = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PreheatPC.sizePolicy().hasHeightForWidth())
        self.PreheatPC.setSizePolicy(sizePolicy)
        self.PreheatPC.setObjectName("PreheatPC")
        self.verticalLayout_2.addWidget(self.PreheatPC)
        self.PreheatPETG = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PreheatPETG.sizePolicy().hasHeightForWidth())
        self.PreheatPETG.setSizePolicy(sizePolicy)
        self.PreheatPETG.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.PreheatPETG.setObjectName("PreheatPETG")
        self.verticalLayout_2.addWidget(self.PreheatPETG)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.w_pushbutton_m0_extruder0 = QtWidgets.QPushButton(self.frame_2)
        self.w_pushbutton_m0_extruder0.setMinimumSize(QtCore.QSize(70, 40))
        self.w_pushbutton_m0_extruder0.setMaximumSize(QtCore.QSize(75, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.w_pushbutton_m0_extruder0.setFont(font)
        self.w_pushbutton_m0_extruder0.setToolTip("")
        self.w_pushbutton_m0_extruder0.setObjectName("w_pushbutton_m0_extruder0")
        self.horizontalLayout.addWidget(self.w_pushbutton_m0_extruder0)
        self.w_pushbutton_m0_extruder1 = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_pushbutton_m0_extruder1.sizePolicy().hasHeightForWidth())
        self.w_pushbutton_m0_extruder1.setSizePolicy(sizePolicy)
        self.w_pushbutton_m0_extruder1.setMinimumSize(QtCore.QSize(70, 40))
        self.w_pushbutton_m0_extruder1.setMaximumSize(QtCore.QSize(75, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.w_pushbutton_m0_extruder1.setFont(font)
        self.w_pushbutton_m0_extruder1.setToolTip("")
        self.w_pushbutton_m0_extruder1.setObjectName("w_pushbutton_m0_extruder1")
        self.horizontalLayout.addWidget(self.w_pushbutton_m0_extruder1)
        self.w_pushbutton_m0_bed = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_pushbutton_m0_bed.sizePolicy().hasHeightForWidth())
        self.w_pushbutton_m0_bed.setSizePolicy(sizePolicy)
        self.w_pushbutton_m0_bed.setMinimumSize(QtCore.QSize(70, 40))
        self.w_pushbutton_m0_bed.setMaximumSize(QtCore.QSize(75, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.w_pushbutton_m0_bed.setFont(font)
        self.w_pushbutton_m0_bed.setToolTip("")
        self.w_pushbutton_m0_bed.setObjectName("w_pushbutton_m0_bed")
        self.horizontalLayout.addWidget(self.w_pushbutton_m0_bed)
        self.w_pushbutton_m0_all = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_pushbutton_m0_all.sizePolicy().hasHeightForWidth())
        self.w_pushbutton_m0_all.setSizePolicy(sizePolicy)
        self.w_pushbutton_m0_all.setMinimumSize(QtCore.QSize(70, 40))
        self.w_pushbutton_m0_all.setMaximumSize(QtCore.QSize(75, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.w_pushbutton_m0_all.setFont(font)
        self.w_pushbutton_m0_all.setToolTip("")
        self.w_pushbutton_m0_all.setObjectName("w_pushbutton_m0_all")
        self.horizontalLayout.addWidget(self.w_pushbutton_m0_all)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.w_pushbutton_m1_extruder0 = QtWidgets.QPushButton(self.frame_2)
        self.w_pushbutton_m1_extruder0.setMinimumSize(QtCore.QSize(70, 40))
        self.w_pushbutton_m1_extruder0.setMaximumSize(QtCore.QSize(75, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.w_pushbutton_m1_extruder0.setFont(font)
        self.w_pushbutton_m1_extruder0.setToolTip("")
        self.w_pushbutton_m1_extruder0.setObjectName("w_pushbutton_m1_extruder0")
        self.horizontalLayout_2.addWidget(self.w_pushbutton_m1_extruder0)
        self.w_pushbutton_m1_extruder1 = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_pushbutton_m1_extruder1.sizePolicy().hasHeightForWidth())
        self.w_pushbutton_m1_extruder1.setSizePolicy(sizePolicy)
        self.w_pushbutton_m1_extruder1.setMinimumSize(QtCore.QSize(70, 40))
        self.w_pushbutton_m1_extruder1.setMaximumSize(QtCore.QSize(75, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.w_pushbutton_m1_extruder1.setFont(font)
        self.w_pushbutton_m1_extruder1.setToolTip("")
        self.w_pushbutton_m1_extruder1.setObjectName("w_pushbutton_m1_extruder1")
        self.horizontalLayout_2.addWidget(self.w_pushbutton_m1_extruder1)
        self.w_pushbutton_m1_bed = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_pushbutton_m1_bed.sizePolicy().hasHeightForWidth())
        self.w_pushbutton_m1_bed.setSizePolicy(sizePolicy)
        self.w_pushbutton_m1_bed.setMinimumSize(QtCore.QSize(70, 40))
        self.w_pushbutton_m1_bed.setMaximumSize(QtCore.QSize(75, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.w_pushbutton_m1_bed.setFont(font)
        self.w_pushbutton_m1_bed.setToolTip("")
        self.w_pushbutton_m1_bed.setObjectName("w_pushbutton_m1_bed")
        self.horizontalLayout_2.addWidget(self.w_pushbutton_m1_bed)
        self.w_pushbutton_m1_all = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_pushbutton_m1_all.sizePolicy().hasHeightForWidth())
        self.w_pushbutton_m1_all.setSizePolicy(sizePolicy)
        self.w_pushbutton_m1_all.setMinimumSize(QtCore.QSize(70, 40))
        self.w_pushbutton_m1_all.setMaximumSize(QtCore.QSize(75, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.w_pushbutton_m1_all.setFont(font)
        self.w_pushbutton_m1_all.setToolTip("")
        self.w_pushbutton_m1_all.setObjectName("w_pushbutton_m1_all")
        self.horizontalLayout_2.addWidget(self.w_pushbutton_m1_all)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.w_pushbutton_m2_extruder0 = QtWidgets.QPushButton(self.frame_2)
        self.w_pushbutton_m2_extruder0.setMinimumSize(QtCore.QSize(70, 40))
        self.w_pushbutton_m2_extruder0.setMaximumSize(QtCore.QSize(75, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.w_pushbutton_m2_extruder0.setFont(font)
        self.w_pushbutton_m2_extruder0.setToolTip("")
        self.w_pushbutton_m2_extruder0.setObjectName("w_pushbutton_m2_extruder0")
        self.horizontalLayout_3.addWidget(self.w_pushbutton_m2_extruder0)
        self.w_pushbutton_m2_extruder1 = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_pushbutton_m2_extruder1.sizePolicy().hasHeightForWidth())
        self.w_pushbutton_m2_extruder1.setSizePolicy(sizePolicy)
        self.w_pushbutton_m2_extruder1.setMinimumSize(QtCore.QSize(70, 40))
        self.w_pushbutton_m2_extruder1.setMaximumSize(QtCore.QSize(75, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.w_pushbutton_m2_extruder1.setFont(font)
        self.w_pushbutton_m2_extruder1.setToolTip("")
        self.w_pushbutton_m2_extruder1.setObjectName("w_pushbutton_m2_extruder1")
        self.horizontalLayout_3.addWidget(self.w_pushbutton_m2_extruder1)
        self.w_pushbutton_m2_bed = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_pushbutton_m2_bed.sizePolicy().hasHeightForWidth())
        self.w_pushbutton_m2_bed.setSizePolicy(sizePolicy)
        self.w_pushbutton_m2_bed.setMinimumSize(QtCore.QSize(70, 40))
        self.w_pushbutton_m2_bed.setMaximumSize(QtCore.QSize(75, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.w_pushbutton_m2_bed.setFont(font)
        self.w_pushbutton_m2_bed.setToolTip("")
        self.w_pushbutton_m2_bed.setObjectName("w_pushbutton_m2_bed")
        self.horizontalLayout_3.addWidget(self.w_pushbutton_m2_bed)
        self.w_pushbutton_m2_all = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_pushbutton_m2_all.sizePolicy().hasHeightForWidth())
        self.w_pushbutton_m2_all.setSizePolicy(sizePolicy)
        self.w_pushbutton_m2_all.setMinimumSize(QtCore.QSize(70, 40))
        self.w_pushbutton_m2_all.setMaximumSize(QtCore.QSize(75, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.w_pushbutton_m2_all.setFont(font)
        self.w_pushbutton_m2_all.setToolTip("")
        self.w_pushbutton_m2_all.setObjectName("w_pushbutton_m2_all")
        self.horizontalLayout_3.addWidget(self.w_pushbutton_m2_all)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.w_pushbutton_fan = QtWidgets.QPushButton(self.frame_2)
        self.w_pushbutton_fan.setMaximumSize(QtCore.QSize(75, 75))
        self.w_pushbutton_fan.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/fanoff.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.w_pushbutton_fan.setIcon(icon)
        self.w_pushbutton_fan.setIconSize(QtCore.QSize(65, 65))
        self.w_pushbutton_fan.setObjectName("w_pushbutton_fan")
        self.horizontalLayout_4.addWidget(self.w_pushbutton_fan)
        self.w_pushbutton_cooldown = QtWidgets.QPushButton(self.frame_2)
        self.w_pushbutton_cooldown.setMaximumSize(QtCore.QSize(75, 75))
        self.w_pushbutton_cooldown.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("img/cooldown.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.w_pushbutton_cooldown.setIcon(icon1)
        self.w_pushbutton_cooldown.setIconSize(QtCore.QSize(65, 65))
        self.w_pushbutton_cooldown.setObjectName("w_pushbutton_cooldown")
        self.horizontalLayout_4.addWidget(self.w_pushbutton_cooldown)
        self.horizontalLayout_5.addWidget(self.frame_2)

        self.retranslateUi(NotActivePrintWidget)
        QtCore.QMetaObject.connectSlotsByName(NotActivePrintWidget)

    def retranslateUi(self, NotActivePrintWidget):
        _translate = QtCore.QCoreApplication.translate
        NotActivePrintWidget.setWindowTitle(_translate("NotActivePrintWidget", "TemperatureWindow"))
        self.PreheatPLA.setText(_translate("NotActivePrintWidget", "Preheat PLA:"))
        self.PreheatPC.setText(_translate("NotActivePrintWidget", "Preheat PC:"))
        self.PreheatPETG.setText(_translate("NotActivePrintWidget", "Preheat PETG:"))
        self.w_pushbutton_m0_extruder0.setText(_translate("NotActivePrintWidget", "E0"))
        self.w_pushbutton_m0_extruder1.setText(_translate("NotActivePrintWidget", "E1"))
        self.w_pushbutton_m0_bed.setText(_translate("NotActivePrintWidget", "Bed"))
        self.w_pushbutton_m0_all.setText(_translate("NotActivePrintWidget", "All"))
        self.w_pushbutton_m1_extruder0.setText(_translate("NotActivePrintWidget", "E0"))
        self.w_pushbutton_m1_extruder1.setText(_translate("NotActivePrintWidget", "E1"))
        self.w_pushbutton_m1_bed.setText(_translate("NotActivePrintWidget", "Bed"))
        self.w_pushbutton_m1_all.setText(_translate("NotActivePrintWidget", "All"))
        self.w_pushbutton_m2_extruder0.setText(_translate("NotActivePrintWidget", "E0"))
        self.w_pushbutton_m2_extruder1.setText(_translate("NotActivePrintWidget", "E1"))
        self.w_pushbutton_m2_bed.setText(_translate("NotActivePrintWidget", "Bed"))
        self.w_pushbutton_m2_all.setText(_translate("NotActivePrintWidget", "All"))
import img_rc
