# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'printpage_qt.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PrintPage(object):
    def setupUi(self, PrintPage):
        PrintPage.setObjectName("PrintPage")
        PrintPage.resize(800, 448)
        PrintPage.setMaximumSize(QtCore.QSize(800, 448))
        self.tabWidget = QtWidgets.QTabWidget(PrintPage)
        self.tabWidget.setGeometry(QtCore.QRect(9, 9, 781, 331))
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setObjectName("tabWidget")
        self.SD = QtWidgets.QWidget()
        self.SD.setObjectName("SD")
        self.uppervertLayout = QtWidgets.QVBoxLayout(self.SD)
        self.uppervertLayout.setObjectName("uppervertLayout")
        self.sd_pathlabel = QtWidgets.QLabel(self.SD)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.sd_pathlabel.setFont(font)
        self.sd_pathlabel.setObjectName("sd_pathlabel")
        self.uppervertLayout.addWidget(self.sd_pathlabel)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.SDFileList = QtWidgets.QTableWidget(self.SD)
        self.SDFileList.setObjectName("SDFileList")
        self.SDFileList.setColumnCount(2)
        self.SDFileList.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.SDFileList.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.SDFileList.setHorizontalHeaderItem(1, item)
        self.horizontalLayout.addWidget(self.SDFileList)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushbutton_scan_sd = QtWidgets.QPushButton(self.SD)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushbutton_scan_sd.sizePolicy().hasHeightForWidth())
        self.pushbutton_scan_sd.setSizePolicy(sizePolicy)
        self.pushbutton_scan_sd.setMinimumSize(QtCore.QSize(100, 0))
        self.pushbutton_scan_sd.setMaximumSize(QtCore.QSize(100, 100))
        self.pushbutton_scan_sd.setObjectName("pushbutton_scan_sd")
        self.verticalLayout.addWidget(self.pushbutton_scan_sd)
        self.pushbutton_sd_print = QtWidgets.QPushButton(self.SD)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushbutton_sd_print.sizePolicy().hasHeightForWidth())
        self.pushbutton_sd_print.setSizePolicy(sizePolicy)
        self.pushbutton_sd_print.setMinimumSize(QtCore.QSize(100, 0))
        self.pushbutton_sd_print.setMaximumSize(QtCore.QSize(100, 100))
        self.pushbutton_sd_print.setObjectName("pushbutton_sd_print")
        self.verticalLayout.addWidget(self.pushbutton_sd_print)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.uppervertLayout.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.SD, "")
        self.USB = QtWidgets.QWidget()
        self.USB.setObjectName("USB")
        self.uppervertLayout1 = QtWidgets.QVBoxLayout(self.USB)
        self.uppervertLayout1.setObjectName("uppervertLayout1")
        self.usb_pathlabel = QtWidgets.QLabel(self.USB)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.usb_pathlabel.setFont(font)
        self.usb_pathlabel.setObjectName("usb_pathlabel")
        self.uppervertLayout1.addWidget(self.usb_pathlabel)
        self.horizontalLayout1 = QtWidgets.QHBoxLayout()
        self.horizontalLayout1.setObjectName("horizontalLayout1")
        self.USBFileList = QtWidgets.QTableWidget(self.USB)
        self.USBFileList.setObjectName("USBFileList")
        self.USBFileList.setColumnCount(2)
        self.USBFileList.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.USBFileList.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.USBFileList.setHorizontalHeaderItem(1, item)
        self.horizontalLayout1.addWidget(self.USBFileList)
        self.verticalLayout1 = QtWidgets.QVBoxLayout()
        self.verticalLayout1.setObjectName("verticalLayout1")
        self.pushbutton_usb_up = QtWidgets.QPushButton(self.USB)
        self.pushbutton_usb_up.setMinimumSize(QtCore.QSize(0, 50))
        self.pushbutton_usb_up.setObjectName("pushbutton_usb_up")
        self.verticalLayout1.addWidget(self.pushbutton_usb_up)
        self.pushbutton_usb_open = QtWidgets.QPushButton(self.USB)
        self.pushbutton_usb_open.setMinimumSize(QtCore.QSize(0, 50))
        self.pushbutton_usb_open.setObjectName("pushbutton_usb_open")
        self.verticalLayout1.addWidget(self.pushbutton_usb_open)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout1.addItem(spacerItem)
        self.pushbutton_usb_print = QtWidgets.QPushButton(self.USB)
        self.pushbutton_usb_print.setMinimumSize(QtCore.QSize(0, 100))
        self.pushbutton_usb_print.setObjectName("pushbutton_usb_print")
        self.verticalLayout1.addWidget(self.pushbutton_usb_print)
        self.horizontalLayout1.addLayout(self.verticalLayout1)
        self.uppervertLayout1.addLayout(self.horizontalLayout1)
        self.tabWidget.addTab(self.USB, "")
        self.Local = QtWidgets.QWidget()
        self.Local.setObjectName("Local")
        self.uppervertLayout2 = QtWidgets.QVBoxLayout(self.Local)
        self.uppervertLayout2.setObjectName("uppervertLayout2")
        self.loc_pathlabel = QtWidgets.QLabel(self.Local)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.loc_pathlabel.setFont(font)
        self.loc_pathlabel.setObjectName("loc_pathlabel")
        self.uppervertLayout2.addWidget(self.loc_pathlabel)
        self.horizontalLayout2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout2.setObjectName("horizontalLayout2")
        self.LocalFileList = QtWidgets.QTableWidget(self.Local)
        self.LocalFileList.setObjectName("LocalFileList")
        self.LocalFileList.setColumnCount(2)
        self.LocalFileList.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.LocalFileList.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.LocalFileList.setHorizontalHeaderItem(1, item)
        self.horizontalLayout2.addWidget(self.LocalFileList)
        self.verticalLayout2 = QtWidgets.QVBoxLayout()
        self.verticalLayout2.setObjectName("verticalLayout2")
        self.pushbutton_loc_up = QtWidgets.QPushButton(self.Local)
        self.pushbutton_loc_up.setMinimumSize(QtCore.QSize(0, 50))
        self.pushbutton_loc_up.setObjectName("pushbutton_loc_up")
        self.verticalLayout2.addWidget(self.pushbutton_loc_up)
        self.pushbutton_loc_open = QtWidgets.QPushButton(self.Local)
        self.pushbutton_loc_open.setMinimumSize(QtCore.QSize(0, 50))
        self.pushbutton_loc_open.setObjectName("pushbutton_loc_open")
        self.verticalLayout2.addWidget(self.pushbutton_loc_open)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout2.addItem(spacerItem1)
        self.pushbutton_loc_print = QtWidgets.QPushButton(self.Local)
        self.pushbutton_loc_print.setMinimumSize(QtCore.QSize(0, 100))
        self.pushbutton_loc_print.setObjectName("pushbutton_loc_print")
        self.verticalLayout2.addWidget(self.pushbutton_loc_print)
        self.horizontalLayout2.addLayout(self.verticalLayout2)
        self.uppervertLayout2.addLayout(self.horizontalLayout2)
        self.tabWidget.addTab(self.Local, "")
        self.widget = QtWidgets.QWidget(PrintPage)
        self.widget.setGeometry(QtCore.QRect(0, 332, 800, 120))
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushbutton_back = QtWidgets.QPushButton(self.widget)
        self.pushbutton_back.setMaximumSize(QtCore.QSize(100, 100))
        self.pushbutton_back.setStyleSheet("* { border: 0px; }")
        self.pushbutton_back.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushbutton_back.setIcon(icon)
        self.pushbutton_back.setIconSize(QtCore.QSize(100, 100))
        self.pushbutton_back.setObjectName("pushbutton_back")
        self.horizontalLayout_3.addWidget(self.pushbutton_back)
        spacerItem2 = QtWidgets.QSpacerItem(455, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.pushbutton_stop_print = QtWidgets.QPushButton(self.widget)
        self.pushbutton_stop_print.setMinimumSize(QtCore.QSize(100, 0))
        self.pushbutton_stop_print.setMaximumSize(QtCore.QSize(100, 100))
        self.pushbutton_stop_print.setObjectName("pushbutton_stop_print")
        self.horizontalLayout_3.addWidget(self.pushbutton_stop_print)
        self.pushbutton_active_print = QtWidgets.QPushButton(self.widget)
        self.pushbutton_active_print.setMinimumSize(QtCore.QSize(100, 0))
        self.pushbutton_active_print.setMaximumSize(QtCore.QSize(100, 100))
        self.pushbutton_active_print.setObjectName("pushbutton_active_print")
        self.horizontalLayout_3.addWidget(self.pushbutton_active_print)

        self.retranslateUi(PrintPage)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(PrintPage)

    def retranslateUi(self, PrintPage):
        _translate = QtCore.QCoreApplication.translate
        PrintPage.setWindowTitle(_translate("PrintPage", "ControlWindow"))
        self.sd_pathlabel.setText(_translate("PrintPage", "Files on Viki SD Card"))
        item = self.SDFileList.horizontalHeaderItem(0)
        item.setText(_translate("PrintPage", "Name"))
        item = self.SDFileList.horizontalHeaderItem(1)
        item.setText(_translate("PrintPage", "Size"))
        self.pushbutton_scan_sd.setText(_translate("PrintPage", "Scan SD"))
        self.pushbutton_sd_print.setText(_translate("PrintPage", "Start Print"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.SD), _translate("PrintPage", "SD"))
        self.usb_pathlabel.setText(_translate("PrintPage", "TextLabel"))
        item = self.USBFileList.horizontalHeaderItem(0)
        item.setText(_translate("PrintPage", "Name"))
        item = self.USBFileList.horizontalHeaderItem(1)
        item.setText(_translate("PrintPage", "Size"))
        self.pushbutton_usb_up.setText(_translate("PrintPage", "Up One Folder"))
        self.pushbutton_usb_open.setText(_translate("PrintPage", "Open Folder"))
        self.pushbutton_usb_print.setText(_translate("PrintPage", "Start Print"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.USB), _translate("PrintPage", "USB"))
        self.loc_pathlabel.setText(_translate("PrintPage", "TextLabel"))
        item = self.LocalFileList.horizontalHeaderItem(0)
        item.setText(_translate("PrintPage", "Name"))
        item = self.LocalFileList.horizontalHeaderItem(1)
        item.setText(_translate("PrintPage", "Size"))
        self.pushbutton_loc_up.setText(_translate("PrintPage", "Up One Folder"))
        self.pushbutton_loc_open.setText(_translate("PrintPage", "Open Folder"))
        self.pushbutton_loc_print.setText(_translate("PrintPage", "Start Print"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Local), _translate("PrintPage", "Local"))
        self.pushbutton_stop_print.setText(_translate("PrintPage", "Stop Print"))
        self.pushbutton_active_print.setText(_translate("PrintPage", "Active Print"))
import img_rc
