# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'temperaturepage_qt.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TemperaturePage(object):
    def setupUi(self, TemperaturePage):
        TemperaturePage.setObjectName("TemperaturePage")
        TemperaturePage.resize(800, 448)
        TemperaturePage.setMaximumSize(QtCore.QSize(800, 448))
        self.widget = QtWidgets.QWidget(TemperaturePage)
        self.widget.setGeometry(QtCore.QRect(20, 240, 781, 181))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_2 = QtWidgets.QWidget(TemperaturePage)
        self.widget_2.setGeometry(QtCore.QRect(10, 10, 781, 221))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.upper = QtWidgets.QHBoxLayout()
        self.upper.setObjectName("upper")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.e0label = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.e0label.setFont(font)
        self.e0label.setAlignment(QtCore.Qt.AlignCenter)
        self.e0label.setObjectName("e0label")
        self.verticalLayout_4.addWidget(self.e0label)
        self.e0temp = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.e0temp.setFont(font)
        self.e0temp.setAlignment(QtCore.Qt.AlignCenter)
        self.e0temp.setObjectName("e0temp")
        self.verticalLayout_4.addWidget(self.e0temp)
        self.e0img = QtWidgets.QPushButton(self.widget_2)
        self.e0img.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/nozzleidle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.e0img.setIcon(icon)
        self.e0img.setIconSize(QtCore.QSize(75, 75))
        self.e0img.setObjectName("e0img")
        self.verticalLayout_4.addWidget(self.e0img)
        self.upper.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.e1label = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.e1label.setFont(font)
        self.e1label.setAlignment(QtCore.Qt.AlignCenter)
        self.e1label.setObjectName("e1label")
        self.verticalLayout_3.addWidget(self.e1label)
        self.e1temp = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.e1temp.setFont(font)
        self.e1temp.setAlignment(QtCore.Qt.AlignCenter)
        self.e1temp.setObjectName("e1temp")
        self.verticalLayout_3.addWidget(self.e1temp)
        self.e1img = QtWidgets.QPushButton(self.widget_2)
        self.e1img.setText("")
        self.e1img.setIcon(icon)
        self.e1img.setIconSize(QtCore.QSize(75, 75))
        self.e1img.setObjectName("e1img")
        self.verticalLayout_3.addWidget(self.e1img)
        self.upper.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.bedlabel = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.bedlabel.setFont(font)
        self.bedlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.bedlabel.setObjectName("bedlabel")
        self.verticalLayout_2.addWidget(self.bedlabel)
        self.bedtemp = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.bedtemp.setFont(font)
        self.bedtemp.setAlignment(QtCore.Qt.AlignCenter)
        self.bedtemp.setObjectName("bedtemp")
        self.verticalLayout_2.addWidget(self.bedtemp)
        self.bedimg = QtWidgets.QPushButton(self.widget_2)
        self.bedimg.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("img/bed_unheated.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bedimg.setIcon(icon1)
        self.bedimg.setIconSize(QtCore.QSize(75, 75))
        self.bedimg.setObjectName("bedimg")
        self.verticalLayout_2.addWidget(self.bedimg)
        self.upper.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.upper)
        self.lower = QtWidgets.QHBoxLayout()
        self.lower.setObjectName("lower")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.w_pushbutton_extruder0_decrement = QtWidgets.QPushButton(self.widget_2)
        self.w_pushbutton_extruder0_decrement.setMaximumSize(QtCore.QSize(75, 75))
        self.w_pushbutton_extruder0_decrement.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("img/downarrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.w_pushbutton_extruder0_decrement.setIcon(icon2)
        self.w_pushbutton_extruder0_decrement.setIconSize(QtCore.QSize(50, 50))
        self.w_pushbutton_extruder0_decrement.setObjectName("w_pushbutton_extruder0_decrement")
        self.horizontalLayout_6.addWidget(self.w_pushbutton_extruder0_decrement)
        self.w_label_extruder0_setpoint = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.w_label_extruder0_setpoint.setFont(font)
        self.w_label_extruder0_setpoint.setAlignment(QtCore.Qt.AlignCenter)
        self.w_label_extruder0_setpoint.setObjectName("w_label_extruder0_setpoint")
        self.horizontalLayout_6.addWidget(self.w_label_extruder0_setpoint)
        self.w_pushbutton_extruder0_increment = QtWidgets.QPushButton(self.widget_2)
        self.w_pushbutton_extruder0_increment.setMaximumSize(QtCore.QSize(75, 75))
        self.w_pushbutton_extruder0_increment.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("img/uparrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.w_pushbutton_extruder0_increment.setIcon(icon3)
        self.w_pushbutton_extruder0_increment.setIconSize(QtCore.QSize(50, 50))
        self.w_pushbutton_extruder0_increment.setObjectName("w_pushbutton_extruder0_increment")
        self.horizontalLayout_6.addWidget(self.w_pushbutton_extruder0_increment)
        self.lower.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.w_pushbutton_extruder1_decrement = QtWidgets.QPushButton(self.widget_2)
        self.w_pushbutton_extruder1_decrement.setMaximumSize(QtCore.QSize(75, 75))
        self.w_pushbutton_extruder1_decrement.setText("")
        self.w_pushbutton_extruder1_decrement.setIcon(icon2)
        self.w_pushbutton_extruder1_decrement.setIconSize(QtCore.QSize(50, 50))
        self.w_pushbutton_extruder1_decrement.setObjectName("w_pushbutton_extruder1_decrement")
        self.horizontalLayout_5.addWidget(self.w_pushbutton_extruder1_decrement)
        self.w_label_extruder1_setpoint = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.w_label_extruder1_setpoint.setFont(font)
        self.w_label_extruder1_setpoint.setAlignment(QtCore.Qt.AlignCenter)
        self.w_label_extruder1_setpoint.setObjectName("w_label_extruder1_setpoint")
        self.horizontalLayout_5.addWidget(self.w_label_extruder1_setpoint)
        self.w_pushbutton_extruder1_increment = QtWidgets.QPushButton(self.widget_2)
        self.w_pushbutton_extruder1_increment.setMaximumSize(QtCore.QSize(75, 75))
        self.w_pushbutton_extruder1_increment.setText("")
        self.w_pushbutton_extruder1_increment.setIcon(icon3)
        self.w_pushbutton_extruder1_increment.setIconSize(QtCore.QSize(50, 50))
        self.w_pushbutton_extruder1_increment.setObjectName("w_pushbutton_extruder1_increment")
        self.horizontalLayout_5.addWidget(self.w_pushbutton_extruder1_increment)
        self.lower.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.w_pushbutton_bed_decrement = QtWidgets.QPushButton(self.widget_2)
        self.w_pushbutton_bed_decrement.setMaximumSize(QtCore.QSize(75, 75))
        self.w_pushbutton_bed_decrement.setText("")
        self.w_pushbutton_bed_decrement.setIcon(icon2)
        self.w_pushbutton_bed_decrement.setIconSize(QtCore.QSize(50, 50))
        self.w_pushbutton_bed_decrement.setObjectName("w_pushbutton_bed_decrement")
        self.horizontalLayout_4.addWidget(self.w_pushbutton_bed_decrement)
        self.w_label_bed_setpoint = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.w_label_bed_setpoint.setFont(font)
        self.w_label_bed_setpoint.setAlignment(QtCore.Qt.AlignCenter)
        self.w_label_bed_setpoint.setObjectName("w_label_bed_setpoint")
        self.horizontalLayout_4.addWidget(self.w_label_bed_setpoint)
        self.w_pushbutton_bed_increment = QtWidgets.QPushButton(self.widget_2)
        self.w_pushbutton_bed_increment.setMaximumSize(QtCore.QSize(75, 75))
        self.w_pushbutton_bed_increment.setText("")
        self.w_pushbutton_bed_increment.setIcon(icon3)
        self.w_pushbutton_bed_increment.setIconSize(QtCore.QSize(50, 50))
        self.w_pushbutton_bed_increment.setObjectName("w_pushbutton_bed_increment")
        self.horizontalLayout_4.addWidget(self.w_pushbutton_bed_increment)
        self.lower.addLayout(self.horizontalLayout_4)
        self.verticalLayout.addLayout(self.lower)
        self.pushbutton_back = QtWidgets.QPushButton(TemperaturePage)
        self.pushbutton_back.setGeometry(QtCore.QRect(5, 347, 90, 90))
        self.pushbutton_back.setMaximumSize(QtCore.QSize(100, 100))
        self.pushbutton_back.setStyleSheet("QPushButton { background: rgba(255,255,255,0); outline: none; border: none; } QPushButton:checked{background: rgba(255,255,255,0); outline: none; border: none;} QPushButton:pressed { background: rgba(0,0,0,0.1); outline: none; border: none; }")
        self.pushbutton_back.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("img/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushbutton_back.setIcon(icon4)
        self.pushbutton_back.setIconSize(QtCore.QSize(100, 100))
        self.pushbutton_back.setObjectName("pushbutton_back")

        self.retranslateUi(TemperaturePage)
        QtCore.QMetaObject.connectSlotsByName(TemperaturePage)

    def retranslateUi(self, TemperaturePage):
        _translate = QtCore.QCoreApplication.translate
        TemperaturePage.setWindowTitle(_translate("TemperaturePage", "TemperatureWindow"))
        self.e0label.setText(_translate("TemperaturePage", "Extruder 0"))
        self.e0temp.setText(_translate("TemperaturePage", "-----"))
        self.e1label.setText(_translate("TemperaturePage", "Extruder 1"))
        self.e1temp.setText(_translate("TemperaturePage", "-----"))
        self.bedlabel.setText(_translate("TemperaturePage", "Bed"))
        self.bedtemp.setText(_translate("TemperaturePage", "-----"))
        self.w_label_extruder0_setpoint.setText(_translate("TemperaturePage", "-----"))
        self.w_label_extruder1_setpoint.setText(_translate("TemperaturePage", "-----"))
        self.w_label_bed_setpoint.setText(_translate("TemperaturePage", "-----"))
