# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/temperaturewindow.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TemperatureWindow(object):
    def setupUi(self, TemperatureWindow):
        TemperatureWindow.setObjectName("TemperatureWindow")
        TemperatureWindow.resize(800, 480)
        TemperatureWindow.setMaximumSize(QtCore.QSize(800, 480))
        self.e1label = QtWidgets.QLabel(TemperatureWindow)
        self.e1label.setGeometry(QtCore.QRect(110, 0, 181, 61))
        self.e1label.setObjectName("e1label")
        self.e2label = QtWidgets.QLabel(TemperatureWindow)
        self.e2label.setGeometry(QtCore.QRect(330, 0, 191, 61))
        self.e2label.setObjectName("e2label")
        self.Back = QtWidgets.QPushButton(TemperatureWindow)
        self.Back.setGeometry(QtCore.QRect(10, 380, 91, 91))
        self.Back.setMaximumSize(QtCore.QSize(100, 100))
        self.Back.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Back.setIcon(icon)
        self.Back.setIconSize(QtCore.QSize(100, 100))
        self.Back.setObjectName("Back")
        self.layoutWidget = QtWidgets.QWidget(TemperatureWindow)
        self.layoutWidget.setGeometry(QtCore.QRect(160, 340, 431, 131))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.PreheatPLA = QtWidgets.QLabel(self.layoutWidget)
        self.PreheatPLA.setObjectName("PreheatPLA")
        self.horizontalLayout.addWidget(self.PreheatPLA)
        self.m1e1 = QtWidgets.QPushButton(self.layoutWidget)
        self.m1e1.setMinimumSize(QtCore.QSize(70, 30))
        self.m1e1.setMaximumSize(QtCore.QSize(75, 35))
        self.m1e1.setStyleSheet("font: 14pt \"Ubuntu\";")
        self.m1e1.setObjectName("m1e1")
        self.horizontalLayout.addWidget(self.m1e1)
        self.m1e2 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m1e2.sizePolicy().hasHeightForWidth())
        self.m1e2.setSizePolicy(sizePolicy)
        self.m1e2.setMinimumSize(QtCore.QSize(70, 30))
        self.m1e2.setMaximumSize(QtCore.QSize(75, 35))
        self.m1e2.setStyleSheet("font: 14pt \"Ubuntu\";")
        self.m1e2.setObjectName("m1e2")
        self.horizontalLayout.addWidget(self.m1e2)
        self.m1bed = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m1bed.sizePolicy().hasHeightForWidth())
        self.m1bed.setSizePolicy(sizePolicy)
        self.m1bed.setMinimumSize(QtCore.QSize(70, 30))
        self.m1bed.setMaximumSize(QtCore.QSize(75, 35))
        self.m1bed.setStyleSheet("font: 14pt \"Ubuntu\";")
        self.m1bed.setObjectName("m1bed")
        self.horizontalLayout.addWidget(self.m1bed)
        self.m1all = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m1all.sizePolicy().hasHeightForWidth())
        self.m1all.setSizePolicy(sizePolicy)
        self.m1all.setMinimumSize(QtCore.QSize(70, 30))
        self.m1all.setMaximumSize(QtCore.QSize(75, 35))
        self.m1all.setStyleSheet("font: 14pt \"Ubuntu\";")
        self.m1all.setObjectName("m1all")
        self.horizontalLayout.addWidget(self.m1all)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.PreheatPC = QtWidgets.QLabel(self.layoutWidget)
        self.PreheatPC.setObjectName("PreheatPC")
        self.horizontalLayout_2.addWidget(self.PreheatPC)
        self.m2e1 = QtWidgets.QPushButton(self.layoutWidget)
        self.m2e1.setMinimumSize(QtCore.QSize(70, 30))
        self.m2e1.setMaximumSize(QtCore.QSize(75, 35))
        self.m2e1.setStyleSheet("font: 14pt \"Ubuntu\";")
        self.m2e1.setObjectName("m2e1")
        self.horizontalLayout_2.addWidget(self.m2e1)
        self.m2e2 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m2e2.sizePolicy().hasHeightForWidth())
        self.m2e2.setSizePolicy(sizePolicy)
        self.m2e2.setMinimumSize(QtCore.QSize(70, 30))
        self.m2e2.setMaximumSize(QtCore.QSize(75, 35))
        self.m2e2.setStyleSheet("font: 14pt \"Ubuntu\";")
        self.m2e2.setObjectName("m2e2")
        self.horizontalLayout_2.addWidget(self.m2e2)
        self.m2bed = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m2bed.sizePolicy().hasHeightForWidth())
        self.m2bed.setSizePolicy(sizePolicy)
        self.m2bed.setMinimumSize(QtCore.QSize(70, 30))
        self.m2bed.setMaximumSize(QtCore.QSize(75, 35))
        self.m2bed.setStyleSheet("font: 14pt \"Ubuntu\";")
        self.m2bed.setObjectName("m2bed")
        self.horizontalLayout_2.addWidget(self.m2bed)
        self.m2all = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m2all.sizePolicy().hasHeightForWidth())
        self.m2all.setSizePolicy(sizePolicy)
        self.m2all.setMinimumSize(QtCore.QSize(70, 30))
        self.m2all.setMaximumSize(QtCore.QSize(75, 35))
        self.m2all.setStyleSheet("font: 14pt \"Ubuntu\";")
        self.m2all.setObjectName("m2all")
        self.horizontalLayout_2.addWidget(self.m2all)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.PreheatPETG = QtWidgets.QLabel(self.layoutWidget)
        self.PreheatPETG.setObjectName("PreheatPETG")
        self.horizontalLayout_3.addWidget(self.PreheatPETG)
        self.m3e1 = QtWidgets.QPushButton(self.layoutWidget)
        self.m3e1.setMinimumSize(QtCore.QSize(70, 30))
        self.m3e1.setMaximumSize(QtCore.QSize(75, 35))
        self.m3e1.setStyleSheet("font: 14pt \"Ubuntu\";")
        self.m3e1.setObjectName("m3e1")
        self.horizontalLayout_3.addWidget(self.m3e1)
        self.m3e2 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m3e2.sizePolicy().hasHeightForWidth())
        self.m3e2.setSizePolicy(sizePolicy)
        self.m3e2.setMinimumSize(QtCore.QSize(70, 30))
        self.m3e2.setMaximumSize(QtCore.QSize(75, 35))
        self.m3e2.setStyleSheet("font: 14pt \"Ubuntu\";")
        self.m3e2.setObjectName("m3e2")
        self.horizontalLayout_3.addWidget(self.m3e2)
        self.m3bed = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m3bed.sizePolicy().hasHeightForWidth())
        self.m3bed.setSizePolicy(sizePolicy)
        self.m3bed.setMinimumSize(QtCore.QSize(70, 30))
        self.m3bed.setMaximumSize(QtCore.QSize(75, 35))
        self.m3bed.setStyleSheet("font: 14pt \"Ubuntu\";")
        self.m3bed.setObjectName("m3bed")
        self.horizontalLayout_3.addWidget(self.m3bed)
        self.m3all = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.m3all.sizePolicy().hasHeightForWidth())
        self.m3all.setSizePolicy(sizePolicy)
        self.m3all.setMinimumSize(QtCore.QSize(70, 30))
        self.m3all.setMaximumSize(QtCore.QSize(75, 35))
        self.m3all.setStyleSheet("font: 14pt \"Ubuntu\";")
        self.m3all.setObjectName("m3all")
        self.horizontalLayout_3.addWidget(self.m3all)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.bedlabel = QtWidgets.QLabel(TemperatureWindow)
        self.bedlabel.setGeometry(QtCore.QRect(620, 0, 81, 61))
        self.bedlabel.setObjectName("bedlabel")
        self.e2img = QtWidgets.QLabel(TemperatureWindow)
        self.e2img.setGeometry(QtCore.QRect(340, 100, 131, 131))
        self.e2img.setText("")
        self.e2img.setPixmap(QtGui.QPixmap("img/nozzle2.png"))
        self.e2img.setScaledContents(True)
        self.e2img.setObjectName("e2img")
        self.e1img = QtWidgets.QLabel(TemperatureWindow)
        self.e1img.setGeometry(QtCore.QRect(100, 100, 131, 131))
        self.e1img.setText("")
        self.e1img.setPixmap(QtGui.QPixmap("img/nozzle2.png"))
        self.e1img.setScaledContents(True)
        self.e1img.setObjectName("e1img")
        self.bedimg = QtWidgets.QLabel(TemperatureWindow)
        self.bedimg.setGeometry(QtCore.QRect(590, 100, 131, 131))
        self.bedimg.setText("")
        self.bedimg.setPixmap(QtGui.QPixmap("img/bed_unheated.png"))
        self.bedimg.setScaledContents(True)
        self.bedimg.setObjectName("bedimg")
        self.layoutWidget1 = QtWidgets.QWidget(TemperatureWindow)
        self.layoutWidget1.setGeometry(QtCore.QRect(30, 240, 751, 91))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.e1neg = QtWidgets.QPushButton(self.layoutWidget1)
        self.e1neg.setMaximumSize(QtCore.QSize(75, 75))
        self.e1neg.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("img/downarrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.e1neg.setIcon(icon1)
        self.e1neg.setIconSize(QtCore.QSize(50, 50))
        self.e1neg.setObjectName("e1neg")
        self.horizontalLayout_6.addWidget(self.e1neg)
        self.e1set = QtWidgets.QLabel(self.layoutWidget1)
        self.e1set.setObjectName("e1set")
        self.horizontalLayout_6.addWidget(self.e1set)
        self.e1pos = QtWidgets.QPushButton(self.layoutWidget1)
        self.e1pos.setMaximumSize(QtCore.QSize(75, 75))
        self.e1pos.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("img/uparrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.e1pos.setIcon(icon2)
        self.e1pos.setIconSize(QtCore.QSize(50, 50))
        self.e1pos.setObjectName("e1pos")
        self.horizontalLayout_6.addWidget(self.e1pos)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.e2neg = QtWidgets.QPushButton(self.layoutWidget1)
        self.e2neg.setMaximumSize(QtCore.QSize(75, 75))
        self.e2neg.setText("")
        self.e2neg.setIcon(icon1)
        self.e2neg.setIconSize(QtCore.QSize(50, 50))
        self.e2neg.setObjectName("e2neg")
        self.horizontalLayout_5.addWidget(self.e2neg)
        self.e2set = QtWidgets.QLabel(self.layoutWidget1)
        self.e2set.setObjectName("e2set")
        self.horizontalLayout_5.addWidget(self.e2set)
        self.e2pos = QtWidgets.QPushButton(self.layoutWidget1)
        self.e2pos.setMaximumSize(QtCore.QSize(75, 75))
        self.e2pos.setText("")
        self.e2pos.setIcon(icon2)
        self.e2pos.setIconSize(QtCore.QSize(50, 50))
        self.e2pos.setObjectName("e2pos")
        self.horizontalLayout_5.addWidget(self.e2pos)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.bedneg = QtWidgets.QPushButton(self.layoutWidget1)
        self.bedneg.setMaximumSize(QtCore.QSize(75, 75))
        self.bedneg.setText("")
        self.bedneg.setIcon(icon1)
        self.bedneg.setIconSize(QtCore.QSize(50, 50))
        self.bedneg.setObjectName("bedneg")
        self.horizontalLayout_4.addWidget(self.bedneg)
        self.bedset = QtWidgets.QLabel(self.layoutWidget1)
        self.bedset.setObjectName("bedset")
        self.horizontalLayout_4.addWidget(self.bedset)
        self.bedpos = QtWidgets.QPushButton(self.layoutWidget1)
        self.bedpos.setMaximumSize(QtCore.QSize(75, 75))
        self.bedpos.setText("")
        self.bedpos.setIcon(icon2)
        self.bedpos.setIconSize(QtCore.QSize(50, 50))
        self.bedpos.setObjectName("bedpos")
        self.horizontalLayout_4.addWidget(self.bedpos)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_4)
        self.layoutWidget2 = QtWidgets.QWidget(TemperatureWindow)
        self.layoutWidget2.setGeometry(QtCore.QRect(120, 50, 561, 51))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.e1temp = QtWidgets.QLabel(self.layoutWidget2)
        self.e1temp.setObjectName("e1temp")
        self.horizontalLayout_8.addWidget(self.e1temp)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.e2temp = QtWidgets.QLabel(self.layoutWidget2)
        self.e2temp.setObjectName("e2temp")
        self.horizontalLayout_8.addWidget(self.e2temp)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.bedtemp = QtWidgets.QLabel(self.layoutWidget2)
        self.bedtemp.setObjectName("bedtemp")
        self.horizontalLayout_8.addWidget(self.bedtemp)
        self.CoolDown = QtWidgets.QPushButton(TemperatureWindow)
        self.CoolDown.setGeometry(QtCore.QRect(700, 390, 75, 75))
        self.CoolDown.setMaximumSize(QtCore.QSize(75, 75))
        self.CoolDown.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("img/cooldown.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.CoolDown.setIcon(icon3)
        self.CoolDown.setIconSize(QtCore.QSize(65, 65))
        self.CoolDown.setObjectName("CoolDown")
        self.Fan = QtWidgets.QPushButton(TemperatureWindow)
        self.Fan.setGeometry(QtCore.QRect(610, 390, 75, 75))
        self.Fan.setMaximumSize(QtCore.QSize(75, 75))
        self.Fan.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("img/fanoff.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Fan.setIcon(icon4)
        self.Fan.setIconSize(QtCore.QSize(65, 65))
        self.Fan.setObjectName("Fan")

        self.retranslateUi(TemperatureWindow)
        QtCore.QMetaObject.connectSlotsByName(TemperatureWindow)

    def retranslateUi(self, TemperatureWindow):
        _translate = QtCore.QCoreApplication.translate
        TemperatureWindow.setWindowTitle(_translate("TemperatureWindow", "TemperatureWindow"))
        self.e1label.setText(_translate("TemperatureWindow", "<html><head/><body><p><span style=\" font-size:22pt; font-weight:600;\">Extruder 1</span></p></body></html>"))
        self.e2label.setText(_translate("TemperatureWindow", "<html><head/><body><p><span style=\" font-size:24pt; font-weight:600;\">Extruder 2</span></p></body></html>"))
        self.PreheatPLA.setText(_translate("TemperatureWindow", "Preheat PLA"))
        self.m1e1.setToolTip(_translate("TemperatureWindow", "<html><head/><body><p><span style=\" font-size:24pt;\">0.1</span></p></body></html>"))
        self.m1e1.setText(_translate("TemperatureWindow", "E1"))
        self.m1e2.setToolTip(_translate("TemperatureWindow", "<html><head/><body><p><span style=\" font-size:24pt;\">0.1</span></p></body></html>"))
        self.m1e2.setText(_translate("TemperatureWindow", "E2"))
        self.m1bed.setToolTip(_translate("TemperatureWindow", "<html><head/><body><p><span style=\" font-size:24pt;\">0.1</span></p></body></html>"))
        self.m1bed.setText(_translate("TemperatureWindow", "Bed"))
        self.m1all.setToolTip(_translate("TemperatureWindow", "<html><head/><body><p><span style=\" font-size:24pt;\">0.1</span></p></body></html>"))
        self.m1all.setText(_translate("TemperatureWindow", "All"))
        self.PreheatPC.setText(_translate("TemperatureWindow", "Preheat PC"))
        self.m2e1.setToolTip(_translate("TemperatureWindow", "<html><head/><body><p><span style=\" font-size:24pt;\">0.1</span></p></body></html>"))
        self.m2e1.setText(_translate("TemperatureWindow", "E1"))
        self.m2e2.setToolTip(_translate("TemperatureWindow", "<html><head/><body><p><span style=\" font-size:24pt;\">0.1</span></p></body></html>"))
        self.m2e2.setText(_translate("TemperatureWindow", "E2"))
        self.m2bed.setToolTip(_translate("TemperatureWindow", "<html><head/><body><p><span style=\" font-size:24pt;\">0.1</span></p></body></html>"))
        self.m2bed.setText(_translate("TemperatureWindow", "Bed"))
        self.m2all.setToolTip(_translate("TemperatureWindow", "<html><head/><body><p><span style=\" font-size:24pt;\">0.1</span></p></body></html>"))
        self.m2all.setText(_translate("TemperatureWindow", "All"))
        self.PreheatPETG.setText(_translate("TemperatureWindow", "Preheat PETG"))
        self.m3e1.setToolTip(_translate("TemperatureWindow", "<html><head/><body><p><span style=\" font-size:24pt;\">0.1</span></p></body></html>"))
        self.m3e1.setText(_translate("TemperatureWindow", "E1"))
        self.m3e2.setToolTip(_translate("TemperatureWindow", "<html><head/><body><p><span style=\" font-size:24pt;\">0.1</span></p></body></html>"))
        self.m3e2.setText(_translate("TemperatureWindow", "E2"))
        self.m3bed.setToolTip(_translate("TemperatureWindow", "<html><head/><body><p><span style=\" font-size:24pt;\">0.1</span></p></body></html>"))
        self.m3bed.setText(_translate("TemperatureWindow", "Bed"))
        self.m3all.setToolTip(_translate("TemperatureWindow", "<html><head/><body><p><span style=\" font-size:24pt;\">0.1</span></p></body></html>"))
        self.m3all.setText(_translate("TemperatureWindow", "All"))
        self.bedlabel.setText(_translate("TemperatureWindow", "<html><head/><body><p><span style=\" font-size:24pt; font-weight:600;\">Bed</span></p></body></html>"))
        self.e1set.setText(_translate("TemperatureWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt;\">-----</span></p></body></html>"))
        self.e2set.setText(_translate("TemperatureWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt;\">-----</span></p></body></html>"))
        self.bedset.setText(_translate("TemperatureWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt;\">-----</span></p></body></html>"))
        self.e1temp.setText(_translate("TemperatureWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt;\">-----</span></p></body></html>"))
        self.e2temp.setText(_translate("TemperatureWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt;\">-----</span></p></body></html>"))
        self.bedtemp.setText(_translate("TemperatureWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt;\">-----</span></p></body></html>"))

