# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'temperaturepage_qt.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TemperaturePage(object):
    def setupUi(self, TemperaturePage):
        TemperaturePage.setObjectName("TemperaturePage")
        TemperaturePage.resize(800, 448)
        TemperaturePage.setMaximumSize(QtCore.QSize(800, 448))
        self.widget = QtWidgets.QWidget(TemperaturePage)
        self.widget.setGeometry(QtCore.QRect(20, 250, 781, 171))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_2 = QtWidgets.QWidget(TemperaturePage)
        self.widget_2.setGeometry(QtCore.QRect(10, 10, 781, 231))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.upper = QtWidgets.QHBoxLayout()
        self.upper.setObjectName("upper")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.e1label = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.e1label.setFont(font)
        self.e1label.setAlignment(QtCore.Qt.AlignCenter)
        self.e1label.setObjectName("e1label")
        self.verticalLayout_4.addWidget(self.e1label)
        self.e1temp = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.e1temp.setFont(font)
        self.e1temp.setAlignment(QtCore.Qt.AlignCenter)
        self.e1temp.setObjectName("e1temp")
        self.verticalLayout_4.addWidget(self.e1temp)
        self.e1img = QtWidgets.QPushButton(self.widget_2)
        self.e1img.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/nozzleidle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.e1img.setIcon(icon)
        self.e1img.setIconSize(QtCore.QSize(90, 90))
        self.e1img.setObjectName("e1img")
        self.verticalLayout_4.addWidget(self.e1img)
        self.upper.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.e2label = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.e2label.setFont(font)
        self.e2label.setAlignment(QtCore.Qt.AlignCenter)
        self.e2label.setObjectName("e2label")
        self.verticalLayout_3.addWidget(self.e2label)
        self.e2temp = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.e2temp.setFont(font)
        self.e2temp.setAlignment(QtCore.Qt.AlignCenter)
        self.e2temp.setObjectName("e2temp")
        self.verticalLayout_3.addWidget(self.e2temp)
        self.e2img = QtWidgets.QPushButton(self.widget_2)
        self.e2img.setText("")
        self.e2img.setIcon(icon)
        self.e2img.setIconSize(QtCore.QSize(80, 80))
        self.e2img.setObjectName("e2img")
        self.verticalLayout_3.addWidget(self.e2img)
        self.upper.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.bedlabel = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.bedlabel.setFont(font)
        self.bedlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.bedlabel.setObjectName("bedlabel")
        self.verticalLayout_2.addWidget(self.bedlabel)
        self.bedtemp = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.bedtemp.setFont(font)
        self.bedtemp.setAlignment(QtCore.Qt.AlignCenter)
        self.bedtemp.setObjectName("bedtemp")
        self.verticalLayout_2.addWidget(self.bedtemp)
        self.bedimg = QtWidgets.QPushButton(self.widget_2)
        self.bedimg.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("img/bed_unheated.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bedimg.setIcon(icon1)
        self.bedimg.setIconSize(QtCore.QSize(80, 80))
        self.bedimg.setObjectName("bedimg")
        self.verticalLayout_2.addWidget(self.bedimg)
        self.upper.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.upper)
        self.lower = QtWidgets.QHBoxLayout()
        self.lower.setObjectName("lower")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.e1neg = QtWidgets.QPushButton(self.widget_2)
        self.e1neg.setMaximumSize(QtCore.QSize(75, 75))
        self.e1neg.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("img/downarrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.e1neg.setIcon(icon2)
        self.e1neg.setIconSize(QtCore.QSize(50, 50))
        self.e1neg.setObjectName("e1neg")
        self.horizontalLayout_6.addWidget(self.e1neg)
        self.e1set = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.e1set.setFont(font)
        self.e1set.setAlignment(QtCore.Qt.AlignCenter)
        self.e1set.setObjectName("e1set")
        self.horizontalLayout_6.addWidget(self.e1set)
        self.e1pos = QtWidgets.QPushButton(self.widget_2)
        self.e1pos.setMaximumSize(QtCore.QSize(75, 75))
        self.e1pos.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("img/uparrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.e1pos.setIcon(icon3)
        self.e1pos.setIconSize(QtCore.QSize(50, 50))
        self.e1pos.setObjectName("e1pos")
        self.horizontalLayout_6.addWidget(self.e1pos)
        self.lower.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.e2neg = QtWidgets.QPushButton(self.widget_2)
        self.e2neg.setMaximumSize(QtCore.QSize(75, 75))
        self.e2neg.setText("")
        self.e2neg.setIcon(icon2)
        self.e2neg.setIconSize(QtCore.QSize(50, 50))
        self.e2neg.setObjectName("e2neg")
        self.horizontalLayout_5.addWidget(self.e2neg)
        self.e2set = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.e2set.setFont(font)
        self.e2set.setAlignment(QtCore.Qt.AlignCenter)
        self.e2set.setObjectName("e2set")
        self.horizontalLayout_5.addWidget(self.e2set)
        self.e2pos = QtWidgets.QPushButton(self.widget_2)
        self.e2pos.setMaximumSize(QtCore.QSize(75, 75))
        self.e2pos.setText("")
        self.e2pos.setIcon(icon3)
        self.e2pos.setIconSize(QtCore.QSize(50, 50))
        self.e2pos.setObjectName("e2pos")
        self.horizontalLayout_5.addWidget(self.e2pos)
        self.lower.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.bedneg = QtWidgets.QPushButton(self.widget_2)
        self.bedneg.setMaximumSize(QtCore.QSize(75, 75))
        self.bedneg.setText("")
        self.bedneg.setIcon(icon2)
        self.bedneg.setIconSize(QtCore.QSize(50, 50))
        self.bedneg.setObjectName("bedneg")
        self.horizontalLayout_4.addWidget(self.bedneg)
        self.bedset = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.bedset.setFont(font)
        self.bedset.setAlignment(QtCore.Qt.AlignCenter)
        self.bedset.setObjectName("bedset")
        self.horizontalLayout_4.addWidget(self.bedset)
        self.bedpos = QtWidgets.QPushButton(self.widget_2)
        self.bedpos.setMaximumSize(QtCore.QSize(75, 75))
        self.bedpos.setText("")
        self.bedpos.setIcon(icon3)
        self.bedpos.setIconSize(QtCore.QSize(50, 50))
        self.bedpos.setObjectName("bedpos")
        self.horizontalLayout_4.addWidget(self.bedpos)
        self.lower.addLayout(self.horizontalLayout_4)
        self.verticalLayout.addLayout(self.lower)
        self.pushbutton_back = QtWidgets.QPushButton(TemperaturePage)
        self.pushbutton_back.setGeometry(QtCore.QRect(5, 347, 90, 90))
        self.pushbutton_back.setMaximumSize(QtCore.QSize(100, 100))
        self.pushbutton_back.setStyleSheet("QPushButton { background: rgba(255,255,255,0); outline: none; border: none; } QPushButton:checked{background: rgba(255,255,255,0); outline: none; border: none;} QPushButton:pressed { background: rgba(0,0,0,0.1); outline: none; border: none; }")
        self.pushbutton_back.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("img/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushbutton_back.setIcon(icon4)
        self.pushbutton_back.setIconSize(QtCore.QSize(100, 100))
        self.pushbutton_back.setObjectName("pushbutton_back")

        self.retranslateUi(TemperaturePage)
        QtCore.QMetaObject.connectSlotsByName(TemperaturePage)

    def retranslateUi(self, TemperaturePage):
        _translate = QtCore.QCoreApplication.translate
        TemperaturePage.setWindowTitle(_translate("TemperaturePage", "TemperatureWindow"))
        self.e1label.setText(_translate("TemperaturePage", "Extruder 0"))
        self.e1temp.setText(_translate("TemperaturePage", "-----"))
        self.e2label.setText(_translate("TemperaturePage", "Extruder 1"))
        self.e2temp.setText(_translate("TemperaturePage", "-----"))
        self.bedlabel.setText(_translate("TemperaturePage", "Bed"))
        self.bedtemp.setText(_translate("TemperaturePage", "-----"))
        self.e1set.setText(_translate("TemperaturePage", "-----"))
        self.e2set.setText(_translate("TemperaturePage", "-----"))
        self.bedset.setText(_translate("TemperaturePage", "-----"))
