# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'temperaturepage_qt.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TemperaturePage(object):
    def setupUi(self, TemperaturePage):
        TemperaturePage.setObjectName("TemperaturePage")
        TemperaturePage.resize(800, 448)
        TemperaturePage.setMaximumSize(QtCore.QSize(800, 448))
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(TemperaturePage)
        self.verticalLayout_7.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_7.setSpacing(10)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.widget_2 = QtWidgets.QWidget(TemperaturePage)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.e0img = QtWidgets.QPushButton(self.widget_2)
        self.e0img.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/img/Extruder_1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.e0img.setIcon(icon)
        self.e0img.setIconSize(QtCore.QSize(100, 99))
        self.e0img.setObjectName("e0img")
        self.verticalLayout_2.addWidget(self.e0img)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.e0temp = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.e0temp.setFont(font)
        self.e0temp.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.e0temp.setObjectName("e0temp")
        self.horizontalLayout.addWidget(self.e0temp)
        self.e0slash = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.e0slash.setFont(font)
        self.e0slash.setAlignment(QtCore.Qt.AlignCenter)
        self.e0slash.setObjectName("e0slash")
        self.horizontalLayout.addWidget(self.e0slash)
        self.w_label_extruder0_setpoint = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.w_label_extruder0_setpoint.setFont(font)
        self.w_label_extruder0_setpoint.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.w_label_extruder0_setpoint.setObjectName("w_label_extruder0_setpoint")
        self.horizontalLayout.addWidget(self.w_label_extruder0_setpoint)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(26)
        self.verticalLayout.setObjectName("verticalLayout")
        self.w_pushbutton_extruder0_increment = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_pushbutton_extruder0_increment.sizePolicy().hasHeightForWidth())
        self.w_pushbutton_extruder0_increment.setSizePolicy(sizePolicy)
        self.w_pushbutton_extruder0_increment.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.w_pushbutton_extruder0_increment.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/img/img/UP.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.w_pushbutton_extruder0_increment.setIcon(icon1)
        self.w_pushbutton_extruder0_increment.setIconSize(QtCore.QSize(60, 60))
        self.w_pushbutton_extruder0_increment.setObjectName("w_pushbutton_extruder0_increment")
        self.verticalLayout.addWidget(self.w_pushbutton_extruder0_increment)
        self.w_pushbutton_extruder0_decrement = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_pushbutton_extruder0_decrement.sizePolicy().hasHeightForWidth())
        self.w_pushbutton_extruder0_decrement.setSizePolicy(sizePolicy)
        self.w_pushbutton_extruder0_decrement.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.w_pushbutton_extruder0_decrement.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/img/img/Down.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.w_pushbutton_extruder0_decrement.setIcon(icon2)
        self.w_pushbutton_extruder0_decrement.setIconSize(QtCore.QSize(60, 60))
        self.w_pushbutton_extruder0_decrement.setObjectName("w_pushbutton_extruder0_decrement")
        self.verticalLayout.addWidget(self.w_pushbutton_extruder0_decrement)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.e1img = QtWidgets.QPushButton(self.widget_2)
        self.e1img.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/img/img/Extruder_2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.e1img.setIcon(icon3)
        self.e1img.setIconSize(QtCore.QSize(100, 99))
        self.e1img.setObjectName("e1img")
        self.verticalLayout_5.addWidget(self.e1img)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.e1temp = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.e1temp.setFont(font)
        self.e1temp.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.e1temp.setObjectName("e1temp")
        self.horizontalLayout_2.addWidget(self.e1temp)
        self.e1slash = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.e1slash.setFont(font)
        self.e1slash.setAlignment(QtCore.Qt.AlignCenter)
        self.e1slash.setObjectName("e1slash")
        self.horizontalLayout_2.addWidget(self.e1slash)
        self.w_label_extruder1_setpoint = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.w_label_extruder1_setpoint.setFont(font)
        self.w_label_extruder1_setpoint.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.w_label_extruder1_setpoint.setObjectName("w_label_extruder1_setpoint")
        self.horizontalLayout_2.addWidget(self.w_label_extruder1_setpoint)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_5)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(26)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.w_pushbutton_extruder1_increment = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_pushbutton_extruder1_increment.sizePolicy().hasHeightForWidth())
        self.w_pushbutton_extruder1_increment.setSizePolicy(sizePolicy)
        self.w_pushbutton_extruder1_increment.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.w_pushbutton_extruder1_increment.setText("")
        self.w_pushbutton_extruder1_increment.setIcon(icon1)
        self.w_pushbutton_extruder1_increment.setIconSize(QtCore.QSize(60, 60))
        self.w_pushbutton_extruder1_increment.setObjectName("w_pushbutton_extruder1_increment")
        self.verticalLayout_4.addWidget(self.w_pushbutton_extruder1_increment)
        self.w_pushbutton_extruder1_decrement = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_pushbutton_extruder1_decrement.sizePolicy().hasHeightForWidth())
        self.w_pushbutton_extruder1_decrement.setSizePolicy(sizePolicy)
        self.w_pushbutton_extruder1_decrement.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.w_pushbutton_extruder1_decrement.setText("")
        self.w_pushbutton_extruder1_decrement.setIcon(icon2)
        self.w_pushbutton_extruder1_decrement.setIconSize(QtCore.QSize(60, 60))
        self.w_pushbutton_extruder1_decrement.setObjectName("w_pushbutton_extruder1_decrement")
        self.verticalLayout_4.addWidget(self.w_pushbutton_extruder1_decrement)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.bedimg = QtWidgets.QPushButton(self.widget_2)
        self.bedimg.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/img/img/Bed.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bedimg.setIcon(icon4)
        self.bedimg.setIconSize(QtCore.QSize(100, 99))
        self.bedimg.setObjectName("bedimg")
        self.verticalLayout_6.addWidget(self.bedimg)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.bedtemp = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.bedtemp.setFont(font)
        self.bedtemp.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.bedtemp.setObjectName("bedtemp")
        self.horizontalLayout_3.addWidget(self.bedtemp)
        self.bedslash = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.bedslash.setFont(font)
        self.bedslash.setAlignment(QtCore.Qt.AlignCenter)
        self.bedslash.setObjectName("bedslash")
        self.horizontalLayout_3.addWidget(self.bedslash)
        self.w_label_bed_setpoint = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.w_label_bed_setpoint.setFont(font)
        self.w_label_bed_setpoint.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.w_label_bed_setpoint.setObjectName("w_label_bed_setpoint")
        self.horizontalLayout_3.addWidget(self.w_label_bed_setpoint)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4.addLayout(self.verticalLayout_6)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(26)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.w_pushbutton_bed_increment = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_pushbutton_bed_increment.sizePolicy().hasHeightForWidth())
        self.w_pushbutton_bed_increment.setSizePolicy(sizePolicy)
        self.w_pushbutton_bed_increment.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.w_pushbutton_bed_increment.setText("")
        self.w_pushbutton_bed_increment.setIcon(icon1)
        self.w_pushbutton_bed_increment.setIconSize(QtCore.QSize(60, 60))
        self.w_pushbutton_bed_increment.setObjectName("w_pushbutton_bed_increment")
        self.verticalLayout_3.addWidget(self.w_pushbutton_bed_increment)
        self.w_pushbutton_bed_decrement = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.w_pushbutton_bed_decrement.sizePolicy().hasHeightForWidth())
        self.w_pushbutton_bed_decrement.setSizePolicy(sizePolicy)
        self.w_pushbutton_bed_decrement.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.w_pushbutton_bed_decrement.setText("")
        self.w_pushbutton_bed_decrement.setIcon(icon2)
        self.w_pushbutton_bed_decrement.setIconSize(QtCore.QSize(60, 60))
        self.w_pushbutton_bed_decrement.setObjectName("w_pushbutton_bed_decrement")
        self.verticalLayout_3.addWidget(self.w_pushbutton_bed_decrement)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_7.addWidget(self.widget_2)
        self.widget = QtWidgets.QWidget(TemperaturePage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_7.addWidget(self.widget)

        self.retranslateUi(TemperaturePage)
        QtCore.QMetaObject.connectSlotsByName(TemperaturePage)

    def retranslateUi(self, TemperaturePage):
        _translate = QtCore.QCoreApplication.translate
        TemperaturePage.setWindowTitle(_translate("TemperaturePage", "TemperatureWindow"))
        self.e0temp.setText(_translate("TemperaturePage", "-----"))
        self.e0slash.setText(_translate("TemperaturePage", "/"))
        self.w_label_extruder0_setpoint.setText(_translate("TemperaturePage", "-----"))
        self.e1temp.setText(_translate("TemperaturePage", "-----"))
        self.e1slash.setText(_translate("TemperaturePage", "/"))
        self.w_label_extruder1_setpoint.setText(_translate("TemperaturePage", "-----"))
        self.bedtemp.setText(_translate("TemperaturePage", "-----"))
        self.bedslash.setText(_translate("TemperaturePage", "/"))
        self.w_label_bed_setpoint.setText(_translate("TemperaturePage", "-----"))
import img_rc
