# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/temperaturewindow.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TemperatureWindow(object):
    def setupUi(self, TemperatureWindow):
        TemperatureWindow.setObjectName("TemperatureWindow")
        TemperatureWindow.resize(800, 480)
        TemperatureWindow.setMaximumSize(QtCore.QSize(800, 480))
        self.gridLayout = QtWidgets.QGridLayout(TemperatureWindow)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.e1label = QtWidgets.QLabel(TemperatureWindow)
        self.e1label.setObjectName("e1label")
        self.verticalLayout_4.addWidget(self.e1label)
        self.e1temp = QtWidgets.QLabel(TemperatureWindow)
        self.e1temp.setObjectName("e1temp")
        self.verticalLayout_4.addWidget(self.e1temp)
        self.e1img = QtWidgets.QPushButton(TemperatureWindow)
        self.e1img.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/nozzleidle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.e1img.setIcon(icon)
        self.e1img.setIconSize(QtCore.QSize(100, 100))
        self.e1img.setObjectName("e1img")
        self.verticalLayout_4.addWidget(self.e1img)
        self.horizontalLayout_8.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.e2label = QtWidgets.QLabel(TemperatureWindow)
        self.e2label.setObjectName("e2label")
        self.verticalLayout_3.addWidget(self.e2label)
        self.e2temp = QtWidgets.QLabel(TemperatureWindow)
        self.e2temp.setObjectName("e2temp")
        self.verticalLayout_3.addWidget(self.e2temp)
        self.e2img = QtWidgets.QPushButton(TemperatureWindow)
        self.e2img.setText("")
        self.e2img.setIcon(icon)
        self.e2img.setIconSize(QtCore.QSize(100, 100))
        self.e2img.setObjectName("e2img")
        self.verticalLayout_3.addWidget(self.e2img)
        self.horizontalLayout_8.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.bedlabel = QtWidgets.QLabel(TemperatureWindow)
        self.bedlabel.setObjectName("bedlabel")
        self.verticalLayout_2.addWidget(self.bedlabel)
        self.bedtemp = QtWidgets.QLabel(TemperatureWindow)
        self.bedtemp.setObjectName("bedtemp")
        self.verticalLayout_2.addWidget(self.bedtemp)
        self.bedimg = QtWidgets.QPushButton(TemperatureWindow)
        self.bedimg.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("img/bed_unheated.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bedimg.setIcon(icon1)
        self.bedimg.setIconSize(QtCore.QSize(100, 100))
        self.bedimg.setObjectName("bedimg")
        self.verticalLayout_2.addWidget(self.bedimg)
        self.horizontalLayout_8.addLayout(self.verticalLayout_2)
        self.gridLayout.addLayout(self.horizontalLayout_8, 0, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.e1neg = QtWidgets.QPushButton(TemperatureWindow)
        self.e1neg.setMaximumSize(QtCore.QSize(75, 75))
        self.e1neg.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("img/downarrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.e1neg.setIcon(icon2)
        self.e1neg.setIconSize(QtCore.QSize(50, 50))
        self.e1neg.setObjectName("e1neg")
        self.horizontalLayout_6.addWidget(self.e1neg)
        self.e1set = QtWidgets.QLabel(TemperatureWindow)
        self.e1set.setObjectName("e1set")
        self.horizontalLayout_6.addWidget(self.e1set)
        self.e1pos = QtWidgets.QPushButton(TemperatureWindow)
        self.e1pos.setMaximumSize(QtCore.QSize(75, 75))
        self.e1pos.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("img/uparrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.e1pos.setIcon(icon3)
        self.e1pos.setIconSize(QtCore.QSize(50, 50))
        self.e1pos.setObjectName("e1pos")
        self.horizontalLayout_6.addWidget(self.e1pos)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.e2neg = QtWidgets.QPushButton(TemperatureWindow)
        self.e2neg.setMaximumSize(QtCore.QSize(75, 75))
        self.e2neg.setText("")
        self.e2neg.setIcon(icon2)
        self.e2neg.setIconSize(QtCore.QSize(50, 50))
        self.e2neg.setObjectName("e2neg")
        self.horizontalLayout_5.addWidget(self.e2neg)
        self.e2set = QtWidgets.QLabel(TemperatureWindow)
        self.e2set.setObjectName("e2set")
        self.horizontalLayout_5.addWidget(self.e2set)
        self.e2pos = QtWidgets.QPushButton(TemperatureWindow)
        self.e2pos.setMaximumSize(QtCore.QSize(75, 75))
        self.e2pos.setText("")
        self.e2pos.setIcon(icon3)
        self.e2pos.setIconSize(QtCore.QSize(50, 50))
        self.e2pos.setObjectName("e2pos")
        self.horizontalLayout_5.addWidget(self.e2pos)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.bedneg = QtWidgets.QPushButton(TemperatureWindow)
        self.bedneg.setMaximumSize(QtCore.QSize(75, 75))
        self.bedneg.setText("")
        self.bedneg.setIcon(icon2)
        self.bedneg.setIconSize(QtCore.QSize(50, 50))
        self.bedneg.setObjectName("bedneg")
        self.horizontalLayout_4.addWidget(self.bedneg)
        self.bedset = QtWidgets.QLabel(TemperatureWindow)
        self.bedset.setObjectName("bedset")
        self.horizontalLayout_4.addWidget(self.bedset)
        self.bedpos = QtWidgets.QPushButton(TemperatureWindow)
        self.bedpos.setMaximumSize(QtCore.QSize(75, 75))
        self.bedpos.setText("")
        self.bedpos.setIcon(icon3)
        self.bedpos.setIconSize(QtCore.QSize(50, 50))
        self.bedpos.setObjectName("bedpos")
        self.horizontalLayout_4.addWidget(self.bedpos)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_4)
        self.gridLayout.addLayout(self.horizontalLayout_7, 1, 0, 1, 1)

        self.retranslateUi(TemperatureWindow)
        QtCore.QMetaObject.connectSlotsByName(TemperatureWindow)

    def retranslateUi(self, TemperatureWindow):
        _translate = QtCore.QCoreApplication.translate
        TemperatureWindow.setWindowTitle(_translate("TemperatureWindow", "TemperatureWindow"))
        self.e1label.setText(_translate("TemperatureWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt; font-weight:600;\">Extruder 1</span></p></body></html>"))
        self.e1temp.setText(_translate("TemperatureWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt;\">-----</span></p></body></html>"))
        self.e2label.setText(_translate("TemperatureWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt; font-weight:600;\">Extruder 2</span></p></body></html>"))
        self.e2temp.setText(_translate("TemperatureWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt;\">-----</span></p></body></html>"))
        self.bedlabel.setText(_translate("TemperatureWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt; font-weight:600;\">Bed</span></p></body></html>"))
        self.bedtemp.setText(_translate("TemperatureWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt;\">-----</span></p></body></html>"))
        self.e1set.setText(_translate("TemperatureWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt;\">-----</span></p></body></html>"))
        self.e2set.setText(_translate("TemperatureWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt;\">-----</span></p></body></html>"))
        self.bedset.setText(_translate("TemperatureWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt;\">-----</span></p></body></html>"))

