# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/touchdisplaywindow.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from builtins import object
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TouchDisplay(object):
    def setupUi(self, TouchDisplay):
        TouchDisplay.setObjectName("TouchDisplay")
        TouchDisplay.resize(800, 480)
        TouchDisplay.setMinimumSize(QtCore.QSize(800, 480))
        TouchDisplay.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.verticalLayout = QtWidgets.QVBoxLayout(TouchDisplay)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Title = QtWidgets.QLabel(TouchDisplay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Title.sizePolicy().hasHeightForWidth())
        self.Title.setSizePolicy(sizePolicy)
        self.Title.setObjectName("Title")
        self.horizontalLayout_3.addWidget(self.Title)
        self.re3DIcon = QtWidgets.QLabel(TouchDisplay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.re3DIcon.sizePolicy().hasHeightForWidth())
        self.re3DIcon.setSizePolicy(sizePolicy)
        self.re3DIcon.setMaximumSize(QtCore.QSize(120, 120))
        self.re3DIcon.setText("")
        self.re3DIcon.setPixmap(QtGui.QPixmap("img/re3d.png"))
        self.re3DIcon.setScaledContents(True)
        self.re3DIcon.setObjectName("re3DIcon")
        self.horizontalLayout_3.addWidget(self.re3DIcon)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Print = QtWidgets.QPushButton(TouchDisplay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Print.sizePolicy().hasHeightForWidth())
        self.Print.setSizePolicy(sizePolicy)
        self.Print.setMinimumSize(QtCore.QSize(150, 150))
        self.Print.setMaximumSize(QtCore.QSize(150, 300))
        self.Print.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/print.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Print.setIcon(icon)
        self.Print.setIconSize(QtCore.QSize(150, 150))
        self.Print.setObjectName("Print")
        self.horizontalLayout_2.addWidget(self.Print)
        self.Control = QtWidgets.QPushButton(TouchDisplay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Control.sizePolicy().hasHeightForWidth())
        self.Control.setSizePolicy(sizePolicy)
        self.Control.setMinimumSize(QtCore.QSize(150, 150))
        self.Control.setMaximumSize(QtCore.QSize(150, 300))
        self.Control.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("img/control.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Control.setIcon(icon1)
        self.Control.setIconSize(QtCore.QSize(150, 150))
        self.Control.setObjectName("Control")
        self.horizontalLayout_2.addWidget(self.Control)
        self.Temperature = QtWidgets.QPushButton(TouchDisplay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Temperature.sizePolicy().hasHeightForWidth())
        self.Temperature.setSizePolicy(sizePolicy)
        self.Temperature.setMinimumSize(QtCore.QSize(150, 150))
        self.Temperature.setMaximumSize(QtCore.QSize(150, 300))
        self.Temperature.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("img/temperature.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Temperature.setIcon(icon2)
        self.Temperature.setIconSize(QtCore.QSize(150, 150))
        self.Temperature.setObjectName("Temperature")
        self.horizontalLayout_2.addWidget(self.Temperature)
        self.Settings = QtWidgets.QPushButton(TouchDisplay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Settings.sizePolicy().hasHeightForWidth())
        self.Settings.setSizePolicy(sizePolicy)
        self.Settings.setMinimumSize(QtCore.QSize(150, 150))
        self.Settings.setMaximumSize(QtCore.QSize(150, 300))
        self.Settings.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("img/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Settings.setIcon(icon3)
        self.Settings.setIconSize(QtCore.QSize(150, 150))
        self.Settings.setObjectName("Settings")
        self.horizontalLayout_2.addWidget(self.Settings)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(0, 75, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(TouchDisplay)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 70))
        self.label.setMaximumSize(QtCore.QSize(16777215, 70))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(TouchDisplay)
        QtCore.QMetaObject.connectSlotsByName(TouchDisplay)

    def retranslateUi(self, TouchDisplay):
        _translate = QtCore.QCoreApplication.translate
        TouchDisplay.setWindowTitle(_translate("TouchDisplay", "Form"))
        self.Title.setText(_translate("TouchDisplay", "<html><head/><body><p><span style=\" font-size:36pt;\">re:3Display</span></p></body></html>"))
        self.label.setText(_translate("TouchDisplay", "V.1.0.0 re3Display"))

