# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'userupdatepage_qt.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UserUpdatePage(object):
    def setupUi(self, UserUpdatePage):
        UserUpdatePage.setObjectName("UserUpdatePage")
        UserUpdatePage.resize(800, 448)
        UserUpdatePage.setMaximumSize(QtCore.QSize(800, 448))
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        UserUpdatePage.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(UserUpdatePage)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.LeftBar = QtWidgets.QWidget(UserUpdatePage)
        self.LeftBar.setObjectName("LeftBar")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.LeftBar)
        self.verticalLayout_6.setContentsMargins(-1, -1, -1, 9)
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.CheckUpdate = QtWidgets.QPushButton(self.LeftBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CheckUpdate.sizePolicy().hasHeightForWidth())
        self.CheckUpdate.setSizePolicy(sizePolicy)
        self.CheckUpdate.setMinimumSize(QtCore.QSize(160, 85))
        self.CheckUpdate.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.CheckUpdate.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/img/Check_for_Update.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.CheckUpdate.setIcon(icon)
        self.CheckUpdate.setIconSize(QtCore.QSize(140, 65))
        self.CheckUpdate.setObjectName("CheckUpdate")
        self.verticalLayout_6.addWidget(self.CheckUpdate)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_6.addItem(spacerItem1)
        self.horizontalLayout_3.addWidget(self.LeftBar)
        self.MainLayout = QtWidgets.QWidget(UserUpdatePage)
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        self.MainLayout.setFont(font)
        self.MainLayout.setObjectName("MainLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.MainLayout)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.SoftwareTableLayout = QtWidgets.QHBoxLayout()
        self.SoftwareTableLayout.setObjectName("SoftwareTableLayout")
        self.horizontalLayout_4.addLayout(self.SoftwareTableLayout)
        self.DebugOutput = QtWidgets.QTextBrowser(self.MainLayout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DebugOutput.sizePolicy().hasHeightForWidth())
        self.DebugOutput.setSizePolicy(sizePolicy)
        self.DebugOutput.setMaximumSize(QtCore.QSize(250, 16777215))
        self.DebugOutput.setObjectName("DebugOutput")
        self.horizontalLayout_4.addWidget(self.DebugOutput)
        self.horizontalLayout_3.addWidget(self.MainLayout)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.BottomBar = QtWidgets.QWidget(UserUpdatePage)
        self.BottomBar.setObjectName("BottomBar")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.BottomBar)
        self.horizontalLayout_2.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Back = QtWidgets.QPushButton(self.BottomBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Back.sizePolicy().hasHeightForWidth())
        self.Back.setSizePolicy(sizePolicy)
        self.Back.setMinimumSize(QtCore.QSize(65, 65))
        self.Back.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Back.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Back.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/img/img/Small_arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Back.setIcon(icon1)
        self.Back.setIconSize(QtCore.QSize(55, 55))
        self.Back.setObjectName("Back")
        self.horizontalLayout_2.addWidget(self.Back)
        self.CurrentVersion = QtWidgets.QLabel(self.BottomBar)
        self.CurrentVersion.setObjectName("CurrentVersion")
        self.horizontalLayout_2.addWidget(self.CurrentVersion)
        spacerItem2 = QtWidgets.QSpacerItem(282, 40, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.Update = QtWidgets.QPushButton(self.BottomBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Update.sizePolicy().hasHeightForWidth())
        self.Update.setSizePolicy(sizePolicy)
        self.Update.setMinimumSize(QtCore.QSize(0, 0))
        self.Update.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Update.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/img/img/Update-rollback.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Update.setIcon(icon2)
        self.Update.setIconSize(QtCore.QSize(120, 60))
        self.Update.setObjectName("Update")
        self.horizontalLayout_2.addWidget(self.Update)
        self.verticalLayout.addWidget(self.BottomBar)

        self.retranslateUi(UserUpdatePage)
        QtCore.QMetaObject.connectSlotsByName(UserUpdatePage)

    def retranslateUi(self, UserUpdatePage):
        _translate = QtCore.QCoreApplication.translate
        UserUpdatePage.setWindowTitle(_translate("UserUpdatePage", "ControlWindow"))
        self.CurrentVersion.setText(_translate("UserUpdatePage", "Current Version:"))
import img_rc
